/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "paralelo_serial_rx.v:1" *)
module paralelo_serial_rx_synth(active, clk_4f, clk_32f, rst_L, idle_out);
  (* src = "paralelo_serial_rx.v:31" *)
  wire [7:0] _00_;
  (* src = "paralelo_serial_rx.v:12" *)
  wire [2:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  (* src = "paralelo_serial_rx.v:2" *)
  input active;
  (* src = "paralelo_serial_rx.v:4" *)
  input clk_32f;
  (* src = "paralelo_serial_rx.v:3" *)
  input clk_4f;
  (* src = "paralelo_serial_rx.v:9" *)
  wire [7:0] data2send;
  (* src = "paralelo_serial_rx.v:6" *)
  output idle_out;
  (* src = "paralelo_serial_rx.v:8" *)
  wire [2:0] index;
  (* src = "paralelo_serial_rx.v:5" *)
  input rst_L;
  NOT _38_ (
    .A(index[2]),
    .Y(_02_)
  );
  NOT _39_ (
    .A(index[1]),
    .Y(_03_)
  );
  NOT _40_ (
    .A(index[0]),
    .Y(_04_)
  );
  NOT _41_ (
    .A(data2send[4]),
    .Y(_05_)
  );
  NOT _42_ (
    .A(data2send[2]),
    .Y(_06_)
  );
  NOT _43_ (
    .A(data2send[1]),
    .Y(_07_)
  );
  NOT _44_ (
    .A(rst_L),
    .Y(_08_)
  );
  NOR _45_ (
    .A(index[1]),
    .B(index[0]),
    .Y(_09_)
  );
  NOT _46_ (
    .A(_09_),
    .Y(_10_)
  );
  NOR _47_ (
    .A(_02_),
    .B(data2send[3]),
    .Y(_11_)
  );
  NOR _48_ (
    .A(index[2]),
    .B(data2send[7]),
    .Y(_12_)
  );
  NOT _49_ (
    .A(_12_),
    .Y(_13_)
  );
  NAND _50_ (
    .A(_09_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _51_ (
    .A(_11_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _52_ (
    .A(index[1]),
    .B(index[0]),
    .Y(_16_)
  );
  NOT _53_ (
    .A(_16_),
    .Y(_17_)
  );
  NOR _54_ (
    .A(_02_),
    .B(data2send[0]),
    .Y(_18_)
  );
  NAND _55_ (
    .A(_02_),
    .B(_05_),
    .Y(_19_)
  );
  NAND _56_ (
    .A(_17_),
    .B(_19_),
    .Y(_20_)
  );
  NOR _57_ (
    .A(_18_),
    .B(_20_),
    .Y(_21_)
  );
  NOR _58_ (
    .A(index[2]),
    .B(data2send[6]),
    .Y(_22_)
  );
  NAND _59_ (
    .A(index[2]),
    .B(_06_),
    .Y(_23_)
  );
  NOR _60_ (
    .A(index[1]),
    .B(_04_),
    .Y(_24_)
  );
  NAND _61_ (
    .A(_23_),
    .B(_24_),
    .Y(_25_)
  );
  NOR _62_ (
    .A(_22_),
    .B(_25_),
    .Y(_26_)
  );
  NOR _63_ (
    .A(index[2]),
    .B(data2send[5]),
    .Y(_27_)
  );
  NAND _64_ (
    .A(index[2]),
    .B(_07_),
    .Y(_28_)
  );
  NOR _65_ (
    .A(_03_),
    .B(index[0]),
    .Y(_29_)
  );
  NAND _66_ (
    .A(_28_),
    .B(_29_),
    .Y(_30_)
  );
  NOR _67_ (
    .A(_27_),
    .B(_30_),
    .Y(_31_)
  );
  NOR _68_ (
    .A(_21_),
    .B(_31_),
    .Y(_32_)
  );
  NOR _69_ (
    .A(_15_),
    .B(_26_),
    .Y(_33_)
  );
  NAND _70_ (
    .A(_32_),
    .B(_33_),
    .Y(idle_out)
  );
  NAND _71_ (
    .A(rst_L),
    .B(_10_),
    .Y(_34_)
  );
  NOR _72_ (
    .A(_17_),
    .B(_34_),
    .Y(_01_[1])
  );
  NOR _73_ (
    .A(index[0]),
    .B(_08_),
    .Y(_01_[0])
  );
  NOR _74_ (
    .A(_08_),
    .B(active),
    .Y(_00_[7])
  );
  NOT _75_ (
    .A(_00_[7]),
    .Y(_00_[6])
  );
  NOR _76_ (
    .A(_02_),
    .B(_16_),
    .Y(_35_)
  );
  NAND _77_ (
    .A(_02_),
    .B(_16_),
    .Y(_36_)
  );
  NAND _78_ (
    .A(rst_L),
    .B(_36_),
    .Y(_37_)
  );
  NOR _79_ (
    .A(_35_),
    .B(_37_),
    .Y(_01_[2])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _80_ (
    .C(clk_4f),
    .D(1'h0),
    .Q(data2send[0])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _81_ (
    .C(clk_4f),
    .D(1'h0),
    .Q(data2send[1])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _82_ (
    .C(clk_4f),
    .D(1'h1),
    .Q(data2send[2])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _83_ (
    .C(clk_4f),
    .D(1'h1),
    .Q(data2send[3])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _84_ (
    .C(clk_4f),
    .D(1'h1),
    .Q(data2send[4])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _85_ (
    .C(clk_4f),
    .D(1'h1),
    .Q(data2send[5])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _86_ (
    .C(clk_4f),
    .D(_00_[6]),
    .Q(data2send[6])
  );
  (* src = "paralelo_serial_rx.v:31" *)
  DFF _87_ (
    .C(clk_4f),
    .D(_00_[7]),
    .Q(data2send[7])
  );
  (* src = "paralelo_serial_rx.v:12" *)
  DFF _88_ (
    .C(clk_32f),
    .D(_01_[0]),
    .Q(index[0])
  );
  (* src = "paralelo_serial_rx.v:12" *)
  DFF _89_ (
    .C(clk_32f),
    .D(_01_[1]),
    .Q(index[1])
  );
  (* src = "paralelo_serial_rx.v:12" *)
  DFF _90_ (
    .C(clk_32f),
    .D(_01_[2]),
    .Q(index[2])
  );
  assign _00_[5:0] = 6'h3c;
endmodule
