/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "paralelo_serial.v:1" *)
module paralelo_serial_synth(data_out, reset_L, clk_32f, data_in, valid_in);
  (* src = "paralelo_serial.v:15" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* src = "paralelo_serial.v:4" *)
  input clk_32f;
  (* src = "paralelo_serial.v:5" *)
  input [7:0] data_in;
  (* src = "paralelo_serial.v:2" *)
  output data_out;
  (* src = "paralelo_serial.v:8" *)
  wire [2:0] index;
  (* src = "paralelo_serial.v:3" *)
  input reset_L;
  (* src = "paralelo_serial.v:6" *)
  input valid_in;
  NOT _42_ (
    .A(valid_in),
    .Y(_01_)
  );
  NOT _43_ (
    .A(data_in[5]),
    .Y(_02_)
  );
  NOT _44_ (
    .A(reset_L),
    .Y(_03_)
  );
  NOT _45_ (
    .A(index[1]),
    .Y(_04_)
  );
  NOT _46_ (
    .A(index[2]),
    .Y(_05_)
  );
  NOR _47_ (
    .A(_03_),
    .B(index[0]),
    .Y(_00_[0])
  );
  NAND _48_ (
    .A(index[0]),
    .B(index[1]),
    .Y(_06_)
  );
  NOT _49_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _50_ (
    .A(index[0]),
    .B(index[1]),
    .Y(_08_)
  );
  NOT _51_ (
    .A(_08_),
    .Y(_09_)
  );
  NAND _52_ (
    .A(reset_L),
    .B(_09_),
    .Y(_10_)
  );
  NOR _53_ (
    .A(_07_),
    .B(_10_),
    .Y(_00_[1])
  );
  NOR _54_ (
    .A(_05_),
    .B(_06_),
    .Y(_11_)
  );
  NAND _55_ (
    .A(_05_),
    .B(_06_),
    .Y(_12_)
  );
  NAND _56_ (
    .A(reset_L),
    .B(_12_),
    .Y(_13_)
  );
  NOR _57_ (
    .A(_11_),
    .B(_13_),
    .Y(_00_[2])
  );
  NOR _58_ (
    .A(_01_),
    .B(index[2]),
    .Y(_14_)
  );
  NOR _59_ (
    .A(data_in[4]),
    .B(_06_),
    .Y(_15_)
  );
  NAND _60_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  NAND _61_ (
    .A(reset_L),
    .B(_16_),
    .Y(_17_)
  );
  NOT _62_ (
    .A(_17_),
    .Y(_18_)
  );
  NAND _63_ (
    .A(valid_in),
    .B(_08_),
    .Y(_19_)
  );
  NAND _64_ (
    .A(data_in[7]),
    .B(_05_),
    .Y(_20_)
  );
  NAND _65_ (
    .A(data_in[3]),
    .B(index[2]),
    .Y(_21_)
  );
  NAND _66_ (
    .A(_20_),
    .B(_21_),
    .Y(_22_)
  );
  NOR _67_ (
    .A(_19_),
    .B(_22_),
    .Y(_23_)
  );
  NAND _68_ (
    .A(data_in[0]),
    .B(valid_in),
    .Y(_24_)
  );
  NAND _69_ (
    .A(_11_),
    .B(_24_),
    .Y(_25_)
  );
  NOT _70_ (
    .A(_25_),
    .Y(_26_)
  );
  NOR _71_ (
    .A(_23_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _72_ (
    .A(_18_),
    .B(_27_),
    .Y(_28_)
  );
  NAND _73_ (
    .A(data_in[6]),
    .B(_14_),
    .Y(_29_)
  );
  NAND _74_ (
    .A(index[0]),
    .B(_04_),
    .Y(_30_)
  );
  NOR _75_ (
    .A(_01_),
    .B(data_in[2]),
    .Y(_31_)
  );
  NOR _76_ (
    .A(_05_),
    .B(_31_),
    .Y(_32_)
  );
  NOR _77_ (
    .A(_30_),
    .B(_32_),
    .Y(_33_)
  );
  NAND _78_ (
    .A(_29_),
    .B(_33_),
    .Y(_34_)
  );
  NAND _79_ (
    .A(_02_),
    .B(_14_),
    .Y(_35_)
  );
  NAND _80_ (
    .A(valid_in),
    .B(data_in[1]),
    .Y(_36_)
  );
  NAND _81_ (
    .A(index[2]),
    .B(_36_),
    .Y(_37_)
  );
  NAND _82_ (
    .A(_35_),
    .B(_37_),
    .Y(_38_)
  );
  NOR _83_ (
    .A(index[0]),
    .B(_04_),
    .Y(_39_)
  );
  NAND _84_ (
    .A(_38_),
    .B(_39_),
    .Y(_40_)
  );
  NAND _85_ (
    .A(_34_),
    .B(_40_),
    .Y(_41_)
  );
  NOR _86_ (
    .A(_28_),
    .B(_41_),
    .Y(data_out)
  );
  (* src = "paralelo_serial.v:15" *)
  DFF _87_ (
    .C(clk_32f),
    .D(_00_[0]),
    .Q(index[0])
  );
  (* src = "paralelo_serial.v:15" *)
  DFF _88_ (
    .C(clk_32f),
    .D(_00_[1]),
    .Q(index[1])
  );
  (* src = "paralelo_serial.v:15" *)
  DFF _89_ (
    .C(clk_32f),
    .D(_00_[2]),
    .Q(index[2])
  );
endmodule
