/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* src = "logica_muxes/MUX1_L1.v:1" *)
module MUX1_L1_synth(data_00, valid_00, reset_L, clk_2f, data_0, data_1, valid_0, valid_1);
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  wire [7:0] _000_;
  (* src = "logica_muxes/MUX1_L1.v:20" *)
  wire _001_;
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "logica_muxes/MUX1_L1.v:5" *)
  input clk_2f;
  (* src = "logica_muxes/MUX1_L1.v:6" *)
  input [7:0] data_0;
  (* src = "logica_muxes/MUX1_L1.v:2" *)
  output [7:0] data_00;
  (* src = "logica_muxes/MUX1_L1.v:7" *)
  input [7:0] data_1;
  (* src = "logica_muxes/MUX1_L1.v:4" *)
  input reset_L;
  (* init = 1'h0 *)
  (* src = "logica_muxes/MUX1_L1.v:14" *)
  wire selector_2f;
  (* src = "logica_muxes/MUX1_L1.v:8" *)
  input valid_0;
  (* src = "logica_muxes/MUX1_L1.v:3" *)
  output valid_00;
  (* src = "logica_muxes/MUX1_L1.v:9" *)
  input valid_1;
  NOT _070_ (
    .A(reset_L),
    .Y(_017_)
  );
  NOT _071_ (
    .A(selector_2f),
    .Y(_001_)
  );
  NOT _072_ (
    .A(valid_1),
    .Y(_018_)
  );
  NAND _073_ (
    .A(selector_2f),
    .B(valid_1),
    .Y(_019_)
  );
  NAND _074_ (
    .A(_001_),
    .B(valid_0),
    .Y(_020_)
  );
  NAND _075_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _076_ (
    .A(selector_2f),
    .B(valid_0),
    .Y(_022_)
  );
  NAND _077_ (
    .A(selector_2f),
    .B(_018_),
    .Y(_023_)
  );
  NAND _078_ (
    .A(reset_L),
    .B(_023_),
    .Y(_024_)
  );
  NOR _079_ (
    .A(_022_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _080_ (
    .A(reset_L),
    .B(_021_),
    .Y(_026_)
  );
  NAND _081_ (
    .A(_017_),
    .B(valid_00),
    .Y(_027_)
  );
  NAND _082_ (
    .A(_026_),
    .B(_027_),
    .Y(_002_)
  );
  NOR _083_ (
    .A(data_0[0]),
    .B(selector_2f),
    .Y(_028_)
  );
  NOR _084_ (
    .A(data_1[0]),
    .B(_001_),
    .Y(_029_)
  );
  NOR _085_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _086_ (
    .A(_026_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _087_ (
    .A(reset_L),
    .B(data_00[0]),
    .Y(_032_)
  );
  NOT _088_ (
    .A(_032_),
    .Y(_033_)
  );
  NOR _089_ (
    .A(_025_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _090_ (
    .A(_031_),
    .B(_034_),
    .Y(_000_[0])
  );
  NOR _091_ (
    .A(selector_2f),
    .B(data_0[1]),
    .Y(_035_)
  );
  NOR _092_ (
    .A(_001_),
    .B(data_1[1]),
    .Y(_036_)
  );
  NOR _093_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _094_ (
    .A(_026_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _095_ (
    .A(data_00[1]),
    .B(reset_L),
    .Y(_039_)
  );
  NOT _096_ (
    .A(_039_),
    .Y(_040_)
  );
  NOR _097_ (
    .A(_025_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _098_ (
    .A(_038_),
    .B(_041_),
    .Y(_000_[1])
  );
  NOR _099_ (
    .A(selector_2f),
    .B(data_0[2]),
    .Y(_042_)
  );
  NOR _100_ (
    .A(_001_),
    .B(data_1[2]),
    .Y(_043_)
  );
  NOR _101_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _102_ (
    .A(_026_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _103_ (
    .A(reset_L),
    .B(data_00[2]),
    .Y(_046_)
  );
  NOT _104_ (
    .A(_046_),
    .Y(_047_)
  );
  NOR _105_ (
    .A(_025_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _106_ (
    .A(_045_),
    .B(_048_),
    .Y(_000_[2])
  );
  NOR _107_ (
    .A(selector_2f),
    .B(data_0[3]),
    .Y(_049_)
  );
  NOR _108_ (
    .A(_001_),
    .B(data_1[3]),
    .Y(_050_)
  );
  NOR _109_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _110_ (
    .A(_026_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _111_ (
    .A(reset_L),
    .B(data_00[3]),
    .Y(_053_)
  );
  NOT _112_ (
    .A(_053_),
    .Y(_054_)
  );
  NOR _113_ (
    .A(_025_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _114_ (
    .A(_052_),
    .B(_055_),
    .Y(_000_[3])
  );
  NOR _115_ (
    .A(selector_2f),
    .B(data_0[4]),
    .Y(_056_)
  );
  NOR _116_ (
    .A(_001_),
    .B(data_1[4]),
    .Y(_057_)
  );
  NOR _117_ (
    .A(_056_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _118_ (
    .A(_026_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _119_ (
    .A(reset_L),
    .B(data_00[4]),
    .Y(_060_)
  );
  NOT _120_ (
    .A(_060_),
    .Y(_061_)
  );
  NOR _121_ (
    .A(_025_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _122_ (
    .A(_059_),
    .B(_062_),
    .Y(_000_[4])
  );
  NOR _123_ (
    .A(selector_2f),
    .B(data_0[5]),
    .Y(_063_)
  );
  NOR _124_ (
    .A(_001_),
    .B(data_1[5]),
    .Y(_064_)
  );
  NOR _125_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _126_ (
    .A(_026_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _127_ (
    .A(reset_L),
    .B(data_00[5]),
    .Y(_067_)
  );
  NOT _128_ (
    .A(_067_),
    .Y(_068_)
  );
  NOR _129_ (
    .A(_025_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _130_ (
    .A(_066_),
    .B(_069_),
    .Y(_000_[5])
  );
  NOR _131_ (
    .A(selector_2f),
    .B(data_0[6]),
    .Y(_003_)
  );
  NOR _132_ (
    .A(_001_),
    .B(data_1[6]),
    .Y(_004_)
  );
  NOR _133_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  NOR _134_ (
    .A(_026_),
    .B(_005_),
    .Y(_006_)
  );
  NAND _135_ (
    .A(reset_L),
    .B(data_00[6]),
    .Y(_007_)
  );
  NOT _136_ (
    .A(_007_),
    .Y(_008_)
  );
  NOR _137_ (
    .A(_025_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _138_ (
    .A(_006_),
    .B(_009_),
    .Y(_000_[6])
  );
  NOR _139_ (
    .A(selector_2f),
    .B(data_0[7]),
    .Y(_010_)
  );
  NOR _140_ (
    .A(_001_),
    .B(data_1[7]),
    .Y(_011_)
  );
  NOR _141_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _142_ (
    .A(_026_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _143_ (
    .A(reset_L),
    .B(data_00[7]),
    .Y(_014_)
  );
  NOT _144_ (
    .A(_014_),
    .Y(_015_)
  );
  NOR _145_ (
    .A(_025_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _146_ (
    .A(_013_),
    .B(_016_),
    .Y(_000_[7])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _147_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_00[0])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _148_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_00[1])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _149_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_00[2])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _150_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_00[3])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _151_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_00[4])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _152_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_00[5])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _153_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_00[6])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _154_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_00[7])
  );
  (* src = "logica_muxes/MUX1_L1.v:39" *)
  DFF _155_ (
    .C(clk_2f),
    .D(_002_),
    .Q(valid_00)
  );
  (* src = "logica_muxes/MUX1_L1.v:20" *)
  DFF _156_ (
    .C(clk_2f),
    .D(_001_),
    .Q(selector_2f)
  );
endmodule

(* src = "logica_muxes/MUXES.v:4" *)
module MUXES_synth(data_000, valid_000, reset_L, clk_f, clk_2f, clk_4f, data_0, data_1, data_2, data_3, valid_0, valid_1, valid_2, valid_3);
  (* src = "logica_muxes/MUXES.v:9" *)
  input clk_2f;
  (* src = "logica_muxes/MUXES.v:10" *)
  input clk_4f;
  (* src = "logica_muxes/MUXES.v:8" *)
  input clk_f;
  (* src = "logica_muxes/MUXES.v:11" *)
  input [7:0] data_0;
  (* src = "logica_muxes/MUXES.v:5" *)
  output [7:0] data_000;
  (* src = "logica_muxes/MUXES.v:12" *)
  input [7:0] data_1;
  (* src = "logica_muxes/MUXES.v:13" *)
  input [7:0] data_2;
  (* src = "logica_muxes/MUXES.v:14" *)
  input [7:0] data_3;
  (* src = "logica_muxes/MUXES.v:20" *)
  wire [7:0] data__00;
  (* src = "logica_muxes/MUXES.v:20" *)
  wire [7:0] data__11;
  (* src = "logica_muxes/MUXES.v:7" *)
  input reset_L;
  (* src = "logica_muxes/MUXES.v:15" *)
  input valid_0;
  (* src = "logica_muxes/MUXES.v:6" *)
  output valid_000;
  (* src = "logica_muxes/MUXES.v:16" *)
  input valid_1;
  (* src = "logica_muxes/MUXES.v:17" *)
  input valid_2;
  (* src = "logica_muxes/MUXES.v:18" *)
  input valid_3;
  (* src = "logica_muxes/MUXES.v:21" *)
  wire valid__00;
  (* src = "logica_muxes/MUXES.v:21" *)
  wire valid__11;
  (* module_not_derived = 32'd1 *)
  (* src = "logica_muxes/MUXES.v:24" *)
  MUX1_L1 MUX1 (
    .clk_2f(clk_2f),
    .data_0(data_0),
    .data_00(data__00),
    .data_1(data_1),
    .reset_L(reset_L),
    .valid_0(valid_0),
    .valid_00(valid__00),
    .valid_1(valid_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "logica_muxes/MUXES.v:33" *)
  MUX1_L1 MUX2 (
    .clk_2f(clk_2f),
    .data_0(data_2),
    .data_00(data__11),
    .data_1(data_3),
    .reset_L(reset_L),
    .valid_0(valid_2),
    .valid_00(valid__11),
    .valid_1(valid_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "logica_muxes/MUXES.v:42" *)
  MUX_L2 MUX3 (
    .clk_4f(clk_4f),
    .data_00(data__00),
    .data_000(data_000),
    .data_11(data__11),
    .reset_L(reset_L),
    .valid_00(valid__00),
    .valid_000(valid_000),
    .valid_11(valid__11)
  );
endmodule

(* src = "logica_muxes/MUX_L2.v:1" *)
module MUX_L2_synth(data_000, valid_000, reset_L, clk_4f, data_00, data_11, valid_00, valid_11);
  (* src = "logica_muxes/MUX_L2.v:38" *)
  wire [7:0] _000_;
  (* src = "logica_muxes/MUX_L2.v:19" *)
  wire _001_;
  (* src = "logica_muxes/MUX_L2.v:38" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "logica_muxes/MUX_L2.v:5" *)
  input clk_4f;
  (* src = "logica_muxes/MUX_L2.v:6" *)
  input [7:0] data_00;
  (* src = "logica_muxes/MUX_L2.v:2" *)
  output [7:0] data_000;
  (* src = "logica_muxes/MUX_L2.v:7" *)
  input [7:0] data_11;
  (* src = "logica_muxes/MUX_L2.v:4" *)
  input reset_L;
  (* init = 1'h1 *)
  (* src = "logica_muxes/MUX_L2.v:13" *)
  wire selector_4f;
  (* src = "logica_muxes/MUX_L2.v:8" *)
  input valid_00;
  (* src = "logica_muxes/MUX_L2.v:3" *)
  output valid_000;
  (* src = "logica_muxes/MUX_L2.v:9" *)
  input valid_11;
  NOT _070_ (
    .A(reset_L),
    .Y(_017_)
  );
  NOT _071_ (
    .A(selector_4f),
    .Y(_001_)
  );
  NOT _072_ (
    .A(valid_11),
    .Y(_018_)
  );
  NAND _073_ (
    .A(selector_4f),
    .B(valid_11),
    .Y(_019_)
  );
  NAND _074_ (
    .A(_001_),
    .B(valid_00),
    .Y(_020_)
  );
  NAND _075_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _076_ (
    .A(selector_4f),
    .B(valid_00),
    .Y(_022_)
  );
  NAND _077_ (
    .A(selector_4f),
    .B(_018_),
    .Y(_023_)
  );
  NAND _078_ (
    .A(reset_L),
    .B(_023_),
    .Y(_024_)
  );
  NOR _079_ (
    .A(_022_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _080_ (
    .A(reset_L),
    .B(_021_),
    .Y(_026_)
  );
  NOR _081_ (
    .A(data_00[0]),
    .B(selector_4f),
    .Y(_027_)
  );
  NOR _082_ (
    .A(data_11[0]),
    .B(_001_),
    .Y(_028_)
  );
  NOR _083_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _084_ (
    .A(_026_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _085_ (
    .A(reset_L),
    .B(data_000[0]),
    .Y(_031_)
  );
  NOT _086_ (
    .A(_031_),
    .Y(_032_)
  );
  NOR _087_ (
    .A(_025_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _088_ (
    .A(_030_),
    .B(_033_),
    .Y(_000_[0])
  );
  NOR _089_ (
    .A(selector_4f),
    .B(data_00[1]),
    .Y(_034_)
  );
  NOR _090_ (
    .A(_001_),
    .B(data_11[1]),
    .Y(_035_)
  );
  NOR _091_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _092_ (
    .A(_026_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _093_ (
    .A(reset_L),
    .B(data_000[1]),
    .Y(_038_)
  );
  NOT _094_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _095_ (
    .A(_025_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _096_ (
    .A(_037_),
    .B(_040_),
    .Y(_000_[1])
  );
  NOR _097_ (
    .A(selector_4f),
    .B(data_00[2]),
    .Y(_041_)
  );
  NOR _098_ (
    .A(_001_),
    .B(data_11[2]),
    .Y(_042_)
  );
  NOR _099_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _100_ (
    .A(_026_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _101_ (
    .A(reset_L),
    .B(data_000[2]),
    .Y(_045_)
  );
  NOT _102_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _103_ (
    .A(_025_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _104_ (
    .A(_044_),
    .B(_047_),
    .Y(_000_[2])
  );
  NOR _105_ (
    .A(selector_4f),
    .B(data_00[3]),
    .Y(_048_)
  );
  NOR _106_ (
    .A(_001_),
    .B(data_11[3]),
    .Y(_049_)
  );
  NOR _107_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _108_ (
    .A(_026_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _109_ (
    .A(reset_L),
    .B(data_000[3]),
    .Y(_052_)
  );
  NOT _110_ (
    .A(_052_),
    .Y(_053_)
  );
  NOR _111_ (
    .A(_025_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _112_ (
    .A(_051_),
    .B(_054_),
    .Y(_000_[3])
  );
  NOR _113_ (
    .A(selector_4f),
    .B(data_00[4]),
    .Y(_055_)
  );
  NOR _114_ (
    .A(_001_),
    .B(data_11[4]),
    .Y(_056_)
  );
  NOR _115_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _116_ (
    .A(_026_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _117_ (
    .A(reset_L),
    .B(data_000[4]),
    .Y(_059_)
  );
  NOT _118_ (
    .A(_059_),
    .Y(_060_)
  );
  NOR _119_ (
    .A(_025_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _120_ (
    .A(_058_),
    .B(_061_),
    .Y(_000_[4])
  );
  NOR _121_ (
    .A(selector_4f),
    .B(data_00[5]),
    .Y(_062_)
  );
  NOR _122_ (
    .A(_001_),
    .B(data_11[5]),
    .Y(_063_)
  );
  NOR _123_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _124_ (
    .A(_026_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _125_ (
    .A(reset_L),
    .B(data_000[5]),
    .Y(_066_)
  );
  NOT _126_ (
    .A(_066_),
    .Y(_067_)
  );
  NOR _127_ (
    .A(_025_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _128_ (
    .A(_065_),
    .B(_068_),
    .Y(_000_[5])
  );
  NOR _129_ (
    .A(selector_4f),
    .B(data_00[6]),
    .Y(_069_)
  );
  NOR _130_ (
    .A(_001_),
    .B(data_11[6]),
    .Y(_003_)
  );
  NOR _131_ (
    .A(_069_),
    .B(_003_),
    .Y(_004_)
  );
  NOR _132_ (
    .A(_026_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _133_ (
    .A(reset_L),
    .B(data_000[6]),
    .Y(_006_)
  );
  NOT _134_ (
    .A(_006_),
    .Y(_007_)
  );
  NOR _135_ (
    .A(_025_),
    .B(_007_),
    .Y(_008_)
  );
  NOR _136_ (
    .A(_005_),
    .B(_008_),
    .Y(_000_[6])
  );
  NOR _137_ (
    .A(selector_4f),
    .B(data_00[7]),
    .Y(_009_)
  );
  NOR _138_ (
    .A(_001_),
    .B(data_11[7]),
    .Y(_010_)
  );
  NOR _139_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _140_ (
    .A(_026_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _141_ (
    .A(reset_L),
    .B(data_000[7]),
    .Y(_013_)
  );
  NOT _142_ (
    .A(_013_),
    .Y(_014_)
  );
  NOR _143_ (
    .A(_025_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _144_ (
    .A(_012_),
    .B(_015_),
    .Y(_000_[7])
  );
  NAND _145_ (
    .A(valid_000),
    .B(_017_),
    .Y(_016_)
  );
  NAND _146_ (
    .A(_026_),
    .B(_016_),
    .Y(_002_)
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _147_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_000[0])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _148_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_000[1])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _149_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_000[2])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _150_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_000[3])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _151_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_000[4])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _152_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_000[5])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _153_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_000[6])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _154_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_000[7])
  );
  (* src = "logica_muxes/MUX_L2.v:38" *)
  DFF _155_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_000)
  );
  (* src = "logica_muxes/MUX_L2.v:19" *)
  DFF _156_ (
    .C(clk_4f),
    .D(_001_),
    .Q(selector_4f)
  );
endmodule

(* src = "Serial_paralelo/Serial_paralelo_tx.v:1" *)
module serial_paralelo_synth(clk_4f, clk_32f, data_in, reset, idle);
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:16" *)
  wire [2:0] _000_;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  wire [2:0] _001_;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  wire [7:0] _002_;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:16" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:10" *)
  wire [2:0] BC_counter;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:4" *)
  input clk_32f;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:3" *)
  input clk_4f;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:10" *)
  wire [2:0] cont;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:12" *)
  wire [7:0] data2out;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:5" *)
  input data_in;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:7" *)
  output idle;
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:6" *)
  input reset;
  NOT _082_ (
    .A(data2out[6]),
    .Y(_023_)
  );
  NOT _083_ (
    .A(data2out[7]),
    .Y(_024_)
  );
  NOT _084_ (
    .A(BC_counter[0]),
    .Y(_025_)
  );
  NOT _085_ (
    .A(BC_counter[1]),
    .Y(_026_)
  );
  NOT _086_ (
    .A(reset),
    .Y(_027_)
  );
  NOT _087_ (
    .A(data_in),
    .Y(_028_)
  );
  NOT _088_ (
    .A(data2out[3]),
    .Y(_029_)
  );
  NOT _089_ (
    .A(cont[0]),
    .Y(_030_)
  );
  NOT _090_ (
    .A(cont[1]),
    .Y(_031_)
  );
  NOT _091_ (
    .A(cont[2]),
    .Y(_032_)
  );
  NOR _092_ (
    .A(data2out[0]),
    .B(data2out[1]),
    .Y(_033_)
  );
  NAND _093_ (
    .A(data2out[3]),
    .B(data2out[2]),
    .Y(_034_)
  );
  NOT _094_ (
    .A(_034_),
    .Y(_035_)
  );
  NAND _095_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  NOT _096_ (
    .A(_036_),
    .Y(_037_)
  );
  NOR _097_ (
    .A(BC_counter[0]),
    .B(BC_counter[1]),
    .Y(_038_)
  );
  NAND _098_ (
    .A(BC_counter[2]),
    .B(_038_),
    .Y(_039_)
  );
  NAND _099_ (
    .A(data2out[5]),
    .B(data2out[4]),
    .Y(_040_)
  );
  NOT _100_ (
    .A(_040_),
    .Y(_041_)
  );
  NOR _101_ (
    .A(data2out[7]),
    .B(_040_),
    .Y(_042_)
  );
  NAND _102_ (
    .A(data2out[6]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _103_ (
    .A(_039_),
    .B(_043_),
    .Y(_044_)
  );
  NOT _104_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _105_ (
    .A(_036_),
    .B(_045_),
    .Y(_003_)
  );
  NOR _106_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_046_)
  );
  NAND _107_ (
    .A(_032_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _108_ (
    .A(_024_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _109_ (
    .A(data_in),
    .B(_047_),
    .Y(_049_)
  );
  NAND _110_ (
    .A(reset),
    .B(_048_),
    .Y(_050_)
  );
  NOR _111_ (
    .A(_049_),
    .B(_050_),
    .Y(_002_[7])
  );
  NAND _112_ (
    .A(cont[0]),
    .B(_031_),
    .Y(_051_)
  );
  NOR _113_ (
    .A(cont[2]),
    .B(_051_),
    .Y(_052_)
  );
  NOR _114_ (
    .A(data2out[6]),
    .B(_052_),
    .Y(_053_)
  );
  NAND _115_ (
    .A(_028_),
    .B(_052_),
    .Y(_054_)
  );
  NAND _116_ (
    .A(reset),
    .B(_054_),
    .Y(_055_)
  );
  NOR _117_ (
    .A(_053_),
    .B(_055_),
    .Y(_002_[6])
  );
  NAND _118_ (
    .A(_030_),
    .B(cont[1]),
    .Y(_056_)
  );
  NOR _119_ (
    .A(cont[2]),
    .B(_056_),
    .Y(_057_)
  );
  NOR _120_ (
    .A(data2out[5]),
    .B(_057_),
    .Y(_058_)
  );
  NAND _121_ (
    .A(_028_),
    .B(_057_),
    .Y(_059_)
  );
  NAND _122_ (
    .A(reset),
    .B(_059_),
    .Y(_060_)
  );
  NOR _123_ (
    .A(_058_),
    .B(_060_),
    .Y(_002_[5])
  );
  NAND _124_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_061_)
  );
  NOR _125_ (
    .A(cont[2]),
    .B(_061_),
    .Y(_062_)
  );
  NOR _126_ (
    .A(data2out[4]),
    .B(_062_),
    .Y(_063_)
  );
  NAND _127_ (
    .A(_028_),
    .B(_062_),
    .Y(_064_)
  );
  NAND _128_ (
    .A(reset),
    .B(_064_),
    .Y(_065_)
  );
  NOR _129_ (
    .A(_063_),
    .B(_065_),
    .Y(_002_[4])
  );
  NAND _130_ (
    .A(cont[2]),
    .B(_046_),
    .Y(_066_)
  );
  NAND _131_ (
    .A(_029_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _132_ (
    .A(data_in),
    .B(_066_),
    .Y(_068_)
  );
  NAND _133_ (
    .A(reset),
    .B(_067_),
    .Y(_069_)
  );
  NOR _134_ (
    .A(_068_),
    .B(_069_),
    .Y(_002_[3])
  );
  NOR _135_ (
    .A(_032_),
    .B(_051_),
    .Y(_070_)
  );
  NOR _136_ (
    .A(data2out[2]),
    .B(_070_),
    .Y(_071_)
  );
  NAND _137_ (
    .A(_028_),
    .B(_070_),
    .Y(_072_)
  );
  NAND _138_ (
    .A(reset),
    .B(_072_),
    .Y(_073_)
  );
  NOR _139_ (
    .A(_071_),
    .B(_073_),
    .Y(_002_[2])
  );
  NOR _140_ (
    .A(_032_),
    .B(_056_),
    .Y(_074_)
  );
  NOR _141_ (
    .A(data2out[1]),
    .B(_074_),
    .Y(_075_)
  );
  NAND _142_ (
    .A(_028_),
    .B(_074_),
    .Y(_076_)
  );
  NAND _143_ (
    .A(reset),
    .B(_076_),
    .Y(_077_)
  );
  NOR _144_ (
    .A(_075_),
    .B(_077_),
    .Y(_002_[1])
  );
  NOR _145_ (
    .A(_032_),
    .B(_061_),
    .Y(_078_)
  );
  NOR _146_ (
    .A(data2out[0]),
    .B(_078_),
    .Y(_079_)
  );
  NAND _147_ (
    .A(_028_),
    .B(_078_),
    .Y(_080_)
  );
  NAND _148_ (
    .A(reset),
    .B(_080_),
    .Y(_081_)
  );
  NOR _149_ (
    .A(_079_),
    .B(_081_),
    .Y(_002_[0])
  );
  NOR _150_ (
    .A(_027_),
    .B(cont[0]),
    .Y(_001_[0])
  );
  NAND _151_ (
    .A(reset),
    .B(_061_),
    .Y(_004_)
  );
  NOR _152_ (
    .A(_046_),
    .B(_004_),
    .Y(_001_[1])
  );
  NAND _153_ (
    .A(_032_),
    .B(_061_),
    .Y(_005_)
  );
  NAND _154_ (
    .A(reset),
    .B(_005_),
    .Y(_006_)
  );
  NOR _155_ (
    .A(_078_),
    .B(_006_),
    .Y(_001_[2])
  );
  NOR _156_ (
    .A(data2out[6]),
    .B(_024_),
    .Y(_007_)
  );
  NAND _157_ (
    .A(_023_),
    .B(data2out[7]),
    .Y(_008_)
  );
  NOR _158_ (
    .A(_040_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _159_ (
    .A(_041_),
    .B(_007_),
    .Y(_010_)
  );
  NOR _160_ (
    .A(_036_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _161_ (
    .A(_037_),
    .B(_009_),
    .Y(_012_)
  );
  NOR _162_ (
    .A(BC_counter[0]),
    .B(_027_),
    .Y(_013_)
  );
  NAND _163_ (
    .A(_039_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _164_ (
    .A(_012_),
    .B(_014_),
    .Y(_000_[0])
  );
  NOR _165_ (
    .A(_025_),
    .B(_026_),
    .Y(_015_)
  );
  NOR _166_ (
    .A(_038_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _167_ (
    .A(reset),
    .B(_016_),
    .Y(_017_)
  );
  NOR _168_ (
    .A(_012_),
    .B(_017_),
    .Y(_000_[1])
  );
  NOR _169_ (
    .A(_038_),
    .B(_011_),
    .Y(_018_)
  );
  NAND _170_ (
    .A(BC_counter[2]),
    .B(_015_),
    .Y(_019_)
  );
  NOR _171_ (
    .A(BC_counter[2]),
    .B(_015_),
    .Y(_020_)
  );
  NOR _172_ (
    .A(_027_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _173_ (
    .A(_019_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _174_ (
    .A(_018_),
    .B(_022_),
    .Y(_000_[2])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _175_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(data2out[0])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _176_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(data2out[1])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _177_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(data2out[2])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _178_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(data2out[3])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _179_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(data2out[4])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _180_ (
    .C(clk_32f),
    .D(_002_[5]),
    .Q(data2out[5])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _181_ (
    .C(clk_32f),
    .D(_002_[6]),
    .Q(data2out[6])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _182_ (
    .C(clk_32f),
    .D(_002_[7]),
    .Q(data2out[7])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _183_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(cont[0])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _184_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(cont[1])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:34" *)
  DFF _185_ (
    .C(clk_32f),
    .D(_001_[2]),
    .Q(cont[2])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:16" *)
  DFF _186_ (
    .C(clk_4f),
    .D(_003_),
    .Q(idle)
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:16" *)
  DFF _187_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:16" *)
  DFF _188_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "Serial_paralelo/Serial_paralelo_tx.v:16" *)
  DFF _189_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
endmodule

(* src = "paralelo_serial/paralelo_serial.v:1" *)
module paralelo_serial_synth(data_out, reset_L, clk_32f, data_in, valid_in);
  (* src = "paralelo_serial/paralelo_serial.v:15" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* src = "paralelo_serial/paralelo_serial.v:4" *)
  input clk_32f;
  (* src = "paralelo_serial/paralelo_serial.v:5" *)
  input [7:0] data_in;
  (* src = "paralelo_serial/paralelo_serial.v:2" *)
  output data_out;
  (* init = 3'h0 *)
  (* src = "paralelo_serial/paralelo_serial.v:8" *)
  wire [2:0] index;
  (* src = "paralelo_serial/paralelo_serial.v:3" *)
  input reset_L;
  (* src = "paralelo_serial/paralelo_serial.v:6" *)
  input valid_in;
  NOT _42_ (
    .A(valid_in),
    .Y(_01_)
  );
  NOT _43_ (
    .A(data_in[5]),
    .Y(_02_)
  );
  NOT _44_ (
    .A(reset_L),
    .Y(_03_)
  );
  NOT _45_ (
    .A(index[1]),
    .Y(_04_)
  );
  NOT _46_ (
    .A(index[2]),
    .Y(_05_)
  );
  NOR _47_ (
    .A(_03_),
    .B(index[0]),
    .Y(_00_[0])
  );
  NAND _48_ (
    .A(index[0]),
    .B(index[1]),
    .Y(_06_)
  );
  NOT _49_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _50_ (
    .A(index[0]),
    .B(index[1]),
    .Y(_08_)
  );
  NOT _51_ (
    .A(_08_),
    .Y(_09_)
  );
  NAND _52_ (
    .A(reset_L),
    .B(_09_),
    .Y(_10_)
  );
  NOR _53_ (
    .A(_07_),
    .B(_10_),
    .Y(_00_[1])
  );
  NOR _54_ (
    .A(_05_),
    .B(_06_),
    .Y(_11_)
  );
  NAND _55_ (
    .A(_05_),
    .B(_06_),
    .Y(_12_)
  );
  NAND _56_ (
    .A(reset_L),
    .B(_12_),
    .Y(_13_)
  );
  NOR _57_ (
    .A(_11_),
    .B(_13_),
    .Y(_00_[2])
  );
  NOR _58_ (
    .A(_01_),
    .B(index[2]),
    .Y(_14_)
  );
  NOR _59_ (
    .A(data_in[4]),
    .B(_06_),
    .Y(_15_)
  );
  NAND _60_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  NAND _61_ (
    .A(reset_L),
    .B(_16_),
    .Y(_17_)
  );
  NOT _62_ (
    .A(_17_),
    .Y(_18_)
  );
  NAND _63_ (
    .A(valid_in),
    .B(_08_),
    .Y(_19_)
  );
  NAND _64_ (
    .A(data_in[7]),
    .B(_05_),
    .Y(_20_)
  );
  NAND _65_ (
    .A(data_in[3]),
    .B(index[2]),
    .Y(_21_)
  );
  NAND _66_ (
    .A(_20_),
    .B(_21_),
    .Y(_22_)
  );
  NOR _67_ (
    .A(_19_),
    .B(_22_),
    .Y(_23_)
  );
  NAND _68_ (
    .A(data_in[0]),
    .B(valid_in),
    .Y(_24_)
  );
  NAND _69_ (
    .A(_11_),
    .B(_24_),
    .Y(_25_)
  );
  NOT _70_ (
    .A(_25_),
    .Y(_26_)
  );
  NOR _71_ (
    .A(_23_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _72_ (
    .A(_18_),
    .B(_27_),
    .Y(_28_)
  );
  NAND _73_ (
    .A(data_in[6]),
    .B(_14_),
    .Y(_29_)
  );
  NAND _74_ (
    .A(index[0]),
    .B(_04_),
    .Y(_30_)
  );
  NOR _75_ (
    .A(_01_),
    .B(data_in[2]),
    .Y(_31_)
  );
  NOR _76_ (
    .A(_05_),
    .B(_31_),
    .Y(_32_)
  );
  NOR _77_ (
    .A(_30_),
    .B(_32_),
    .Y(_33_)
  );
  NAND _78_ (
    .A(_29_),
    .B(_33_),
    .Y(_34_)
  );
  NAND _79_ (
    .A(_02_),
    .B(_14_),
    .Y(_35_)
  );
  NAND _80_ (
    .A(valid_in),
    .B(data_in[1]),
    .Y(_36_)
  );
  NAND _81_ (
    .A(index[2]),
    .B(_36_),
    .Y(_37_)
  );
  NAND _82_ (
    .A(_35_),
    .B(_37_),
    .Y(_38_)
  );
  NOR _83_ (
    .A(index[0]),
    .B(_04_),
    .Y(_39_)
  );
  NAND _84_ (
    .A(_38_),
    .B(_39_),
    .Y(_40_)
  );
  NAND _85_ (
    .A(_34_),
    .B(_40_),
    .Y(_41_)
  );
  NOR _86_ (
    .A(_28_),
    .B(_41_),
    .Y(data_out)
  );
  (* src = "paralelo_serial/paralelo_serial.v:15" *)
  DFF _87_ (
    .C(clk_32f),
    .D(_00_[0]),
    .Q(index[0])
  );
  (* src = "paralelo_serial/paralelo_serial.v:15" *)
  DFF _88_ (
    .C(clk_32f),
    .D(_00_[1]),
    .Q(index[1])
  );
  (* src = "paralelo_serial/paralelo_serial.v:15" *)
  DFF _89_ (
    .C(clk_32f),
    .D(_00_[2]),
    .Q(index[2])
  );
endmodule

(* top =  1  *)
(* src = "phy_tx.v:6" *)
module phy_tx_synth(data_out, recirc_4, recirc_5, recirc_6, recirc_7, valid_r_4, valid_r_5, valid_r_6, valid_r_7, clk_f, clk_2f, clk_4f, clk_32f, reset_L, data_in_0, data_in_1, data_in_2, data_in_3, valid_in_0, valid_in_1, valid_in_2, valid_in_3, data_in);
  (* src = "phy_tx.v:19" *)
  input clk_2f;
  (* src = "phy_tx.v:21" *)
  input clk_32f;
  (* src = "phy_tx.v:20" *)
  input clk_4f;
  (* src = "phy_tx.v:18" *)
  input clk_f;
  (* src = "phy_tx.v:42" *)
  wire [7:0] data_000;
  (* src = "phy_tx.v:34" *)
  input data_in;
  (* src = "phy_tx.v:25" *)
  input [7:0] data_in_0;
  (* src = "phy_tx.v:26" *)
  input [7:0] data_in_1;
  (* src = "phy_tx.v:27" *)
  input [7:0] data_in_2;
  (* src = "phy_tx.v:28" *)
  input [7:0] data_in_3;
  (* src = "phy_tx.v:7" *)
  output data_out;
  (* src = "phy_tx.v:43" *)
  wire idle;
  (* src = "phy_tx.v:44" *)
  wire [7:0] recirc_0;
  (* src = "phy_tx.v:45" *)
  wire [7:0] recirc_1;
  (* src = "phy_tx.v:46" *)
  wire [7:0] recirc_2;
  (* src = "phy_tx.v:47" *)
  wire [7:0] recirc_3;
  (* src = "phy_tx.v:9" *)
  output [7:0] recirc_4;
  (* src = "phy_tx.v:10" *)
  output [7:0] recirc_5;
  (* src = "phy_tx.v:11" *)
  output [7:0] recirc_6;
  (* src = "phy_tx.v:12" *)
  output [7:0] recirc_7;
  (* src = "phy_tx.v:23" *)
  input reset_L;
  (* src = "phy_tx.v:48" *)
  wire valid_000;
  (* src = "phy_tx.v:29" *)
  input valid_in_0;
  (* src = "phy_tx.v:30" *)
  input valid_in_1;
  (* src = "phy_tx.v:31" *)
  input valid_in_2;
  (* src = "phy_tx.v:32" *)
  input valid_in_3;
  (* src = "phy_tx.v:49" *)
  wire valid_r_0;
  (* src = "phy_tx.v:50" *)
  wire valid_r_1;
  (* src = "phy_tx.v:51" *)
  wire valid_r_2;
  (* src = "phy_tx.v:52" *)
  wire valid_r_3;
  (* src = "phy_tx.v:13" *)
  output valid_r_4;
  (* src = "phy_tx.v:14" *)
  output valid_r_5;
  (* src = "phy_tx.v:15" *)
  output valid_r_6;
  (* src = "phy_tx.v:16" *)
  output valid_r_7;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:97" *)
  MUXES muxes_tx (
    .clk_2f(clk_2f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .data_0(recirc_0),
    .data_000(data_000),
    .data_1(recirc_1),
    .data_2(recirc_2),
    .data_3(recirc_3),
    .reset_L(reset_L),
    .valid_0(valid_r_0),
    .valid_000(valid_000),
    .valid_1(valid_r_1),
    .valid_2(valid_r_2),
    .valid_3(valid_r_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:120" *)
  paralelo_serial paralelo_serial_tx (
    .clk_32f(clk_32f),
    .data_in(data_000),
    .data_out(data_out),
    .reset_L(reset_L),
    .valid_in(valid_000)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:61" *)
  recirculador recirculador_tx (
    .clk(clk_f),
    .data_in_0(data_in_0),
    .data_in_1(data_in_1),
    .data_in_2(data_in_2),
    .data_in_3(data_in_3),
    .data_out_0(recirc_0),
    .data_out_1(recirc_1),
    .data_out_2(recirc_2),
    .data_out_3(recirc_3),
    .data_out_4(recirc_4),
    .data_out_5(recirc_5),
    .data_out_6(recirc_6),
    .data_out_7(recirc_7),
    .idle(idle),
    .valid_in_0(valid_in_0),
    .valid_in_1(valid_in_1),
    .valid_in_2(valid_in_2),
    .valid_in_3(valid_in_3),
    .valid_out_0(valid_r_0),
    .valid_out_1(valid_r_1),
    .valid_out_2(valid_r_2),
    .valid_out_3(valid_r_3),
    .valid_out_4(valid_r_4),
    .valid_out_5(valid_r_5),
    .valid_out_6(valid_r_6),
    .valid_out_7(valid_r_7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:133" *)
  Serial_paralelo_tx serial_paralelo_tx (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(data_in),
    .idle(idle),
    .reset(reset_L)
  );
endmodule

(* src = "recirculador/recirculador.v:1" *)
module recirculador_synth(idle, clk, data_in_0, data_in_1, data_in_2, data_in_3, valid_in_0, valid_in_1, valid_in_2, valid_in_3, data_out_0, data_out_1, data_out_2, data_out_3, data_out_4, data_out_5, data_out_6, data_out_7, valid_out_0, valid_out_1, valid_out_2, valid_out_3, valid_out_4, valid_out_5, valid_out_6, valid_out_7);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  (* src = "recirculador/recirculador.v:3" *)
  input clk;
  (* src = "recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_0;
  (* src = "recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_1;
  (* src = "recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_2;
  (* src = "recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_3;
  (* src = "recirculador/recirculador.v:5" *)
  input [7:0] data_in_0;
  (* src = "recirculador/recirculador.v:6" *)
  input [7:0] data_in_1;
  (* src = "recirculador/recirculador.v:7" *)
  input [7:0] data_in_2;
  (* src = "recirculador/recirculador.v:8" *)
  input [7:0] data_in_3;
  (* src = "recirculador/recirculador.v:15" *)
  output [7:0] data_out_0;
  (* src = "recirculador/recirculador.v:16" *)
  output [7:0] data_out_1;
  (* src = "recirculador/recirculador.v:17" *)
  output [7:0] data_out_2;
  (* src = "recirculador/recirculador.v:18" *)
  output [7:0] data_out_3;
  (* src = "recirculador/recirculador.v:20" *)
  output [7:0] data_out_4;
  (* src = "recirculador/recirculador.v:21" *)
  output [7:0] data_out_5;
  (* src = "recirculador/recirculador.v:22" *)
  output [7:0] data_out_6;
  (* src = "recirculador/recirculador.v:23" *)
  output [7:0] data_out_7;
  (* src = "recirculador/recirculador.v:2" *)
  input idle;
  (* src = "recirculador/recirculador.v:39" *)
  wire valid_ff_0;
  (* src = "recirculador/recirculador.v:39" *)
  wire valid_ff_1;
  (* src = "recirculador/recirculador.v:39" *)
  wire valid_ff_2;
  (* src = "recirculador/recirculador.v:39" *)
  wire valid_ff_3;
  (* src = "recirculador/recirculador.v:10" *)
  input valid_in_0;
  (* src = "recirculador/recirculador.v:11" *)
  input valid_in_1;
  (* src = "recirculador/recirculador.v:12" *)
  input valid_in_2;
  (* src = "recirculador/recirculador.v:13" *)
  input valid_in_3;
  (* src = "recirculador/recirculador.v:25" *)
  output valid_out_0;
  (* src = "recirculador/recirculador.v:26" *)
  output valid_out_1;
  (* src = "recirculador/recirculador.v:27" *)
  output valid_out_2;
  (* src = "recirculador/recirculador.v:28" *)
  output valid_out_3;
  (* src = "recirculador/recirculador.v:29" *)
  output valid_out_4;
  (* src = "recirculador/recirculador.v:30" *)
  output valid_out_5;
  (* src = "recirculador/recirculador.v:31" *)
  output valid_out_6;
  (* src = "recirculador/recirculador.v:32" *)
  output valid_out_7;
  NOT _064_ (
    .A(data_ff_3[1]),
    .Y(_062_)
  );
  NOT _065_ (
    .A(data_ff_3[2]),
    .Y(_063_)
  );
  NOT _066_ (
    .A(data_ff_3[3]),
    .Y(_000_)
  );
  NOT _067_ (
    .A(data_ff_3[4]),
    .Y(_001_)
  );
  NOT _068_ (
    .A(data_ff_3[5]),
    .Y(_002_)
  );
  NOT _069_ (
    .A(data_ff_3[6]),
    .Y(_003_)
  );
  NOT _070_ (
    .A(data_ff_3[7]),
    .Y(_004_)
  );
  NOT _071_ (
    .A(data_ff_0[0]),
    .Y(_005_)
  );
  NOT _072_ (
    .A(data_ff_0[1]),
    .Y(_006_)
  );
  NOT _073_ (
    .A(data_ff_0[2]),
    .Y(_007_)
  );
  NOT _074_ (
    .A(data_ff_0[3]),
    .Y(_008_)
  );
  NOT _075_ (
    .A(data_ff_0[4]),
    .Y(_009_)
  );
  NOT _076_ (
    .A(data_ff_0[5]),
    .Y(_010_)
  );
  NOT _077_ (
    .A(data_ff_0[6]),
    .Y(_011_)
  );
  NOT _078_ (
    .A(data_ff_0[7]),
    .Y(_012_)
  );
  NOT _079_ (
    .A(data_ff_2[0]),
    .Y(_013_)
  );
  NOT _080_ (
    .A(data_ff_2[1]),
    .Y(_014_)
  );
  NOT _081_ (
    .A(data_ff_2[2]),
    .Y(_015_)
  );
  NOT _082_ (
    .A(data_ff_2[3]),
    .Y(_016_)
  );
  NOT _083_ (
    .A(data_ff_2[4]),
    .Y(_017_)
  );
  NOT _084_ (
    .A(data_ff_2[5]),
    .Y(_018_)
  );
  NOT _085_ (
    .A(data_ff_2[6]),
    .Y(_019_)
  );
  NOT _086_ (
    .A(data_ff_2[7]),
    .Y(_020_)
  );
  NOT _087_ (
    .A(data_ff_1[0]),
    .Y(_021_)
  );
  NOT _088_ (
    .A(data_ff_1[1]),
    .Y(_022_)
  );
  NOT _089_ (
    .A(data_ff_1[2]),
    .Y(_023_)
  );
  NOT _090_ (
    .A(data_ff_1[3]),
    .Y(_024_)
  );
  NOT _091_ (
    .A(data_ff_1[4]),
    .Y(_025_)
  );
  NOT _092_ (
    .A(data_ff_1[5]),
    .Y(_026_)
  );
  NOT _093_ (
    .A(data_ff_1[6]),
    .Y(_027_)
  );
  NOT _094_ (
    .A(data_ff_1[7]),
    .Y(_028_)
  );
  NOT _095_ (
    .A(data_ff_3[0]),
    .Y(_029_)
  );
  NOR _096_ (
    .A(_062_),
    .B(idle),
    .Y(data_out_7[1])
  );
  NOR _097_ (
    .A(idle),
    .B(_063_),
    .Y(data_out_7[2])
  );
  NOR _098_ (
    .A(idle),
    .B(_000_),
    .Y(data_out_7[3])
  );
  NOR _099_ (
    .A(idle),
    .B(_001_),
    .Y(data_out_7[4])
  );
  NOR _100_ (
    .A(idle),
    .B(_002_),
    .Y(data_out_7[5])
  );
  NOR _101_ (
    .A(idle),
    .B(_003_),
    .Y(data_out_7[6])
  );
  NOR _102_ (
    .A(idle),
    .B(_004_),
    .Y(data_out_7[7])
  );
  NOR _103_ (
    .A(idle),
    .B(_005_),
    .Y(data_out_4[0])
  );
  NOR _104_ (
    .A(idle),
    .B(_006_),
    .Y(data_out_4[1])
  );
  NOR _105_ (
    .A(idle),
    .B(_007_),
    .Y(data_out_4[2])
  );
  NOR _106_ (
    .A(idle),
    .B(_008_),
    .Y(data_out_4[3])
  );
  NOR _107_ (
    .A(idle),
    .B(_009_),
    .Y(data_out_4[4])
  );
  NOR _108_ (
    .A(idle),
    .B(_010_),
    .Y(data_out_4[5])
  );
  NOR _109_ (
    .A(idle),
    .B(_011_),
    .Y(data_out_4[6])
  );
  NOR _110_ (
    .A(idle),
    .B(_012_),
    .Y(data_out_4[7])
  );
  NOR _111_ (
    .A(idle),
    .B(_013_),
    .Y(data_out_6[0])
  );
  NOR _112_ (
    .A(idle),
    .B(_014_),
    .Y(data_out_6[1])
  );
  NOR _113_ (
    .A(idle),
    .B(_015_),
    .Y(data_out_6[2])
  );
  NOR _114_ (
    .A(idle),
    .B(_016_),
    .Y(data_out_6[3])
  );
  NOR _115_ (
    .A(idle),
    .B(_017_),
    .Y(data_out_6[4])
  );
  NOR _116_ (
    .A(idle),
    .B(_018_),
    .Y(data_out_6[5])
  );
  NOR _117_ (
    .A(idle),
    .B(_019_),
    .Y(data_out_6[6])
  );
  NOR _118_ (
    .A(idle),
    .B(_020_),
    .Y(data_out_6[7])
  );
  NOR _119_ (
    .A(idle),
    .B(_021_),
    .Y(data_out_5[0])
  );
  NOR _120_ (
    .A(idle),
    .B(_022_),
    .Y(data_out_5[1])
  );
  NOR _121_ (
    .A(idle),
    .B(_023_),
    .Y(data_out_5[2])
  );
  NOR _122_ (
    .A(idle),
    .B(_024_),
    .Y(data_out_5[3])
  );
  NOR _123_ (
    .A(idle),
    .B(_025_),
    .Y(data_out_5[4])
  );
  NOR _124_ (
    .A(idle),
    .B(_026_),
    .Y(data_out_5[5])
  );
  NOR _125_ (
    .A(idle),
    .B(_027_),
    .Y(data_out_5[6])
  );
  NOR _126_ (
    .A(idle),
    .B(_028_),
    .Y(data_out_5[7])
  );
  NAND _127_ (
    .A(idle),
    .B(data_ff_1[0]),
    .Y(_030_)
  );
  NOT _128_ (
    .A(_030_),
    .Y(data_out_1[0])
  );
  NAND _129_ (
    .A(idle),
    .B(data_ff_1[1]),
    .Y(_031_)
  );
  NOT _130_ (
    .A(_031_),
    .Y(data_out_1[1])
  );
  NAND _131_ (
    .A(idle),
    .B(data_ff_1[2]),
    .Y(_032_)
  );
  NOT _132_ (
    .A(_032_),
    .Y(data_out_1[2])
  );
  NAND _133_ (
    .A(idle),
    .B(data_ff_1[3]),
    .Y(_033_)
  );
  NOT _134_ (
    .A(_033_),
    .Y(data_out_1[3])
  );
  NAND _135_ (
    .A(idle),
    .B(data_ff_1[4]),
    .Y(_034_)
  );
  NOT _136_ (
    .A(_034_),
    .Y(data_out_1[4])
  );
  NAND _137_ (
    .A(idle),
    .B(data_ff_1[5]),
    .Y(_035_)
  );
  NOT _138_ (
    .A(_035_),
    .Y(data_out_1[5])
  );
  NAND _139_ (
    .A(idle),
    .B(data_ff_1[6]),
    .Y(_036_)
  );
  NOT _140_ (
    .A(_036_),
    .Y(data_out_1[6])
  );
  NAND _141_ (
    .A(idle),
    .B(data_ff_1[7]),
    .Y(_037_)
  );
  NOT _142_ (
    .A(_037_),
    .Y(data_out_1[7])
  );
  NAND _143_ (
    .A(idle),
    .B(data_ff_3[0]),
    .Y(_038_)
  );
  NOT _144_ (
    .A(_038_),
    .Y(data_out_3[0])
  );
  NAND _145_ (
    .A(data_ff_3[1]),
    .B(idle),
    .Y(_039_)
  );
  NOT _146_ (
    .A(_039_),
    .Y(data_out_3[1])
  );
  NAND _147_ (
    .A(idle),
    .B(data_ff_3[2]),
    .Y(_040_)
  );
  NOT _148_ (
    .A(_040_),
    .Y(data_out_3[2])
  );
  NAND _149_ (
    .A(idle),
    .B(data_ff_3[3]),
    .Y(_041_)
  );
  NOT _150_ (
    .A(_041_),
    .Y(data_out_3[3])
  );
  NAND _151_ (
    .A(idle),
    .B(data_ff_3[4]),
    .Y(_042_)
  );
  NOT _152_ (
    .A(_042_),
    .Y(data_out_3[4])
  );
  NAND _153_ (
    .A(idle),
    .B(data_ff_3[5]),
    .Y(_043_)
  );
  NOT _154_ (
    .A(_043_),
    .Y(data_out_3[5])
  );
  NAND _155_ (
    .A(idle),
    .B(data_ff_3[6]),
    .Y(_044_)
  );
  NOT _156_ (
    .A(_044_),
    .Y(data_out_3[6])
  );
  NAND _157_ (
    .A(idle),
    .B(data_ff_3[7]),
    .Y(_045_)
  );
  NOT _158_ (
    .A(_045_),
    .Y(data_out_3[7])
  );
  NAND _159_ (
    .A(idle),
    .B(data_ff_2[0]),
    .Y(_046_)
  );
  NOT _160_ (
    .A(_046_),
    .Y(data_out_2[0])
  );
  NAND _161_ (
    .A(idle),
    .B(data_ff_2[1]),
    .Y(_047_)
  );
  NOT _162_ (
    .A(_047_),
    .Y(data_out_2[1])
  );
  NAND _163_ (
    .A(idle),
    .B(data_ff_2[2]),
    .Y(_048_)
  );
  NOT _164_ (
    .A(_048_),
    .Y(data_out_2[2])
  );
  NAND _165_ (
    .A(idle),
    .B(data_ff_2[3]),
    .Y(_049_)
  );
  NOT _166_ (
    .A(_049_),
    .Y(data_out_2[3])
  );
  NAND _167_ (
    .A(idle),
    .B(data_ff_2[4]),
    .Y(_050_)
  );
  NOT _168_ (
    .A(_050_),
    .Y(data_out_2[4])
  );
  NAND _169_ (
    .A(idle),
    .B(data_ff_2[5]),
    .Y(_051_)
  );
  NOT _170_ (
    .A(_051_),
    .Y(data_out_2[5])
  );
  NAND _171_ (
    .A(idle),
    .B(data_ff_2[6]),
    .Y(_052_)
  );
  NOT _172_ (
    .A(_052_),
    .Y(data_out_2[6])
  );
  NAND _173_ (
    .A(idle),
    .B(data_ff_2[7]),
    .Y(_053_)
  );
  NOT _174_ (
    .A(_053_),
    .Y(data_out_2[7])
  );
  NAND _175_ (
    .A(idle),
    .B(data_ff_0[0]),
    .Y(_054_)
  );
  NOT _176_ (
    .A(_054_),
    .Y(data_out_0[0])
  );
  NAND _177_ (
    .A(idle),
    .B(data_ff_0[1]),
    .Y(_055_)
  );
  NOT _178_ (
    .A(_055_),
    .Y(data_out_0[1])
  );
  NAND _179_ (
    .A(idle),
    .B(data_ff_0[2]),
    .Y(_056_)
  );
  NOT _180_ (
    .A(_056_),
    .Y(data_out_0[2])
  );
  NAND _181_ (
    .A(idle),
    .B(data_ff_0[3]),
    .Y(_057_)
  );
  NOT _182_ (
    .A(_057_),
    .Y(data_out_0[3])
  );
  NAND _183_ (
    .A(idle),
    .B(data_ff_0[4]),
    .Y(_058_)
  );
  NOT _184_ (
    .A(_058_),
    .Y(data_out_0[4])
  );
  NAND _185_ (
    .A(idle),
    .B(data_ff_0[5]),
    .Y(_059_)
  );
  NOT _186_ (
    .A(_059_),
    .Y(data_out_0[5])
  );
  NAND _187_ (
    .A(idle),
    .B(data_ff_0[6]),
    .Y(_060_)
  );
  NOT _188_ (
    .A(_060_),
    .Y(data_out_0[6])
  );
  NAND _189_ (
    .A(idle),
    .B(data_ff_0[7]),
    .Y(_061_)
  );
  NOT _190_ (
    .A(_061_),
    .Y(data_out_0[7])
  );
  NOR _191_ (
    .A(idle),
    .B(_029_),
    .Y(data_out_7[0])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _192_ (
    .C(clk),
    .D(data_in_0[0]),
    .Q(data_ff_0[0])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _193_ (
    .C(clk),
    .D(data_in_0[1]),
    .Q(data_ff_0[1])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _194_ (
    .C(clk),
    .D(data_in_0[2]),
    .Q(data_ff_0[2])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _195_ (
    .C(clk),
    .D(data_in_0[3]),
    .Q(data_ff_0[3])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _196_ (
    .C(clk),
    .D(data_in_0[4]),
    .Q(data_ff_0[4])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _197_ (
    .C(clk),
    .D(data_in_0[5]),
    .Q(data_ff_0[5])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _198_ (
    .C(clk),
    .D(data_in_0[6]),
    .Q(data_ff_0[6])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _199_ (
    .C(clk),
    .D(data_in_0[7]),
    .Q(data_ff_0[7])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _200_ (
    .C(clk),
    .D(data_in_1[0]),
    .Q(data_ff_1[0])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _201_ (
    .C(clk),
    .D(data_in_1[1]),
    .Q(data_ff_1[1])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _202_ (
    .C(clk),
    .D(data_in_1[2]),
    .Q(data_ff_1[2])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _203_ (
    .C(clk),
    .D(data_in_1[3]),
    .Q(data_ff_1[3])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _204_ (
    .C(clk),
    .D(data_in_1[4]),
    .Q(data_ff_1[4])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _205_ (
    .C(clk),
    .D(data_in_1[5]),
    .Q(data_ff_1[5])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _206_ (
    .C(clk),
    .D(data_in_1[6]),
    .Q(data_ff_1[6])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _207_ (
    .C(clk),
    .D(data_in_1[7]),
    .Q(data_ff_1[7])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _208_ (
    .C(clk),
    .D(data_in_2[0]),
    .Q(data_ff_2[0])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _209_ (
    .C(clk),
    .D(data_in_2[1]),
    .Q(data_ff_2[1])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _210_ (
    .C(clk),
    .D(data_in_2[2]),
    .Q(data_ff_2[2])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _211_ (
    .C(clk),
    .D(data_in_2[3]),
    .Q(data_ff_2[3])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _212_ (
    .C(clk),
    .D(data_in_2[4]),
    .Q(data_ff_2[4])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _213_ (
    .C(clk),
    .D(data_in_2[5]),
    .Q(data_ff_2[5])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _214_ (
    .C(clk),
    .D(data_in_2[6]),
    .Q(data_ff_2[6])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _215_ (
    .C(clk),
    .D(data_in_2[7]),
    .Q(data_ff_2[7])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _216_ (
    .C(clk),
    .D(data_in_3[0]),
    .Q(data_ff_3[0])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _217_ (
    .C(clk),
    .D(data_in_3[1]),
    .Q(data_ff_3[1])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _218_ (
    .C(clk),
    .D(data_in_3[2]),
    .Q(data_ff_3[2])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _219_ (
    .C(clk),
    .D(data_in_3[3]),
    .Q(data_ff_3[3])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _220_ (
    .C(clk),
    .D(data_in_3[4]),
    .Q(data_ff_3[4])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _221_ (
    .C(clk),
    .D(data_in_3[5]),
    .Q(data_ff_3[5])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _222_ (
    .C(clk),
    .D(data_in_3[6]),
    .Q(data_ff_3[6])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _223_ (
    .C(clk),
    .D(data_in_3[7]),
    .Q(data_ff_3[7])
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _224_ (
    .C(clk),
    .D(valid_in_0),
    .Q(valid_ff_0)
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _225_ (
    .C(clk),
    .D(valid_in_1),
    .Q(valid_ff_1)
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _226_ (
    .C(clk),
    .D(valid_in_2),
    .Q(valid_ff_2)
  );
  (* src = "recirculador/recirculador.v:42" *)
  DFF _227_ (
    .C(clk),
    .D(valid_in_3),
    .Q(valid_ff_3)
  );
  assign valid_out_0 = valid_ff_0;
  assign valid_out_1 = valid_ff_1;
  assign valid_out_2 = valid_ff_2;
  assign valid_out_3 = valid_ff_3;
  assign valid_out_4 = 1'h0;
  assign valid_out_5 = 1'h0;
  assign valid_out_6 = 1'h0;
  assign valid_out_7 = 1'h0;
endmodule
