/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "./logica_muxes/MUX1_L1.v:1" *)
module MUX1_L1_synth(data_00, valid_00, clk_2f, data_0, data_1, valid_0, valid_1);
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  wire [7:0] _000_;
  (* src = "./logica_muxes/MUX1_L1.v:18" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "./logica_muxes/MUX1_L1.v:4" *)
  input clk_2f;
  (* src = "./logica_muxes/MUX1_L1.v:5" *)
  input [7:0] data_0;
  (* src = "./logica_muxes/MUX1_L1.v:2" *)
  output [7:0] data_00;
  (* src = "./logica_muxes/MUX1_L1.v:6" *)
  input [7:0] data_1;
  (* init = 1'h0 *)
  (* src = "./logica_muxes/MUX1_L1.v:12" *)
  wire selector_2f;
  (* src = "./logica_muxes/MUX1_L1.v:7" *)
  input valid_0;
  (* src = "./logica_muxes/MUX1_L1.v:3" *)
  output valid_00;
  (* src = "./logica_muxes/MUX1_L1.v:8" *)
  input valid_1;
  (* src = "./logica_muxes/MUX1_L1.v:13" *)
  wire validt_00;
  NOT _047_ (
    .A(selector_2f),
    .Y(_001_)
  );
  NOT _048_ (
    .A(valid_0),
    .Y(_002_)
  );
  NAND _049_ (
    .A(selector_2f),
    .B(valid_1),
    .Y(_003_)
  );
  NOT _050_ (
    .A(_003_),
    .Y(_004_)
  );
  NOR _051_ (
    .A(selector_2f),
    .B(_002_),
    .Y(_005_)
  );
  NOR _052_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  NOT _053_ (
    .A(_006_),
    .Y(validt_00)
  );
  NAND _054_ (
    .A(data_0[6]),
    .B(_001_),
    .Y(_007_)
  );
  NAND _055_ (
    .A(data_1[6]),
    .B(selector_2f),
    .Y(_008_)
  );
  NAND _056_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _057_ (
    .A(validt_00),
    .B(_009_),
    .Y(_010_)
  );
  NAND _058_ (
    .A(data_00[6]),
    .B(_006_),
    .Y(_011_)
  );
  NAND _059_ (
    .A(_010_),
    .B(_011_),
    .Y(_000_[6])
  );
  NAND _060_ (
    .A(_001_),
    .B(data_0[5]),
    .Y(_012_)
  );
  NAND _061_ (
    .A(selector_2f),
    .B(data_1[5]),
    .Y(_013_)
  );
  NAND _062_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _063_ (
    .A(validt_00),
    .B(_014_),
    .Y(_015_)
  );
  NAND _064_ (
    .A(data_00[5]),
    .B(_006_),
    .Y(_016_)
  );
  NAND _065_ (
    .A(_015_),
    .B(_016_),
    .Y(_000_[5])
  );
  NAND _066_ (
    .A(_001_),
    .B(data_0[4]),
    .Y(_017_)
  );
  NAND _067_ (
    .A(selector_2f),
    .B(data_1[4]),
    .Y(_018_)
  );
  NAND _068_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _069_ (
    .A(validt_00),
    .B(_019_),
    .Y(_020_)
  );
  NAND _070_ (
    .A(data_00[4]),
    .B(_006_),
    .Y(_021_)
  );
  NAND _071_ (
    .A(_020_),
    .B(_021_),
    .Y(_000_[4])
  );
  NAND _072_ (
    .A(_001_),
    .B(data_0[3]),
    .Y(_022_)
  );
  NAND _073_ (
    .A(selector_2f),
    .B(data_1[3]),
    .Y(_023_)
  );
  NAND _074_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _075_ (
    .A(validt_00),
    .B(_024_),
    .Y(_025_)
  );
  NAND _076_ (
    .A(data_00[3]),
    .B(_006_),
    .Y(_026_)
  );
  NAND _077_ (
    .A(_025_),
    .B(_026_),
    .Y(_000_[3])
  );
  NAND _078_ (
    .A(_001_),
    .B(data_0[2]),
    .Y(_027_)
  );
  NAND _079_ (
    .A(selector_2f),
    .B(data_1[2]),
    .Y(_028_)
  );
  NAND _080_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _081_ (
    .A(validt_00),
    .B(_029_),
    .Y(_030_)
  );
  NAND _082_ (
    .A(data_00[2]),
    .B(_006_),
    .Y(_031_)
  );
  NAND _083_ (
    .A(_030_),
    .B(_031_),
    .Y(_000_[2])
  );
  NAND _084_ (
    .A(_001_),
    .B(data_0[1]),
    .Y(_032_)
  );
  NAND _085_ (
    .A(selector_2f),
    .B(data_1[1]),
    .Y(_033_)
  );
  NAND _086_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _087_ (
    .A(validt_00),
    .B(_034_),
    .Y(_035_)
  );
  NAND _088_ (
    .A(data_00[1]),
    .B(_006_),
    .Y(_036_)
  );
  NAND _089_ (
    .A(_035_),
    .B(_036_),
    .Y(_000_[1])
  );
  NAND _090_ (
    .A(_001_),
    .B(data_0[0]),
    .Y(_037_)
  );
  NAND _091_ (
    .A(selector_2f),
    .B(data_1[0]),
    .Y(_038_)
  );
  NAND _092_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _093_ (
    .A(validt_00),
    .B(_039_),
    .Y(_040_)
  );
  NAND _094_ (
    .A(data_00[0]),
    .B(_006_),
    .Y(_041_)
  );
  NAND _095_ (
    .A(_040_),
    .B(_041_),
    .Y(_000_[0])
  );
  NAND _096_ (
    .A(_001_),
    .B(data_0[7]),
    .Y(_042_)
  );
  NAND _097_ (
    .A(selector_2f),
    .B(data_1[7]),
    .Y(_043_)
  );
  NAND _098_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _099_ (
    .A(validt_00),
    .B(_044_),
    .Y(_045_)
  );
  NAND _100_ (
    .A(data_00[7]),
    .B(_006_),
    .Y(_046_)
  );
  NAND _101_ (
    .A(_045_),
    .B(_046_),
    .Y(_000_[7])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _102_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_00[0])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _103_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_00[1])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _104_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_00[2])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _105_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_00[3])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _106_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_00[4])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _107_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_00[5])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _108_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_00[6])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _109_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_00[7])
  );
  (* src = "./logica_muxes/MUX1_L1.v:37" *)
  DFF _110_ (
    .C(clk_2f),
    .D(validt_00),
    .Q(valid_00)
  );
  (* src = "./logica_muxes/MUX1_L1.v:18" *)
  DFF _111_ (
    .C(clk_2f),
    .D(_001_),
    .Q(selector_2f)
  );
endmodule

(* src = "./logica_muxes/MUX_L2.v:1" *)
module MUX_L2_synth(data_000, valid_000, clk_4f, data_00, data_11, valid_00, valid_11);
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  wire [7:0] _000_;
  (* src = "./logica_muxes/MUX_L2.v:18" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "./logica_muxes/MUX_L2.v:4" *)
  input clk_4f;
  (* src = "./logica_muxes/MUX_L2.v:5" *)
  input [7:0] data_00;
  (* src = "./logica_muxes/MUX_L2.v:2" *)
  output [7:0] data_000;
  (* src = "./logica_muxes/MUX_L2.v:6" *)
  input [7:0] data_11;
  (* init = 1'h1 *)
  (* src = "./logica_muxes/MUX_L2.v:12" *)
  wire selector_4f;
  (* src = "./logica_muxes/MUX_L2.v:7" *)
  input valid_00;
  (* src = "./logica_muxes/MUX_L2.v:3" *)
  output valid_000;
  (* src = "./logica_muxes/MUX_L2.v:8" *)
  input valid_11;
  (* src = "./logica_muxes/MUX_L2.v:13" *)
  wire validt_000;
  NOT _047_ (
    .A(selector_4f),
    .Y(_001_)
  );
  NOT _048_ (
    .A(valid_00),
    .Y(_002_)
  );
  NAND _049_ (
    .A(selector_4f),
    .B(valid_11),
    .Y(_003_)
  );
  NOT _050_ (
    .A(_003_),
    .Y(_004_)
  );
  NOR _051_ (
    .A(selector_4f),
    .B(_002_),
    .Y(_005_)
  );
  NOR _052_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  NOT _053_ (
    .A(_006_),
    .Y(validt_000)
  );
  NAND _054_ (
    .A(data_00[6]),
    .B(_001_),
    .Y(_007_)
  );
  NAND _055_ (
    .A(data_11[6]),
    .B(selector_4f),
    .Y(_008_)
  );
  NAND _056_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _057_ (
    .A(validt_000),
    .B(_009_),
    .Y(_010_)
  );
  NAND _058_ (
    .A(data_000[6]),
    .B(_006_),
    .Y(_011_)
  );
  NAND _059_ (
    .A(_010_),
    .B(_011_),
    .Y(_000_[6])
  );
  NAND _060_ (
    .A(_001_),
    .B(data_00[5]),
    .Y(_012_)
  );
  NAND _061_ (
    .A(selector_4f),
    .B(data_11[5]),
    .Y(_013_)
  );
  NAND _062_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _063_ (
    .A(validt_000),
    .B(_014_),
    .Y(_015_)
  );
  NAND _064_ (
    .A(data_000[5]),
    .B(_006_),
    .Y(_016_)
  );
  NAND _065_ (
    .A(_015_),
    .B(_016_),
    .Y(_000_[5])
  );
  NAND _066_ (
    .A(_001_),
    .B(data_00[4]),
    .Y(_017_)
  );
  NAND _067_ (
    .A(selector_4f),
    .B(data_11[4]),
    .Y(_018_)
  );
  NAND _068_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _069_ (
    .A(validt_000),
    .B(_019_),
    .Y(_020_)
  );
  NAND _070_ (
    .A(data_000[4]),
    .B(_006_),
    .Y(_021_)
  );
  NAND _071_ (
    .A(_020_),
    .B(_021_),
    .Y(_000_[4])
  );
  NAND _072_ (
    .A(_001_),
    .B(data_00[3]),
    .Y(_022_)
  );
  NAND _073_ (
    .A(selector_4f),
    .B(data_11[3]),
    .Y(_023_)
  );
  NAND _074_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _075_ (
    .A(validt_000),
    .B(_024_),
    .Y(_025_)
  );
  NAND _076_ (
    .A(data_000[3]),
    .B(_006_),
    .Y(_026_)
  );
  NAND _077_ (
    .A(_025_),
    .B(_026_),
    .Y(_000_[3])
  );
  NAND _078_ (
    .A(_001_),
    .B(data_00[2]),
    .Y(_027_)
  );
  NAND _079_ (
    .A(selector_4f),
    .B(data_11[2]),
    .Y(_028_)
  );
  NAND _080_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _081_ (
    .A(validt_000),
    .B(_029_),
    .Y(_030_)
  );
  NAND _082_ (
    .A(data_000[2]),
    .B(_006_),
    .Y(_031_)
  );
  NAND _083_ (
    .A(_030_),
    .B(_031_),
    .Y(_000_[2])
  );
  NAND _084_ (
    .A(_001_),
    .B(data_00[1]),
    .Y(_032_)
  );
  NAND _085_ (
    .A(selector_4f),
    .B(data_11[1]),
    .Y(_033_)
  );
  NAND _086_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _087_ (
    .A(validt_000),
    .B(_034_),
    .Y(_035_)
  );
  NAND _088_ (
    .A(data_000[1]),
    .B(_006_),
    .Y(_036_)
  );
  NAND _089_ (
    .A(_035_),
    .B(_036_),
    .Y(_000_[1])
  );
  NAND _090_ (
    .A(_001_),
    .B(data_00[0]),
    .Y(_037_)
  );
  NAND _091_ (
    .A(selector_4f),
    .B(data_11[0]),
    .Y(_038_)
  );
  NAND _092_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _093_ (
    .A(validt_000),
    .B(_039_),
    .Y(_040_)
  );
  NAND _094_ (
    .A(data_000[0]),
    .B(_006_),
    .Y(_041_)
  );
  NAND _095_ (
    .A(_040_),
    .B(_041_),
    .Y(_000_[0])
  );
  NAND _096_ (
    .A(_001_),
    .B(data_00[7]),
    .Y(_042_)
  );
  NAND _097_ (
    .A(selector_4f),
    .B(data_11[7]),
    .Y(_043_)
  );
  NAND _098_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _099_ (
    .A(validt_000),
    .B(_044_),
    .Y(_045_)
  );
  NAND _100_ (
    .A(data_000[7]),
    .B(_006_),
    .Y(_046_)
  );
  NAND _101_ (
    .A(_045_),
    .B(_046_),
    .Y(_000_[7])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _102_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_000[0])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _103_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_000[1])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _104_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_000[2])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _105_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_000[3])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _106_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_000[4])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _107_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_000[5])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _108_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_000[6])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _109_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_000[7])
  );
  (* src = "./logica_muxes/MUX_L2.v:37" *)
  DFF _110_ (
    .C(clk_4f),
    .D(validt_000),
    .Q(valid_000)
  );
  (* src = "./logica_muxes/MUX_L2.v:18" *)
  DFF _111_ (
    .C(clk_4f),
    .D(_001_),
    .Q(selector_4f)
  );
endmodule

(* top =  1  *)
(* src = "phy_tx.v:5" *)
module synt_phy_tx(data_000, valid_000, recirc_0, recirc_1, recirc_2, recirc_3, valid_r_0, valid_r_1, valid_r_2, valid_r_3, idle, clk_f, clk_2f, clk_4f, data_0, data_1, data_2, data_3, valid_0, valid_1, valid_2, valid_3);
  (* src = "phy_tx.v:18" *)
  input clk_2f;
  (* src = "phy_tx.v:19" *)
  input clk_4f;
  (* src = "phy_tx.v:17" *)
  input clk_f;
  (* src = "phy_tx.v:20" *)
  input [7:0] data_0;
  (* src = "phy_tx.v:6" *)
  output [7:0] data_000;
  (* src = "phy_tx.v:21" *)
  input [7:0] data_1;
  (* src = "phy_tx.v:22" *)
  input [7:0] data_2;
  (* src = "phy_tx.v:23" *)
  input [7:0] data_3;
  (* src = "phy_tx.v:29" *)
  wire [7:0] data__00;
  (* src = "phy_tx.v:29" *)
  wire [7:0] data__11;
  (* src = "phy_tx.v:29" *)
  wire [7:0] data_r_0;
  (* src = "phy_tx.v:29" *)
  wire [7:0] data_r_1;
  (* src = "phy_tx.v:29" *)
  wire [7:0] data_r_2;
  (* src = "phy_tx.v:29" *)
  wire [7:0] data_r_3;
  (* src = "phy_tx.v:16" *)
  input idle;
  (* src = "phy_tx.v:8" *)
  output [7:0] recirc_0;
  (* src = "phy_tx.v:9" *)
  output [7:0] recirc_1;
  (* src = "phy_tx.v:10" *)
  output [7:0] recirc_2;
  (* src = "phy_tx.v:11" *)
  output [7:0] recirc_3;
  (* src = "phy_tx.v:24" *)
  input valid_0;
  (* src = "phy_tx.v:7" *)
  output valid_000;
  (* src = "phy_tx.v:25" *)
  input valid_1;
  (* src = "phy_tx.v:26" *)
  input valid_2;
  (* src = "phy_tx.v:27" *)
  input valid_3;
  (* src = "phy_tx.v:30" *)
  wire valid__00;
  (* src = "phy_tx.v:30" *)
  wire valid__11;
  (* src = "phy_tx.v:30" *)
  wire valid_int_0;
  (* src = "phy_tx.v:30" *)
  wire valid_int_1;
  (* src = "phy_tx.v:30" *)
  wire valid_int_2;
  (* src = "phy_tx.v:30" *)
  wire valid_int_3;
  (* src = "phy_tx.v:12" *)
  output valid_r_0;
  (* src = "phy_tx.v:13" *)
  output valid_r_1;
  (* src = "phy_tx.v:14" *)
  output valid_r_2;
  (* src = "phy_tx.v:15" *)
  output valid_r_3;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:62" *)
  MUX1_L1 MUX1 (
    .clk_2f(clk_2f),
    .data_0(data_r_0),
    .data_00(data__00),
    .data_1(data_r_2),
    .valid_0(valid_int_0),
    .valid_00(valid__00),
    .valid_1(valid_int_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:70" *)
  MUX1_L1 MUX2 (
    .clk_2f(clk_2f),
    .data_0(data_r_1),
    .data_00(data__11),
    .data_1(data_r_3),
    .valid_0(valid_int_2),
    .valid_00(valid__11),
    .valid_1(valid_int_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:78" *)
  MUX_L2 MUX3 (
    .clk_4f(clk_4f),
    .data_00(data__00),
    .data_000(data_000),
    .data_11(data__11),
    .valid_00(valid__00),
    .valid_000(valid_000),
    .valid_11(valid__11)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:32" *)
  recirculador recirculador1 (
    .clk(clk_f),
    .data_in_0(data_0),
    .data_in_1(data_1),
    .data_in_2(data_2),
    .data_in_3(data_3),
    .data_out_0(data_r_0),
    .data_out_1(data_r_1),
    .data_out_2(data_r_2),
    .data_out_3(data_r_3),
    .data_out_4(recirc_0),
    .data_out_5(recirc_1),
    .data_out_6(recirc_2),
    .data_out_7(recirc_3),
    .idle(idle),
    .valid_in_0(valid_0),
    .valid_in_1(valid_1),
    .valid_in_2(valid_2),
    .valid_in_3(valid_3),
    .valid_out_0(valid_int_0),
    .valid_out_1(valid_int_1),
    .valid_out_2(valid_int_2),
    .valid_out_3(valid_int_3),
    .valid_out_4(valid_r_0),
    .valid_out_5(valid_r_1),
    .valid_out_6(valid_r_2),
    .valid_out_7(valid_r_3)
  );
endmodule

(* src = "./recirculador/recirculador.v:1" *)
module synt_recirculador(idle, clk, data_in_0, data_in_1, data_in_2, data_in_3, valid_in_0, valid_in_1, valid_in_2, valid_in_3, data_out_0, data_out_1, data_out_2, data_out_3, data_out_4, data_out_5, data_out_6, data_out_7, valid_out_0, valid_out_1, valid_out_2, valid_out_3, valid_out_4, valid_out_5, valid_out_6, valid_out_7);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  (* src = "./recirculador/recirculador.v:3" *)
  input clk;
  (* src = "./recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_0;
  (* src = "./recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_1;
  (* src = "./recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_2;
  (* src = "./recirculador/recirculador.v:37" *)
  wire [7:0] data_ff_3;
  (* src = "./recirculador/recirculador.v:5" *)
  input [7:0] data_in_0;
  (* src = "./recirculador/recirculador.v:6" *)
  input [7:0] data_in_1;
  (* src = "./recirculador/recirculador.v:7" *)
  input [7:0] data_in_2;
  (* src = "./recirculador/recirculador.v:8" *)
  input [7:0] data_in_3;
  (* src = "./recirculador/recirculador.v:15" *)
  output [7:0] data_out_0;
  (* src = "./recirculador/recirculador.v:16" *)
  output [7:0] data_out_1;
  (* src = "./recirculador/recirculador.v:17" *)
  output [7:0] data_out_2;
  (* src = "./recirculador/recirculador.v:18" *)
  output [7:0] data_out_3;
  (* src = "./recirculador/recirculador.v:20" *)
  output [7:0] data_out_4;
  (* src = "./recirculador/recirculador.v:21" *)
  output [7:0] data_out_5;
  (* src = "./recirculador/recirculador.v:22" *)
  output [7:0] data_out_6;
  (* src = "./recirculador/recirculador.v:23" *)
  output [7:0] data_out_7;
  (* src = "./recirculador/recirculador.v:2" *)
  input idle;
  (* src = "./recirculador/recirculador.v:39" *)
  wire valid_ff_0;
  (* src = "./recirculador/recirculador.v:39" *)
  wire valid_ff_1;
  (* src = "./recirculador/recirculador.v:39" *)
  wire valid_ff_2;
  (* src = "./recirculador/recirculador.v:39" *)
  wire valid_ff_3;
  (* src = "./recirculador/recirculador.v:10" *)
  input valid_in_0;
  (* src = "./recirculador/recirculador.v:11" *)
  input valid_in_1;
  (* src = "./recirculador/recirculador.v:12" *)
  input valid_in_2;
  (* src = "./recirculador/recirculador.v:13" *)
  input valid_in_3;
  (* src = "./recirculador/recirculador.v:25" *)
  output valid_out_0;
  (* src = "./recirculador/recirculador.v:26" *)
  output valid_out_1;
  (* src = "./recirculador/recirculador.v:27" *)
  output valid_out_2;
  (* src = "./recirculador/recirculador.v:28" *)
  output valid_out_3;
  (* src = "./recirculador/recirculador.v:29" *)
  output valid_out_4;
  (* src = "./recirculador/recirculador.v:30" *)
  output valid_out_5;
  (* src = "./recirculador/recirculador.v:31" *)
  output valid_out_6;
  (* src = "./recirculador/recirculador.v:32" *)
  output valid_out_7;
  NOT _064_ (
    .A(data_ff_1[6]),
    .Y(_062_)
  );
  NOT _065_ (
    .A(data_ff_1[5]),
    .Y(_063_)
  );
  NOT _066_ (
    .A(data_ff_1[4]),
    .Y(_000_)
  );
  NOT _067_ (
    .A(data_ff_1[3]),
    .Y(_001_)
  );
  NOT _068_ (
    .A(data_ff_1[2]),
    .Y(_002_)
  );
  NOT _069_ (
    .A(data_ff_1[1]),
    .Y(_003_)
  );
  NOT _070_ (
    .A(data_ff_1[0]),
    .Y(_004_)
  );
  NOT _071_ (
    .A(data_ff_2[6]),
    .Y(_005_)
  );
  NOT _072_ (
    .A(data_ff_2[5]),
    .Y(_006_)
  );
  NOT _073_ (
    .A(data_ff_2[4]),
    .Y(_007_)
  );
  NOT _074_ (
    .A(data_ff_2[3]),
    .Y(_008_)
  );
  NOT _075_ (
    .A(data_ff_2[2]),
    .Y(_009_)
  );
  NOT _076_ (
    .A(data_ff_2[1]),
    .Y(_010_)
  );
  NOT _077_ (
    .A(data_ff_2[0]),
    .Y(_011_)
  );
  NOT _078_ (
    .A(data_ff_0[6]),
    .Y(_012_)
  );
  NOT _079_ (
    .A(data_ff_0[5]),
    .Y(_013_)
  );
  NOT _080_ (
    .A(data_ff_0[4]),
    .Y(_014_)
  );
  NOT _081_ (
    .A(data_ff_0[3]),
    .Y(_015_)
  );
  NOT _082_ (
    .A(data_ff_0[2]),
    .Y(_016_)
  );
  NOT _083_ (
    .A(data_ff_0[1]),
    .Y(_017_)
  );
  NOT _084_ (
    .A(data_ff_0[0]),
    .Y(_018_)
  );
  NOT _085_ (
    .A(data_ff_3[6]),
    .Y(_019_)
  );
  NOT _086_ (
    .A(data_ff_3[5]),
    .Y(_020_)
  );
  NOT _087_ (
    .A(data_ff_3[4]),
    .Y(_021_)
  );
  NOT _088_ (
    .A(data_ff_3[3]),
    .Y(_022_)
  );
  NOT _089_ (
    .A(data_ff_3[2]),
    .Y(_023_)
  );
  NOT _090_ (
    .A(data_ff_3[1]),
    .Y(_024_)
  );
  NOT _091_ (
    .A(data_ff_3[0]),
    .Y(_025_)
  );
  NOT _092_ (
    .A(data_ff_3[7]),
    .Y(_026_)
  );
  NOT _093_ (
    .A(data_ff_2[7]),
    .Y(_027_)
  );
  NOT _094_ (
    .A(data_ff_1[7]),
    .Y(_028_)
  );
  NOT _095_ (
    .A(data_ff_0[7]),
    .Y(_029_)
  );
  NAND _096_ (
    .A(data_ff_1[6]),
    .B(idle),
    .Y(_030_)
  );
  NOT _097_ (
    .A(_030_),
    .Y(data_out_1[6])
  );
  NAND _098_ (
    .A(idle),
    .B(data_ff_1[5]),
    .Y(_031_)
  );
  NOT _099_ (
    .A(_031_),
    .Y(data_out_1[5])
  );
  NAND _100_ (
    .A(idle),
    .B(data_ff_1[4]),
    .Y(_032_)
  );
  NOT _101_ (
    .A(_032_),
    .Y(data_out_1[4])
  );
  NAND _102_ (
    .A(idle),
    .B(data_ff_1[3]),
    .Y(_033_)
  );
  NOT _103_ (
    .A(_033_),
    .Y(data_out_1[3])
  );
  NAND _104_ (
    .A(idle),
    .B(data_ff_1[2]),
    .Y(_034_)
  );
  NOT _105_ (
    .A(_034_),
    .Y(data_out_1[2])
  );
  NAND _106_ (
    .A(idle),
    .B(data_ff_1[1]),
    .Y(_035_)
  );
  NOT _107_ (
    .A(_035_),
    .Y(data_out_1[1])
  );
  NAND _108_ (
    .A(idle),
    .B(data_ff_1[0]),
    .Y(_036_)
  );
  NOT _109_ (
    .A(_036_),
    .Y(data_out_1[0])
  );
  NAND _110_ (
    .A(idle),
    .B(data_ff_2[6]),
    .Y(_037_)
  );
  NOT _111_ (
    .A(_037_),
    .Y(data_out_2[6])
  );
  NAND _112_ (
    .A(idle),
    .B(data_ff_2[5]),
    .Y(_038_)
  );
  NOT _113_ (
    .A(_038_),
    .Y(data_out_2[5])
  );
  NAND _114_ (
    .A(idle),
    .B(data_ff_2[4]),
    .Y(_039_)
  );
  NOT _115_ (
    .A(_039_),
    .Y(data_out_2[4])
  );
  NAND _116_ (
    .A(idle),
    .B(data_ff_2[3]),
    .Y(_040_)
  );
  NOT _117_ (
    .A(_040_),
    .Y(data_out_2[3])
  );
  NAND _118_ (
    .A(idle),
    .B(data_ff_2[2]),
    .Y(_041_)
  );
  NOT _119_ (
    .A(_041_),
    .Y(data_out_2[2])
  );
  NAND _120_ (
    .A(idle),
    .B(data_ff_2[1]),
    .Y(_042_)
  );
  NOT _121_ (
    .A(_042_),
    .Y(data_out_2[1])
  );
  NAND _122_ (
    .A(idle),
    .B(data_ff_2[0]),
    .Y(_043_)
  );
  NOT _123_ (
    .A(_043_),
    .Y(data_out_2[0])
  );
  NAND _124_ (
    .A(idle),
    .B(data_ff_0[6]),
    .Y(_044_)
  );
  NOT _125_ (
    .A(_044_),
    .Y(data_out_0[6])
  );
  NAND _126_ (
    .A(idle),
    .B(data_ff_0[5]),
    .Y(_045_)
  );
  NOT _127_ (
    .A(_045_),
    .Y(data_out_0[5])
  );
  NAND _128_ (
    .A(idle),
    .B(data_ff_0[4]),
    .Y(_046_)
  );
  NOT _129_ (
    .A(_046_),
    .Y(data_out_0[4])
  );
  NAND _130_ (
    .A(idle),
    .B(data_ff_0[3]),
    .Y(_047_)
  );
  NOT _131_ (
    .A(_047_),
    .Y(data_out_0[3])
  );
  NAND _132_ (
    .A(idle),
    .B(data_ff_0[2]),
    .Y(_048_)
  );
  NOT _133_ (
    .A(_048_),
    .Y(data_out_0[2])
  );
  NAND _134_ (
    .A(idle),
    .B(data_ff_0[1]),
    .Y(_049_)
  );
  NOT _135_ (
    .A(_049_),
    .Y(data_out_0[1])
  );
  NAND _136_ (
    .A(idle),
    .B(data_ff_0[0]),
    .Y(_050_)
  );
  NOT _137_ (
    .A(_050_),
    .Y(data_out_0[0])
  );
  NOR _138_ (
    .A(idle),
    .B(_012_),
    .Y(data_out_4[6])
  );
  NOR _139_ (
    .A(idle),
    .B(_013_),
    .Y(data_out_4[5])
  );
  NOR _140_ (
    .A(idle),
    .B(_014_),
    .Y(data_out_4[4])
  );
  NOR _141_ (
    .A(idle),
    .B(_015_),
    .Y(data_out_4[3])
  );
  NOR _142_ (
    .A(idle),
    .B(_016_),
    .Y(data_out_4[2])
  );
  NOR _143_ (
    .A(idle),
    .B(_017_),
    .Y(data_out_4[1])
  );
  NOR _144_ (
    .A(idle),
    .B(_018_),
    .Y(data_out_4[0])
  );
  NOR _145_ (
    .A(_062_),
    .B(idle),
    .Y(data_out_5[6])
  );
  NOR _146_ (
    .A(idle),
    .B(_063_),
    .Y(data_out_5[5])
  );
  NOR _147_ (
    .A(idle),
    .B(_000_),
    .Y(data_out_5[4])
  );
  NOR _148_ (
    .A(idle),
    .B(_001_),
    .Y(data_out_5[3])
  );
  NOR _149_ (
    .A(idle),
    .B(_002_),
    .Y(data_out_5[2])
  );
  NOR _150_ (
    .A(idle),
    .B(_003_),
    .Y(data_out_5[1])
  );
  NOR _151_ (
    .A(idle),
    .B(_004_),
    .Y(data_out_5[0])
  );
  NAND _152_ (
    .A(idle),
    .B(data_ff_3[6]),
    .Y(_051_)
  );
  NOT _153_ (
    .A(_051_),
    .Y(data_out_3[6])
  );
  NAND _154_ (
    .A(idle),
    .B(data_ff_3[5]),
    .Y(_052_)
  );
  NOT _155_ (
    .A(_052_),
    .Y(data_out_3[5])
  );
  NAND _156_ (
    .A(idle),
    .B(data_ff_3[4]),
    .Y(_053_)
  );
  NOT _157_ (
    .A(_053_),
    .Y(data_out_3[4])
  );
  NAND _158_ (
    .A(idle),
    .B(data_ff_3[3]),
    .Y(_054_)
  );
  NOT _159_ (
    .A(_054_),
    .Y(data_out_3[3])
  );
  NAND _160_ (
    .A(idle),
    .B(data_ff_3[2]),
    .Y(_055_)
  );
  NOT _161_ (
    .A(_055_),
    .Y(data_out_3[2])
  );
  NAND _162_ (
    .A(idle),
    .B(data_ff_3[1]),
    .Y(_056_)
  );
  NOT _163_ (
    .A(_056_),
    .Y(data_out_3[1])
  );
  NAND _164_ (
    .A(idle),
    .B(data_ff_3[0]),
    .Y(_057_)
  );
  NOT _165_ (
    .A(_057_),
    .Y(data_out_3[0])
  );
  NOR _166_ (
    .A(idle),
    .B(_019_),
    .Y(data_out_7[6])
  );
  NOR _167_ (
    .A(idle),
    .B(_020_),
    .Y(data_out_7[5])
  );
  NOR _168_ (
    .A(idle),
    .B(_021_),
    .Y(data_out_7[4])
  );
  NOR _169_ (
    .A(idle),
    .B(_022_),
    .Y(data_out_7[3])
  );
  NOR _170_ (
    .A(idle),
    .B(_023_),
    .Y(data_out_7[2])
  );
  NOR _171_ (
    .A(idle),
    .B(_024_),
    .Y(data_out_7[1])
  );
  NOR _172_ (
    .A(idle),
    .B(_025_),
    .Y(data_out_7[0])
  );
  NOR _173_ (
    .A(idle),
    .B(_005_),
    .Y(data_out_6[6])
  );
  NOR _174_ (
    .A(idle),
    .B(_006_),
    .Y(data_out_6[5])
  );
  NOR _175_ (
    .A(idle),
    .B(_007_),
    .Y(data_out_6[4])
  );
  NOR _176_ (
    .A(idle),
    .B(_008_),
    .Y(data_out_6[3])
  );
  NOR _177_ (
    .A(idle),
    .B(_009_),
    .Y(data_out_6[2])
  );
  NOR _178_ (
    .A(idle),
    .B(_010_),
    .Y(data_out_6[1])
  );
  NOR _179_ (
    .A(idle),
    .B(_011_),
    .Y(data_out_6[0])
  );
  NOR _180_ (
    .A(idle),
    .B(_026_),
    .Y(data_out_7[7])
  );
  NOR _181_ (
    .A(idle),
    .B(_027_),
    .Y(data_out_6[7])
  );
  NOR _182_ (
    .A(idle),
    .B(_028_),
    .Y(data_out_5[7])
  );
  NOR _183_ (
    .A(idle),
    .B(_029_),
    .Y(data_out_4[7])
  );
  NAND _184_ (
    .A(idle),
    .B(data_ff_3[7]),
    .Y(_058_)
  );
  NOT _185_ (
    .A(_058_),
    .Y(data_out_3[7])
  );
  NAND _186_ (
    .A(idle),
    .B(data_ff_2[7]),
    .Y(_059_)
  );
  NOT _187_ (
    .A(_059_),
    .Y(data_out_2[7])
  );
  NAND _188_ (
    .A(idle),
    .B(data_ff_1[7]),
    .Y(_060_)
  );
  NOT _189_ (
    .A(_060_),
    .Y(data_out_1[7])
  );
  NAND _190_ (
    .A(idle),
    .B(data_ff_0[7]),
    .Y(_061_)
  );
  NOT _191_ (
    .A(_061_),
    .Y(data_out_0[7])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _192_ (
    .C(clk),
    .D(data_in_0[0]),
    .Q(data_ff_0[0])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _193_ (
    .C(clk),
    .D(data_in_0[1]),
    .Q(data_ff_0[1])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _194_ (
    .C(clk),
    .D(data_in_0[2]),
    .Q(data_ff_0[2])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _195_ (
    .C(clk),
    .D(data_in_0[3]),
    .Q(data_ff_0[3])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _196_ (
    .C(clk),
    .D(data_in_0[4]),
    .Q(data_ff_0[4])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _197_ (
    .C(clk),
    .D(data_in_0[5]),
    .Q(data_ff_0[5])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _198_ (
    .C(clk),
    .D(data_in_0[6]),
    .Q(data_ff_0[6])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _199_ (
    .C(clk),
    .D(data_in_0[7]),
    .Q(data_ff_0[7])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _200_ (
    .C(clk),
    .D(data_in_1[0]),
    .Q(data_ff_1[0])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _201_ (
    .C(clk),
    .D(data_in_1[1]),
    .Q(data_ff_1[1])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _202_ (
    .C(clk),
    .D(data_in_1[2]),
    .Q(data_ff_1[2])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _203_ (
    .C(clk),
    .D(data_in_1[3]),
    .Q(data_ff_1[3])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _204_ (
    .C(clk),
    .D(data_in_1[4]),
    .Q(data_ff_1[4])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _205_ (
    .C(clk),
    .D(data_in_1[5]),
    .Q(data_ff_1[5])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _206_ (
    .C(clk),
    .D(data_in_1[6]),
    .Q(data_ff_1[6])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _207_ (
    .C(clk),
    .D(data_in_1[7]),
    .Q(data_ff_1[7])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _208_ (
    .C(clk),
    .D(data_in_2[0]),
    .Q(data_ff_2[0])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _209_ (
    .C(clk),
    .D(data_in_2[1]),
    .Q(data_ff_2[1])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _210_ (
    .C(clk),
    .D(data_in_2[2]),
    .Q(data_ff_2[2])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _211_ (
    .C(clk),
    .D(data_in_2[3]),
    .Q(data_ff_2[3])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _212_ (
    .C(clk),
    .D(data_in_2[4]),
    .Q(data_ff_2[4])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _213_ (
    .C(clk),
    .D(data_in_2[5]),
    .Q(data_ff_2[5])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _214_ (
    .C(clk),
    .D(data_in_2[6]),
    .Q(data_ff_2[6])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _215_ (
    .C(clk),
    .D(data_in_2[7]),
    .Q(data_ff_2[7])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _216_ (
    .C(clk),
    .D(data_in_3[0]),
    .Q(data_ff_3[0])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _217_ (
    .C(clk),
    .D(data_in_3[1]),
    .Q(data_ff_3[1])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _218_ (
    .C(clk),
    .D(data_in_3[2]),
    .Q(data_ff_3[2])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _219_ (
    .C(clk),
    .D(data_in_3[3]),
    .Q(data_ff_3[3])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _220_ (
    .C(clk),
    .D(data_in_3[4]),
    .Q(data_ff_3[4])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _221_ (
    .C(clk),
    .D(data_in_3[5]),
    .Q(data_ff_3[5])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _222_ (
    .C(clk),
    .D(data_in_3[6]),
    .Q(data_ff_3[6])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _223_ (
    .C(clk),
    .D(data_in_3[7]),
    .Q(data_ff_3[7])
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _224_ (
    .C(clk),
    .D(valid_in_0),
    .Q(valid_ff_0)
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _225_ (
    .C(clk),
    .D(valid_in_1),
    .Q(valid_ff_1)
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _226_ (
    .C(clk),
    .D(valid_in_2),
    .Q(valid_ff_2)
  );
  (* src = "./recirculador/recirculador.v:42" *)
  DFF _227_ (
    .C(clk),
    .D(valid_in_3),
    .Q(valid_ff_3)
  );
  assign valid_out_0 = valid_ff_0;
  assign valid_out_1 = valid_ff_1;
  assign valid_out_2 = valid_ff_2;
  assign valid_out_3 = valid_ff_3;
  assign valid_out_4 = 1'h0;
  assign valid_out_5 = 1'h0;
  assign valid_out_6 = 1'h0;
  assign valid_out_7 = 1'h0;
endmodule
