/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/FSM.v:1" *)
module FSM_synth(clk, reset_L, init, almost_empty_threshold_input, almost_full_threshold_input, FIFOs_empty, idle, almost_empty_threshold, almost_full_threshold);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "rtl/FSM.v:12" *)
  input [7:0] FIFOs_empty;
  (* src = "rtl/FSM.v:14" *)
  output [2:0] almost_empty_threshold;
  (* src = "rtl/FSM.v:10" *)
  input [2:0] almost_empty_threshold_input;
  (* src = "rtl/FSM.v:15" *)
  output [2:0] almost_full_threshold;
  (* src = "rtl/FSM.v:11" *)
  input [2:0] almost_full_threshold_input;
  (* src = "rtl/FSM.v:7" *)
  input clk;
  (* onehot = 32'd1 *)
  wire [3:0] estado_actual;
  (* src = "rtl/FSM.v:13" *)
  output idle;
  (* src = "rtl/FSM.v:9" *)
  input init;
  (* src = "rtl/FSM.v:8" *)
  input reset_L;
  NOT _20_ (
    .A(reset_L),
    .Y(_01_)
  );
  NOT _21_ (
    .A(estado_actual[3]),
    .Y(_04_)
  );
  NAND _22_ (
    .A(FIFOs_empty[5]),
    .B(FIFOs_empty[4]),
    .Y(_05_)
  );
  NAND _23_ (
    .A(FIFOs_empty[7]),
    .B(FIFOs_empty[6]),
    .Y(_06_)
  );
  NOR _24_ (
    .A(_05_),
    .B(_06_),
    .Y(_07_)
  );
  NAND _25_ (
    .A(FIFOs_empty[1]),
    .B(FIFOs_empty[0]),
    .Y(_08_)
  );
  NAND _26_ (
    .A(FIFOs_empty[3]),
    .B(FIFOs_empty[2]),
    .Y(_09_)
  );
  NOR _27_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  NAND _28_ (
    .A(_07_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _29_ (
    .A(estado_actual[2]),
    .B(estado_actual[1]),
    .Y(_12_)
  );
  NAND _30_ (
    .A(reset_L),
    .B(_11_),
    .Y(_13_)
  );
  NOR _31_ (
    .A(_12_),
    .B(_13_),
    .Y(_00_)
  );
  NOR _32_ (
    .A(init),
    .B(_04_),
    .Y(_14_)
  );
  NOR _33_ (
    .A(_11_),
    .B(_12_),
    .Y(_15_)
  );
  NOR _34_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _35_ (
    .A(_01_),
    .B(_16_),
    .Y(_02_)
  );
  NAND _36_ (
    .A(init),
    .B(estado_actual[3]),
    .Y(_17_)
  );
  NOT _37_ (
    .A(_17_),
    .Y(_18_)
  );
  NOR _38_ (
    .A(estado_actual[0]),
    .B(_18_),
    .Y(_19_)
  );
  NOR _39_ (
    .A(_01_),
    .B(_19_),
    .Y(_03_)
  );
  NAND _40_ (
    .A(estado_actual[2]),
    .B(_11_),
    .Y(idle)
  );
  DFF _41_ (
    .C(clk),
    .D(_01_),
    .Q(estado_actual[0])
  );
  DFF _42_ (
    .C(clk),
    .D(_00_),
    .Q(estado_actual[1])
  );
  DFF _43_ (
    .C(clk),
    .D(_02_),
    .Q(estado_actual[2])
  );
  DFF _44_ (
    .C(clk),
    .D(_03_),
    .Q(estado_actual[3])
  );
  assign almost_empty_threshold = 3'h2;
  assign almost_full_threshold = 3'h6;
endmodule
