/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "serial_paralelo_rx.v:1" *)
module serial_paralelo_rx_synth(sp_out, valid_out_sp, active, data_in, rst_L, clk_4f, clk_32f);
  (* src = "serial_paralelo_rx.v:28" *)
  wire [2:0] _000_;
  (* src = "serial_paralelo_rx.v:14" *)
  wire [2:0] _001_;
  (* src = "serial_paralelo_rx.v:24" *)
  wire [7:0] _002_;
  (* src = "serial_paralelo_rx.v:28" *)
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  (* src = "serial_paralelo_rx.v:12" *)
  wire [2:0] BCcounter;
  (* src = "serial_paralelo_rx.v:4" *)
  output active;
  (* src = "serial_paralelo_rx.v:8" *)
  input clk_32f;
  (* src = "serial_paralelo_rx.v:7" *)
  input clk_4f;
  (* src = "serial_paralelo_rx.v:11" *)
  wire [2:0] counter;
  (* src = "serial_paralelo_rx.v:5" *)
  input data_in;
  (* src = "serial_paralelo_rx.v:6" *)
  input rst_L;
  (* src = "serial_paralelo_rx.v:10" *)
  wire [7:0] serial_in;
  (* src = "serial_paralelo_rx.v:2" *)
  output [7:0] sp_out;
  (* src = "serial_paralelo_rx.v:3" *)
  output valid_out_sp;
  NOT _093_ (
    .A(BCcounter[1]),
    .Y(_062_)
  );
  NOT _094_ (
    .A(counter[2]),
    .Y(_063_)
  );
  NOT _095_ (
    .A(counter[1]),
    .Y(_064_)
  );
  NOT _096_ (
    .A(counter[0]),
    .Y(_065_)
  );
  NOT _097_ (
    .A(clk_32f),
    .Y(_004_)
  );
  NOT _098_ (
    .A(rst_L),
    .Y(_066_)
  );
  NOT _099_ (
    .A(sp_out[4]),
    .Y(_067_)
  );
  NOR _100_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_068_)
  );
  NOT _101_ (
    .A(_068_),
    .Y(_069_)
  );
  NAND _102_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_070_)
  );
  NOT _103_ (
    .A(_070_),
    .Y(_071_)
  );
  NAND _104_ (
    .A(rst_L),
    .B(_070_),
    .Y(_072_)
  );
  NOR _105_ (
    .A(_068_),
    .B(_072_),
    .Y(_001_[1])
  );
  NOR _106_ (
    .A(counter[0]),
    .B(_066_),
    .Y(_001_[0])
  );
  NAND _107_ (
    .A(rst_L),
    .B(serial_in[6]),
    .Y(_073_)
  );
  NOT _108_ (
    .A(_073_),
    .Y(_003_[6])
  );
  NAND _109_ (
    .A(rst_L),
    .B(serial_in[5]),
    .Y(_074_)
  );
  NOT _110_ (
    .A(_074_),
    .Y(_003_[5])
  );
  NAND _111_ (
    .A(rst_L),
    .B(serial_in[4]),
    .Y(_075_)
  );
  NOT _112_ (
    .A(_075_),
    .Y(_003_[4])
  );
  NAND _113_ (
    .A(rst_L),
    .B(serial_in[3]),
    .Y(_076_)
  );
  NOT _114_ (
    .A(_076_),
    .Y(_003_[3])
  );
  NAND _115_ (
    .A(rst_L),
    .B(serial_in[2]),
    .Y(_077_)
  );
  NOT _116_ (
    .A(_077_),
    .Y(_003_[2])
  );
  NAND _117_ (
    .A(rst_L),
    .B(serial_in[1]),
    .Y(_078_)
  );
  NOT _118_ (
    .A(_078_),
    .Y(_003_[1])
  );
  NAND _119_ (
    .A(rst_L),
    .B(serial_in[0]),
    .Y(_079_)
  );
  NOT _120_ (
    .A(_079_),
    .Y(_003_[0])
  );
  NOR _121_ (
    .A(serial_in[1]),
    .B(serial_in[0]),
    .Y(_080_)
  );
  NAND _122_ (
    .A(serial_in[7]),
    .B(_080_),
    .Y(_081_)
  );
  NOR _123_ (
    .A(BCcounter[2]),
    .B(serial_in[6]),
    .Y(_082_)
  );
  NAND _124_ (
    .A(serial_in[5]),
    .B(serial_in[4]),
    .Y(_083_)
  );
  NAND _125_ (
    .A(serial_in[3]),
    .B(serial_in[2]),
    .Y(_084_)
  );
  NOR _126_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _127_ (
    .A(_082_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _128_ (
    .A(_081_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _129_ (
    .A(BCcounter[0]),
    .B(_087_),
    .Y(_088_)
  );
  NAND _130_ (
    .A(_062_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _131_ (
    .A(rst_L),
    .B(_089_),
    .Y(_090_)
  );
  NOR _132_ (
    .A(_062_),
    .B(_088_),
    .Y(_091_)
  );
  NOR _133_ (
    .A(_090_),
    .B(_091_),
    .Y(_000_[1])
  );
  NOR _134_ (
    .A(BCcounter[0]),
    .B(_087_),
    .Y(_092_)
  );
  NAND _135_ (
    .A(rst_L),
    .B(_088_),
    .Y(_012_)
  );
  NOR _136_ (
    .A(_092_),
    .B(_012_),
    .Y(_000_[0])
  );
  NOR _137_ (
    .A(sp_out[1]),
    .B(sp_out[0]),
    .Y(_013_)
  );
  NAND _138_ (
    .A(sp_out[5]),
    .B(sp_out[3]),
    .Y(_014_)
  );
  NAND _139_ (
    .A(sp_out[2]),
    .B(sp_out[7]),
    .Y(_015_)
  );
  NOT _140_ (
    .A(_015_),
    .Y(_016_)
  );
  NOR _141_ (
    .A(sp_out[6]),
    .B(_067_),
    .Y(_017_)
  );
  NAND _142_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _143_ (
    .A(_014_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _144_ (
    .A(_013_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _145_ (
    .A(BCcounter[2]),
    .B(_020_),
    .Y(_021_)
  );
  NOT _146_ (
    .A(_021_),
    .Y(valid_out_sp)
  );
  NOR _147_ (
    .A(BCcounter[2]),
    .B(_091_),
    .Y(_022_)
  );
  NOR _148_ (
    .A(_066_),
    .B(_022_),
    .Y(_000_[2])
  );
  NAND _149_ (
    .A(rst_L),
    .B(serial_in[7]),
    .Y(_023_)
  );
  NOT _150_ (
    .A(_023_),
    .Y(_003_[7])
  );
  NOR _151_ (
    .A(counter[2]),
    .B(_069_),
    .Y(_024_)
  );
  NAND _152_ (
    .A(_063_),
    .B(_068_),
    .Y(_025_)
  );
  NAND _153_ (
    .A(data_in),
    .B(_024_),
    .Y(_026_)
  );
  NAND _154_ (
    .A(serial_in[7]),
    .B(_025_),
    .Y(_027_)
  );
  NAND _155_ (
    .A(_026_),
    .B(_027_),
    .Y(_002_[7])
  );
  NOR _156_ (
    .A(counter[2]),
    .B(_070_),
    .Y(_028_)
  );
  NOT _157_ (
    .A(_028_),
    .Y(_029_)
  );
  NAND _158_ (
    .A(data_in),
    .B(_028_),
    .Y(_030_)
  );
  NAND _159_ (
    .A(serial_in[4]),
    .B(_029_),
    .Y(_031_)
  );
  NAND _160_ (
    .A(_030_),
    .B(_031_),
    .Y(_002_[4])
  );
  NOR _161_ (
    .A(counter[1]),
    .B(_065_),
    .Y(_032_)
  );
  NAND _162_ (
    .A(_064_),
    .B(counter[0]),
    .Y(_033_)
  );
  NOR _163_ (
    .A(_063_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _164_ (
    .A(counter[2]),
    .B(_032_),
    .Y(_035_)
  );
  NAND _165_ (
    .A(data_in),
    .B(_034_),
    .Y(_036_)
  );
  NAND _166_ (
    .A(serial_in[2]),
    .B(_035_),
    .Y(_037_)
  );
  NAND _167_ (
    .A(_036_),
    .B(_037_),
    .Y(_002_[2])
  );
  NAND _168_ (
    .A(counter[2]),
    .B(_071_),
    .Y(_038_)
  );
  NOT _169_ (
    .A(_038_),
    .Y(_039_)
  );
  NAND _170_ (
    .A(data_in),
    .B(_039_),
    .Y(_040_)
  );
  NAND _171_ (
    .A(serial_in[0]),
    .B(_038_),
    .Y(_041_)
  );
  NAND _172_ (
    .A(_040_),
    .B(_041_),
    .Y(_002_[0])
  );
  NOR _173_ (
    .A(counter[2]),
    .B(_033_),
    .Y(_042_)
  );
  NAND _174_ (
    .A(_063_),
    .B(_032_),
    .Y(_043_)
  );
  NAND _175_ (
    .A(data_in),
    .B(_042_),
    .Y(_044_)
  );
  NAND _176_ (
    .A(serial_in[6]),
    .B(_043_),
    .Y(_045_)
  );
  NAND _177_ (
    .A(_044_),
    .B(_045_),
    .Y(_002_[6])
  );
  NOR _178_ (
    .A(_064_),
    .B(counter[0]),
    .Y(_046_)
  );
  NAND _179_ (
    .A(counter[1]),
    .B(_065_),
    .Y(_047_)
  );
  NOR _180_ (
    .A(_063_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _181_ (
    .A(counter[2]),
    .B(_046_),
    .Y(_049_)
  );
  NAND _182_ (
    .A(data_in),
    .B(_048_),
    .Y(_050_)
  );
  NAND _183_ (
    .A(serial_in[1]),
    .B(_049_),
    .Y(_051_)
  );
  NAND _184_ (
    .A(_050_),
    .B(_051_),
    .Y(_002_[1])
  );
  NAND _185_ (
    .A(counter[2]),
    .B(_068_),
    .Y(_052_)
  );
  NOT _186_ (
    .A(_052_),
    .Y(_053_)
  );
  NAND _187_ (
    .A(data_in),
    .B(_053_),
    .Y(_054_)
  );
  NAND _188_ (
    .A(serial_in[3]),
    .B(_052_),
    .Y(_055_)
  );
  NAND _189_ (
    .A(_054_),
    .B(_055_),
    .Y(_002_[3])
  );
  NOR _190_ (
    .A(counter[2]),
    .B(_047_),
    .Y(_056_)
  );
  NAND _191_ (
    .A(_063_),
    .B(_046_),
    .Y(_057_)
  );
  NAND _192_ (
    .A(data_in),
    .B(_056_),
    .Y(_058_)
  );
  NAND _193_ (
    .A(serial_in[5]),
    .B(_057_),
    .Y(_059_)
  );
  NAND _194_ (
    .A(_058_),
    .B(_059_),
    .Y(_002_[5])
  );
  NAND _195_ (
    .A(_063_),
    .B(_070_),
    .Y(_060_)
  );
  NAND _196_ (
    .A(rst_L),
    .B(_060_),
    .Y(_061_)
  );
  NOR _197_ (
    .A(_039_),
    .B(_061_),
    .Y(_001_[2])
  );
  NOT _198_ (
    .A(clk_32f),
    .Y(_005_)
  );
  NOT _199_ (
    .A(clk_32f),
    .Y(_006_)
  );
  NOT _200_ (
    .A(clk_32f),
    .Y(_007_)
  );
  NOT _201_ (
    .A(clk_32f),
    .Y(_008_)
  );
  NOT _202_ (
    .A(clk_32f),
    .Y(_009_)
  );
  NOT _203_ (
    .A(clk_32f),
    .Y(_010_)
  );
  BUF _204_ (
    .A(BCcounter[2]),
    .Y(active)
  );
  NOT _205_ (
    .A(clk_32f),
    .Y(_011_)
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _206_ (
    .C(clk_4f),
    .D(_003_[0]),
    .Q(sp_out[0])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _207_ (
    .C(clk_4f),
    .D(_003_[1]),
    .Q(sp_out[1])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _208_ (
    .C(clk_4f),
    .D(_003_[2]),
    .Q(sp_out[2])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _209_ (
    .C(clk_4f),
    .D(_003_[3]),
    .Q(sp_out[3])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _210_ (
    .C(clk_4f),
    .D(_003_[4]),
    .Q(sp_out[4])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _211_ (
    .C(clk_4f),
    .D(_003_[5]),
    .Q(sp_out[5])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _212_ (
    .C(clk_4f),
    .D(_003_[6]),
    .Q(sp_out[6])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _213_ (
    .C(clk_4f),
    .D(_003_[7]),
    .Q(sp_out[7])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _214_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BCcounter[0])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _215_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BCcounter[1])
  );
  (* src = "serial_paralelo_rx.v:28" *)
  DFF _216_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BCcounter[2])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _217_ (
    .C(_010_),
    .D(_002_[0]),
    .Q(serial_in[0])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _218_ (
    .C(_009_),
    .D(_002_[1]),
    .Q(serial_in[1])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _219_ (
    .C(_008_),
    .D(_002_[2]),
    .Q(serial_in[2])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _220_ (
    .C(_007_),
    .D(_002_[3]),
    .Q(serial_in[3])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _221_ (
    .C(_006_),
    .D(_002_[4]),
    .Q(serial_in[4])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _222_ (
    .C(_005_),
    .D(_002_[5]),
    .Q(serial_in[5])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _223_ (
    .C(_004_),
    .D(_002_[6]),
    .Q(serial_in[6])
  );
  (* src = "serial_paralelo_rx.v:24" *)
  DFF _224_ (
    .C(_011_),
    .D(_002_[7]),
    .Q(serial_in[7])
  );
  (* src = "serial_paralelo_rx.v:14" *)
  DFF _225_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(counter[0])
  );
  (* src = "serial_paralelo_rx.v:14" *)
  DFF _226_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(counter[1])
  );
  (* src = "serial_paralelo_rx.v:14" *)
  DFF _227_ (
    .C(clk_32f),
    .D(_001_[2]),
    .Q(counter[2])
  );
endmodule
