/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contadores_synth.v:1" *)
module contadores_synth(clk, rst_l, req, pop_0, pop_1, pop_2, pop_3, idx, idle, data, valid);
  (* src = "contadores_synth.v:26" *)
  wire [4:0] _000_;
  (* src = "contadores_synth.v:26" *)
  wire [4:0] _001_;
  (* src = "contadores_synth.v:26" *)
  wire [4:0] _002_;
  (* src = "contadores_synth.v:26" *)
  wire [4:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  (* src = "contadores_synth.v:2" *)
  input clk;
  (* src = "contadores_synth.v:1" *)
  wire [4:0] \contador[0] ;
  (* src = "contadores_synth.v:1" *)
  wire [4:0] \contador[1] ;
  (* src = "contadores_synth.v:1" *)
  wire [4:0] \contador[2] ;
  (* src = "contadores_synth.v:1" *)
  wire [4:0] \contador[3] ;
  (* src = "contadores_synth.v:11" *)
  output [4:0] data;
  (* src = "contadores_synth.v:25" *)
  wire [31:0] i;
  (* src = "contadores_synth.v:10" *)
  input idle;
  (* src = "contadores_synth.v:9" *)
  input [1:0] idx;
  (* src = "contadores_synth.v:5" *)
  input pop_0;
  (* src = "contadores_synth.v:6" *)
  input pop_1;
  (* src = "contadores_synth.v:7" *)
  input pop_2;
  (* src = "contadores_synth.v:8" *)
  input pop_3;
  (* src = "contadores_synth.v:4" *)
  input req;
  (* src = "contadores_synth.v:3" *)
  input rst_l;
  (* src = "contadores_synth.v:12" *)
  output valid;
  NOT _126_ (
    .A(\contador[3] [4]),
    .Y(_088_)
  );
  NOT _127_ (
    .A(\contador[3] [3]),
    .Y(_089_)
  );
  NOT _128_ (
    .A(\contador[3] [1]),
    .Y(_090_)
  );
  NOT _129_ (
    .A(\contador[2] [4]),
    .Y(_091_)
  );
  NOT _130_ (
    .A(\contador[2] [3]),
    .Y(_092_)
  );
  NOT _131_ (
    .A(\contador[2] [1]),
    .Y(_093_)
  );
  NOT _132_ (
    .A(\contador[1] [4]),
    .Y(_094_)
  );
  NOT _133_ (
    .A(\contador[1] [3]),
    .Y(_095_)
  );
  NOT _134_ (
    .A(\contador[1] [1]),
    .Y(_096_)
  );
  NOT _135_ (
    .A(\contador[0] [4]),
    .Y(_097_)
  );
  NOT _136_ (
    .A(\contador[0] [3]),
    .Y(_098_)
  );
  NOT _137_ (
    .A(\contador[0] [1]),
    .Y(_099_)
  );
  NOT _138_ (
    .A(idx[0]),
    .Y(_100_)
  );
  NOT _139_ (
    .A(idx[1]),
    .Y(_101_)
  );
  NAND _140_ (
    .A(\contador[0] [0]),
    .B(pop_0),
    .Y(_102_)
  );
  NOR _141_ (
    .A(_099_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _142_ (
    .A(\contador[0] [2]),
    .B(_103_),
    .Y(_104_)
  );
  NOT _143_ (
    .A(_104_),
    .Y(_105_)
  );
  NAND _144_ (
    .A(\contador[0] [3]),
    .B(_105_),
    .Y(_106_)
  );
  NOT _145_ (
    .A(_106_),
    .Y(_107_)
  );
  NAND _146_ (
    .A(_098_),
    .B(_104_),
    .Y(_108_)
  );
  NAND _147_ (
    .A(rst_l),
    .B(_108_),
    .Y(_109_)
  );
  NOR _148_ (
    .A(_107_),
    .B(_109_),
    .Y(_000_[3])
  );
  NOR _149_ (
    .A(\contador[0] [2]),
    .B(_103_),
    .Y(_110_)
  );
  NAND _150_ (
    .A(rst_l),
    .B(_104_),
    .Y(_111_)
  );
  NOR _151_ (
    .A(_110_),
    .B(_111_),
    .Y(_000_[2])
  );
  NAND _152_ (
    .A(_099_),
    .B(_102_),
    .Y(_112_)
  );
  NAND _153_ (
    .A(rst_l),
    .B(_112_),
    .Y(_113_)
  );
  NOR _154_ (
    .A(_103_),
    .B(_113_),
    .Y(_000_[1])
  );
  NOR _155_ (
    .A(\contador[0] [0]),
    .B(pop_0),
    .Y(_114_)
  );
  NAND _156_ (
    .A(rst_l),
    .B(_102_),
    .Y(_115_)
  );
  NOR _157_ (
    .A(_114_),
    .B(_115_),
    .Y(_000_[0])
  );
  NAND _158_ (
    .A(\contador[1] [0]),
    .B(pop_1),
    .Y(_116_)
  );
  NOR _159_ (
    .A(_096_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _160_ (
    .A(\contador[1] [2]),
    .B(_117_),
    .Y(_118_)
  );
  NOT _161_ (
    .A(_118_),
    .Y(_119_)
  );
  NAND _162_ (
    .A(\contador[1] [3]),
    .B(_119_),
    .Y(_120_)
  );
  NOT _163_ (
    .A(_120_),
    .Y(_121_)
  );
  NAND _164_ (
    .A(_095_),
    .B(_118_),
    .Y(_122_)
  );
  NAND _165_ (
    .A(rst_l),
    .B(_122_),
    .Y(_123_)
  );
  NOR _166_ (
    .A(_121_),
    .B(_123_),
    .Y(_001_[3])
  );
  NOR _167_ (
    .A(\contador[1] [2]),
    .B(_117_),
    .Y(_124_)
  );
  NAND _168_ (
    .A(rst_l),
    .B(_118_),
    .Y(_125_)
  );
  NOR _169_ (
    .A(_124_),
    .B(_125_),
    .Y(_001_[2])
  );
  NAND _170_ (
    .A(_096_),
    .B(_116_),
    .Y(_004_)
  );
  NAND _171_ (
    .A(rst_l),
    .B(_004_),
    .Y(_005_)
  );
  NOR _172_ (
    .A(_117_),
    .B(_005_),
    .Y(_001_[1])
  );
  NOR _173_ (
    .A(\contador[1] [0]),
    .B(pop_1),
    .Y(_006_)
  );
  NAND _174_ (
    .A(rst_l),
    .B(_116_),
    .Y(_007_)
  );
  NOR _175_ (
    .A(_006_),
    .B(_007_),
    .Y(_001_[0])
  );
  NAND _176_ (
    .A(\contador[2] [0]),
    .B(pop_2),
    .Y(_008_)
  );
  NOR _177_ (
    .A(_093_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _178_ (
    .A(\contador[2] [2]),
    .B(_009_),
    .Y(_010_)
  );
  NOT _179_ (
    .A(_010_),
    .Y(_011_)
  );
  NAND _180_ (
    .A(\contador[2] [3]),
    .B(_011_),
    .Y(_012_)
  );
  NOT _181_ (
    .A(_012_),
    .Y(_013_)
  );
  NAND _182_ (
    .A(_092_),
    .B(_010_),
    .Y(_014_)
  );
  NAND _183_ (
    .A(rst_l),
    .B(_014_),
    .Y(_015_)
  );
  NOR _184_ (
    .A(_013_),
    .B(_015_),
    .Y(_002_[3])
  );
  NOR _185_ (
    .A(\contador[2] [2]),
    .B(_009_),
    .Y(_016_)
  );
  NAND _186_ (
    .A(rst_l),
    .B(_010_),
    .Y(_017_)
  );
  NOR _187_ (
    .A(_016_),
    .B(_017_),
    .Y(_002_[2])
  );
  NAND _188_ (
    .A(_093_),
    .B(_008_),
    .Y(_018_)
  );
  NAND _189_ (
    .A(rst_l),
    .B(_018_),
    .Y(_019_)
  );
  NOR _190_ (
    .A(_009_),
    .B(_019_),
    .Y(_002_[1])
  );
  NOR _191_ (
    .A(\contador[2] [0]),
    .B(pop_2),
    .Y(_020_)
  );
  NAND _192_ (
    .A(rst_l),
    .B(_008_),
    .Y(_021_)
  );
  NOR _193_ (
    .A(_020_),
    .B(_021_),
    .Y(_002_[0])
  );
  NAND _194_ (
    .A(\contador[3] [0]),
    .B(pop_3),
    .Y(_022_)
  );
  NOR _195_ (
    .A(_090_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _196_ (
    .A(\contador[3] [2]),
    .B(_023_),
    .Y(_024_)
  );
  NOT _197_ (
    .A(_024_),
    .Y(_025_)
  );
  NAND _198_ (
    .A(\contador[3] [3]),
    .B(_025_),
    .Y(_026_)
  );
  NOT _199_ (
    .A(_026_),
    .Y(_027_)
  );
  NAND _200_ (
    .A(_089_),
    .B(_024_),
    .Y(_028_)
  );
  NAND _201_ (
    .A(rst_l),
    .B(_028_),
    .Y(_029_)
  );
  NOR _202_ (
    .A(_027_),
    .B(_029_),
    .Y(_003_[3])
  );
  NOR _203_ (
    .A(\contador[3] [2]),
    .B(_023_),
    .Y(_030_)
  );
  NAND _204_ (
    .A(rst_l),
    .B(_024_),
    .Y(_031_)
  );
  NOR _205_ (
    .A(_030_),
    .B(_031_),
    .Y(_003_[2])
  );
  NAND _206_ (
    .A(_090_),
    .B(_022_),
    .Y(_032_)
  );
  NAND _207_ (
    .A(rst_l),
    .B(_032_),
    .Y(_033_)
  );
  NOR _208_ (
    .A(_023_),
    .B(_033_),
    .Y(_003_[1])
  );
  NOR _209_ (
    .A(\contador[3] [0]),
    .B(pop_3),
    .Y(_034_)
  );
  NAND _210_ (
    .A(rst_l),
    .B(_022_),
    .Y(_035_)
  );
  NOR _211_ (
    .A(_034_),
    .B(_035_),
    .Y(_003_[0])
  );
  NAND _212_ (
    .A(req),
    .B(idle),
    .Y(_036_)
  );
  NOT _213_ (
    .A(_036_),
    .Y(valid)
  );
  NOR _214_ (
    .A(_100_),
    .B(idx[1]),
    .Y(_037_)
  );
  NAND _215_ (
    .A(\contador[1] [3]),
    .B(_037_),
    .Y(_038_)
  );
  NOR _216_ (
    .A(_100_),
    .B(_101_),
    .Y(_039_)
  );
  NAND _217_ (
    .A(\contador[3] [3]),
    .B(_039_),
    .Y(_040_)
  );
  NAND _218_ (
    .A(_038_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _219_ (
    .A(idx[0]),
    .B(_101_),
    .Y(_042_)
  );
  NAND _220_ (
    .A(\contador[2] [3]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _221_ (
    .A(idx[0]),
    .B(idx[1]),
    .Y(_044_)
  );
  NAND _222_ (
    .A(\contador[0] [3]),
    .B(_044_),
    .Y(_045_)
  );
  NAND _223_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _224_ (
    .A(_041_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _225_ (
    .A(_036_),
    .B(_047_),
    .Y(data[3])
  );
  NAND _226_ (
    .A(\contador[1] [2]),
    .B(_037_),
    .Y(_048_)
  );
  NAND _227_ (
    .A(\contador[3] [2]),
    .B(_039_),
    .Y(_049_)
  );
  NAND _228_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _229_ (
    .A(\contador[2] [2]),
    .B(_042_),
    .Y(_051_)
  );
  NAND _230_ (
    .A(\contador[0] [2]),
    .B(_044_),
    .Y(_052_)
  );
  NAND _231_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _232_ (
    .A(_050_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _233_ (
    .A(_036_),
    .B(_054_),
    .Y(data[2])
  );
  NAND _234_ (
    .A(\contador[1] [1]),
    .B(_037_),
    .Y(_055_)
  );
  NAND _235_ (
    .A(\contador[3] [1]),
    .B(_039_),
    .Y(_056_)
  );
  NAND _236_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _237_ (
    .A(\contador[2] [1]),
    .B(_042_),
    .Y(_058_)
  );
  NAND _238_ (
    .A(\contador[0] [1]),
    .B(_044_),
    .Y(_059_)
  );
  NAND _239_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _240_ (
    .A(_057_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _241_ (
    .A(_036_),
    .B(_061_),
    .Y(data[1])
  );
  NAND _242_ (
    .A(\contador[1] [0]),
    .B(_037_),
    .Y(_062_)
  );
  NAND _243_ (
    .A(\contador[3] [0]),
    .B(_039_),
    .Y(_063_)
  );
  NAND _244_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _245_ (
    .A(\contador[2] [0]),
    .B(_042_),
    .Y(_065_)
  );
  NAND _246_ (
    .A(\contador[0] [0]),
    .B(_044_),
    .Y(_066_)
  );
  NAND _247_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _248_ (
    .A(_064_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _249_ (
    .A(_036_),
    .B(_068_),
    .Y(data[0])
  );
  NAND _250_ (
    .A(\contador[1] [4]),
    .B(_037_),
    .Y(_069_)
  );
  NAND _251_ (
    .A(\contador[3] [4]),
    .B(_039_),
    .Y(_070_)
  );
  NAND _252_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _253_ (
    .A(\contador[2] [4]),
    .B(_042_),
    .Y(_072_)
  );
  NAND _254_ (
    .A(\contador[0] [4]),
    .B(_044_),
    .Y(_073_)
  );
  NAND _255_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _256_ (
    .A(_071_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _257_ (
    .A(_036_),
    .B(_075_),
    .Y(data[4])
  );
  NOR _258_ (
    .A(_088_),
    .B(_026_),
    .Y(_076_)
  );
  NAND _259_ (
    .A(_088_),
    .B(_026_),
    .Y(_077_)
  );
  NAND _260_ (
    .A(rst_l),
    .B(_077_),
    .Y(_078_)
  );
  NOR _261_ (
    .A(_076_),
    .B(_078_),
    .Y(_003_[4])
  );
  NOR _262_ (
    .A(_091_),
    .B(_012_),
    .Y(_079_)
  );
  NAND _263_ (
    .A(_091_),
    .B(_012_),
    .Y(_080_)
  );
  NAND _264_ (
    .A(rst_l),
    .B(_080_),
    .Y(_081_)
  );
  NOR _265_ (
    .A(_079_),
    .B(_081_),
    .Y(_002_[4])
  );
  NOR _266_ (
    .A(_094_),
    .B(_120_),
    .Y(_082_)
  );
  NAND _267_ (
    .A(_094_),
    .B(_120_),
    .Y(_083_)
  );
  NAND _268_ (
    .A(rst_l),
    .B(_083_),
    .Y(_084_)
  );
  NOR _269_ (
    .A(_082_),
    .B(_084_),
    .Y(_001_[4])
  );
  NOR _270_ (
    .A(_097_),
    .B(_106_),
    .Y(_085_)
  );
  NAND _271_ (
    .A(_097_),
    .B(_106_),
    .Y(_086_)
  );
  NAND _272_ (
    .A(rst_l),
    .B(_086_),
    .Y(_087_)
  );
  NOR _273_ (
    .A(_085_),
    .B(_087_),
    .Y(_000_[4])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _274_ (
    .C(clk),
    .D(_000_[0]),
    .Q(\contador[0] [0])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _275_ (
    .C(clk),
    .D(_000_[1]),
    .Q(\contador[0] [1])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _276_ (
    .C(clk),
    .D(_000_[2]),
    .Q(\contador[0] [2])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _277_ (
    .C(clk),
    .D(_000_[3]),
    .Q(\contador[0] [3])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _278_ (
    .C(clk),
    .D(_000_[4]),
    .Q(\contador[0] [4])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _279_ (
    .C(clk),
    .D(_001_[0]),
    .Q(\contador[1] [0])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _280_ (
    .C(clk),
    .D(_001_[1]),
    .Q(\contador[1] [1])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _281_ (
    .C(clk),
    .D(_001_[2]),
    .Q(\contador[1] [2])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _282_ (
    .C(clk),
    .D(_001_[3]),
    .Q(\contador[1] [3])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _283_ (
    .C(clk),
    .D(_001_[4]),
    .Q(\contador[1] [4])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _284_ (
    .C(clk),
    .D(_002_[0]),
    .Q(\contador[2] [0])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _285_ (
    .C(clk),
    .D(_002_[1]),
    .Q(\contador[2] [1])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _286_ (
    .C(clk),
    .D(_002_[2]),
    .Q(\contador[2] [2])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _287_ (
    .C(clk),
    .D(_002_[3]),
    .Q(\contador[2] [3])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _288_ (
    .C(clk),
    .D(_002_[4]),
    .Q(\contador[2] [4])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _289_ (
    .C(clk),
    .D(_003_[0]),
    .Q(\contador[3] [0])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _290_ (
    .C(clk),
    .D(_003_[1]),
    .Q(\contador[3] [1])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _291_ (
    .C(clk),
    .D(_003_[2]),
    .Q(\contador[3] [2])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _292_ (
    .C(clk),
    .D(_003_[3]),
    .Q(\contador[3] [3])
  );
  (* src = "contadores_synth.v:26" *)
  DFF _293_ (
    .C(clk),
    .D(_003_[4]),
    .Q(\contador[3] [4])
  );
  assign i = 32'd4;
endmodule
