/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "DEMUXES.v:4" *)
module DEMUXES_synth(data_0, data_1, data_2, data_3, valid_0, valid_1, valid_2, valid_3, clk_f, clk_2f, clk_4f, data_000, valid_000);
  (* src = "DEMUXES.v:14" *)
  input clk_2f;
  (* src = "DEMUXES.v:15" *)
  input clk_4f;
  (* src = "DEMUXES.v:13" *)
  input clk_f;
  (* src = "DEMUXES.v:21" *)
  wire [7:0] data00;
  (* src = "DEMUXES.v:21" *)
  wire [7:0] data11;
  (* src = "DEMUXES.v:5" *)
  output [7:0] data_0;
  (* src = "DEMUXES.v:17" *)
  input [7:0] data_000;
  (* src = "DEMUXES.v:6" *)
  output [7:0] data_1;
  (* src = "DEMUXES.v:7" *)
  output [7:0] data_2;
  (* src = "DEMUXES.v:8" *)
  output [7:0] data_3;
  (* src = "DEMUXES.v:22" *)
  wire valid00;
  (* src = "DEMUXES.v:22" *)
  wire valid11;
  (* src = "DEMUXES.v:9" *)
  output valid_0;
  (* src = "DEMUXES.v:18" *)
  input valid_000;
  (* src = "DEMUXES.v:10" *)
  output valid_1;
  (* src = "DEMUXES.v:11" *)
  output valid_2;
  (* src = "DEMUXES.v:12" *)
  output valid_3;
  (* module_not_derived = 32'd1 *)
  (* src = "DEMUXES.v:38" *)
  DEMUX_L1 DEMUX_L1_1 (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_0(data_0),
    .data_00(data00),
    .data_1(data_1),
    .data_11(data11),
    .data_2(data_2),
    .data_3(data_3),
    .valid_0(valid_0),
    .valid_00(valid00),
    .valid_1(valid_1),
    .valid_11(valid11),
    .valid_2(valid_2),
    .valid_3(valid_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "DEMUXES.v:25" *)
  DEMUX_L2 DEMUX_L2_1 (
    .clk_2f(clk_2f),
    .clk_4f(clk_4f),
    .data_00(data00),
    .data_000(data_000),
    .data_11(data11),
    .valid_00(valid00),
    .valid_000(valid_000),
    .valid_11(valid11)
  );
endmodule

(* src = "DEMUX_L1.v:1" *)
module DEMUX1_L1_synth(data_00, data_11, valid_00, valid_11, clk_f, clk_2f, data_0, data_1, data_2, data_3, valid_0, valid_1, valid_2, valid_3);
  (* src = "DEMUX_L1.v:29" *)
  wire [7:0] _000_;
  (* src = "DEMUX_L1.v:52" *)
  wire [7:0] _001_;
  (* src = "DEMUX_L1.v:75" *)
  wire [7:0] _002_;
  (* src = "DEMUX_L1.v:75" *)
  wire [7:0] _003_;
  (* src = "DEMUX_L1.v:75" *)
  wire [7:0] _004_;
  (* src = "DEMUX_L1.v:75" *)
  wire [7:0] _005_;
  (* src = "DEMUX_L1.v:29" *)
  wire [7:0] _006_;
  (* src = "DEMUX_L1.v:52" *)
  wire [7:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  (* src = "DEMUX_L1.v:19" *)
  wire [7:0] c;
  (* src = "DEMUX_L1.v:7" *)
  input clk_2f;
  (* src = "DEMUX_L1.v:6" *)
  input clk_f;
  (* src = "DEMUX_L1.v:20" *)
  wire [7:0] d;
  (* src = "DEMUX_L1.v:8" *)
  output [7:0] data_0;
  (* src = "DEMUX_L1.v:2" *)
  input [7:0] data_00;
  (* src = "DEMUX_L1.v:9" *)
  output [7:0] data_1;
  (* src = "DEMUX_L1.v:3" *)
  input [7:0] data_11;
  (* src = "DEMUX_L1.v:10" *)
  output [7:0] data_2;
  (* src = "DEMUX_L1.v:11" *)
  output [7:0] data_3;
  (* src = "DEMUX_L1.v:21" *)
  wire [7:0] e;
  (* src = "DEMUX_L1.v:22" *)
  wire [7:0] f;
  (* src = "DEMUX_L1.v:12" *)
  output valid_0;
  (* src = "DEMUX_L1.v:4" *)
  input valid_00;
  (* src = "DEMUX_L1.v:13" *)
  output valid_1;
  (* src = "DEMUX_L1.v:5" *)
  input valid_11;
  (* src = "DEMUX_L1.v:14" *)
  output valid_2;
  (* src = "DEMUX_L1.v:15" *)
  output valid_3;
  (* src = "DEMUX_L1.v:24" *)
  wire validt_0;
  (* src = "DEMUX_L1.v:25" *)
  wire validt_1;
  (* src = "DEMUX_L1.v:26" *)
  wire validt_2;
  (* src = "DEMUX_L1.v:27" *)
  wire validt_3;
  NOT _160_ (
    .A(validt_1),
    .Y(_026_)
  );
  NOT _161_ (
    .A(validt_3),
    .Y(_027_)
  );
  NOT _162_ (
    .A(validt_2),
    .Y(_028_)
  );
  NOT _163_ (
    .A(validt_0),
    .Y(_029_)
  );
  NOT _164_ (
    .A(valid_00),
    .Y(_030_)
  );
  NOT _165_ (
    .A(valid_11),
    .Y(_031_)
  );
  NOT _166_ (
    .A(clk_2f),
    .Y(_008_)
  );
  NAND _167_ (
    .A(d[1]),
    .B(validt_1),
    .Y(_032_)
  );
  NAND _168_ (
    .A(data_1[1]),
    .B(_026_),
    .Y(_033_)
  );
  NAND _169_ (
    .A(_032_),
    .B(_033_),
    .Y(_003_[1])
  );
  NAND _170_ (
    .A(validt_1),
    .B(d[2]),
    .Y(_034_)
  );
  NAND _171_ (
    .A(_026_),
    .B(data_1[2]),
    .Y(_035_)
  );
  NAND _172_ (
    .A(_034_),
    .B(_035_),
    .Y(_003_[2])
  );
  NAND _173_ (
    .A(validt_1),
    .B(d[3]),
    .Y(_036_)
  );
  NAND _174_ (
    .A(_026_),
    .B(data_1[3]),
    .Y(_037_)
  );
  NAND _175_ (
    .A(_036_),
    .B(_037_),
    .Y(_003_[3])
  );
  NAND _176_ (
    .A(validt_1),
    .B(d[4]),
    .Y(_038_)
  );
  NAND _177_ (
    .A(_026_),
    .B(data_1[4]),
    .Y(_039_)
  );
  NAND _178_ (
    .A(_038_),
    .B(_039_),
    .Y(_003_[4])
  );
  NAND _179_ (
    .A(validt_1),
    .B(d[5]),
    .Y(_040_)
  );
  NAND _180_ (
    .A(_026_),
    .B(data_1[5]),
    .Y(_041_)
  );
  NAND _181_ (
    .A(_040_),
    .B(_041_),
    .Y(_003_[5])
  );
  NAND _182_ (
    .A(validt_1),
    .B(d[6]),
    .Y(_042_)
  );
  NAND _183_ (
    .A(_026_),
    .B(data_1[6]),
    .Y(_043_)
  );
  NAND _184_ (
    .A(_042_),
    .B(_043_),
    .Y(_003_[6])
  );
  NAND _185_ (
    .A(validt_1),
    .B(d[7]),
    .Y(_044_)
  );
  NAND _186_ (
    .A(_026_),
    .B(data_1[7]),
    .Y(_045_)
  );
  NAND _187_ (
    .A(_044_),
    .B(_045_),
    .Y(_003_[7])
  );
  NAND _188_ (
    .A(f[0]),
    .B(validt_3),
    .Y(_046_)
  );
  NAND _189_ (
    .A(data_3[0]),
    .B(_027_),
    .Y(_047_)
  );
  NAND _190_ (
    .A(_046_),
    .B(_047_),
    .Y(_005_[0])
  );
  NAND _191_ (
    .A(validt_3),
    .B(f[1]),
    .Y(_048_)
  );
  NAND _192_ (
    .A(_027_),
    .B(data_3[1]),
    .Y(_049_)
  );
  NAND _193_ (
    .A(_048_),
    .B(_049_),
    .Y(_005_[1])
  );
  NAND _194_ (
    .A(validt_3),
    .B(f[2]),
    .Y(_050_)
  );
  NAND _195_ (
    .A(_027_),
    .B(data_3[2]),
    .Y(_051_)
  );
  NAND _196_ (
    .A(_050_),
    .B(_051_),
    .Y(_005_[2])
  );
  NAND _197_ (
    .A(validt_3),
    .B(f[3]),
    .Y(_052_)
  );
  NAND _198_ (
    .A(_027_),
    .B(data_3[3]),
    .Y(_053_)
  );
  NAND _199_ (
    .A(_052_),
    .B(_053_),
    .Y(_005_[3])
  );
  NAND _200_ (
    .A(validt_3),
    .B(f[4]),
    .Y(_054_)
  );
  NAND _201_ (
    .A(_027_),
    .B(data_3[4]),
    .Y(_055_)
  );
  NAND _202_ (
    .A(_054_),
    .B(_055_),
    .Y(_005_[4])
  );
  NAND _203_ (
    .A(validt_3),
    .B(f[5]),
    .Y(_056_)
  );
  NAND _204_ (
    .A(_027_),
    .B(data_3[5]),
    .Y(_057_)
  );
  NAND _205_ (
    .A(_056_),
    .B(_057_),
    .Y(_005_[5])
  );
  NAND _206_ (
    .A(validt_3),
    .B(f[6]),
    .Y(_058_)
  );
  NAND _207_ (
    .A(_027_),
    .B(data_3[6]),
    .Y(_059_)
  );
  NAND _208_ (
    .A(_058_),
    .B(_059_),
    .Y(_005_[6])
  );
  NAND _209_ (
    .A(validt_3),
    .B(f[7]),
    .Y(_060_)
  );
  NAND _210_ (
    .A(_027_),
    .B(data_3[7]),
    .Y(_061_)
  );
  NAND _211_ (
    .A(_060_),
    .B(_061_),
    .Y(_005_[7])
  );
  NAND _212_ (
    .A(e[0]),
    .B(validt_2),
    .Y(_062_)
  );
  NAND _213_ (
    .A(data_2[0]),
    .B(_028_),
    .Y(_063_)
  );
  NAND _214_ (
    .A(_062_),
    .B(_063_),
    .Y(_004_[0])
  );
  NAND _215_ (
    .A(validt_2),
    .B(e[1]),
    .Y(_064_)
  );
  NAND _216_ (
    .A(_028_),
    .B(data_2[1]),
    .Y(_065_)
  );
  NAND _217_ (
    .A(_064_),
    .B(_065_),
    .Y(_004_[1])
  );
  NAND _218_ (
    .A(validt_2),
    .B(e[2]),
    .Y(_066_)
  );
  NAND _219_ (
    .A(_028_),
    .B(data_2[2]),
    .Y(_067_)
  );
  NAND _220_ (
    .A(_066_),
    .B(_067_),
    .Y(_004_[2])
  );
  NAND _221_ (
    .A(validt_2),
    .B(e[3]),
    .Y(_068_)
  );
  NAND _222_ (
    .A(_028_),
    .B(data_2[3]),
    .Y(_069_)
  );
  NAND _223_ (
    .A(_068_),
    .B(_069_),
    .Y(_004_[3])
  );
  NAND _224_ (
    .A(validt_2),
    .B(e[4]),
    .Y(_070_)
  );
  NAND _225_ (
    .A(_028_),
    .B(data_2[4]),
    .Y(_071_)
  );
  NAND _226_ (
    .A(_070_),
    .B(_071_),
    .Y(_004_[4])
  );
  NAND _227_ (
    .A(validt_2),
    .B(e[5]),
    .Y(_072_)
  );
  NAND _228_ (
    .A(_028_),
    .B(data_2[5]),
    .Y(_073_)
  );
  NAND _229_ (
    .A(_072_),
    .B(_073_),
    .Y(_004_[5])
  );
  NAND _230_ (
    .A(validt_2),
    .B(e[6]),
    .Y(_074_)
  );
  NAND _231_ (
    .A(_028_),
    .B(data_2[6]),
    .Y(_075_)
  );
  NAND _232_ (
    .A(_074_),
    .B(_075_),
    .Y(_004_[6])
  );
  NAND _233_ (
    .A(validt_2),
    .B(e[7]),
    .Y(_076_)
  );
  NAND _234_ (
    .A(_028_),
    .B(data_2[7]),
    .Y(_077_)
  );
  NAND _235_ (
    .A(_076_),
    .B(_077_),
    .Y(_004_[7])
  );
  NAND _236_ (
    .A(c[0]),
    .B(validt_0),
    .Y(_078_)
  );
  NAND _237_ (
    .A(data_0[0]),
    .B(_029_),
    .Y(_079_)
  );
  NAND _238_ (
    .A(_078_),
    .B(_079_),
    .Y(_002_[0])
  );
  NAND _239_ (
    .A(validt_0),
    .B(c[1]),
    .Y(_080_)
  );
  NAND _240_ (
    .A(_029_),
    .B(data_0[1]),
    .Y(_081_)
  );
  NAND _241_ (
    .A(_080_),
    .B(_081_),
    .Y(_002_[1])
  );
  NAND _242_ (
    .A(validt_0),
    .B(c[2]),
    .Y(_082_)
  );
  NAND _243_ (
    .A(_029_),
    .B(data_0[2]),
    .Y(_083_)
  );
  NAND _244_ (
    .A(_082_),
    .B(_083_),
    .Y(_002_[2])
  );
  NAND _245_ (
    .A(validt_0),
    .B(c[3]),
    .Y(_084_)
  );
  NAND _246_ (
    .A(_029_),
    .B(data_0[3]),
    .Y(_085_)
  );
  NAND _247_ (
    .A(_084_),
    .B(_085_),
    .Y(_002_[3])
  );
  NAND _248_ (
    .A(validt_0),
    .B(c[4]),
    .Y(_086_)
  );
  NAND _249_ (
    .A(_029_),
    .B(data_0[4]),
    .Y(_087_)
  );
  NAND _250_ (
    .A(_086_),
    .B(_087_),
    .Y(_002_[4])
  );
  NAND _251_ (
    .A(validt_0),
    .B(c[5]),
    .Y(_088_)
  );
  NAND _252_ (
    .A(_029_),
    .B(data_0[5]),
    .Y(_089_)
  );
  NAND _253_ (
    .A(_088_),
    .B(_089_),
    .Y(_002_[5])
  );
  NAND _254_ (
    .A(validt_0),
    .B(c[6]),
    .Y(_090_)
  );
  NAND _255_ (
    .A(_029_),
    .B(data_0[6]),
    .Y(_091_)
  );
  NAND _256_ (
    .A(_090_),
    .B(_091_),
    .Y(_002_[6])
  );
  NAND _257_ (
    .A(validt_0),
    .B(c[7]),
    .Y(_092_)
  );
  NAND _258_ (
    .A(_029_),
    .B(data_0[7]),
    .Y(_093_)
  );
  NAND _259_ (
    .A(_092_),
    .B(_093_),
    .Y(_002_[7])
  );
  NAND _260_ (
    .A(data_11[0]),
    .B(valid_00),
    .Y(_094_)
  );
  NAND _261_ (
    .A(f[0]),
    .B(_030_),
    .Y(_095_)
  );
  NAND _262_ (
    .A(_094_),
    .B(_095_),
    .Y(_007_[0])
  );
  NAND _263_ (
    .A(valid_00),
    .B(data_11[1]),
    .Y(_096_)
  );
  NAND _264_ (
    .A(f[1]),
    .B(_030_),
    .Y(_097_)
  );
  NAND _265_ (
    .A(_096_),
    .B(_097_),
    .Y(_007_[1])
  );
  NAND _266_ (
    .A(valid_00),
    .B(data_11[2]),
    .Y(_098_)
  );
  NAND _267_ (
    .A(f[2]),
    .B(_030_),
    .Y(_099_)
  );
  NAND _268_ (
    .A(_098_),
    .B(_099_),
    .Y(_007_[2])
  );
  NAND _269_ (
    .A(valid_00),
    .B(data_11[3]),
    .Y(_100_)
  );
  NAND _270_ (
    .A(f[3]),
    .B(_030_),
    .Y(_101_)
  );
  NAND _271_ (
    .A(_100_),
    .B(_101_),
    .Y(_007_[3])
  );
  NAND _272_ (
    .A(valid_00),
    .B(data_11[4]),
    .Y(_102_)
  );
  NAND _273_ (
    .A(f[4]),
    .B(_030_),
    .Y(_103_)
  );
  NAND _274_ (
    .A(_102_),
    .B(_103_),
    .Y(_007_[4])
  );
  NAND _275_ (
    .A(valid_00),
    .B(data_11[5]),
    .Y(_104_)
  );
  NAND _276_ (
    .A(f[5]),
    .B(_030_),
    .Y(_105_)
  );
  NAND _277_ (
    .A(_104_),
    .B(_105_),
    .Y(_007_[5])
  );
  NAND _278_ (
    .A(valid_00),
    .B(data_11[6]),
    .Y(_106_)
  );
  NAND _279_ (
    .A(f[6]),
    .B(_030_),
    .Y(_107_)
  );
  NAND _280_ (
    .A(_106_),
    .B(_107_),
    .Y(_007_[6])
  );
  NAND _281_ (
    .A(valid_00),
    .B(data_11[7]),
    .Y(_108_)
  );
  NAND _282_ (
    .A(f[7]),
    .B(_030_),
    .Y(_109_)
  );
  NAND _283_ (
    .A(_108_),
    .B(_109_),
    .Y(_007_[7])
  );
  NAND _284_ (
    .A(data_00[0]),
    .B(valid_11),
    .Y(_110_)
  );
  NAND _285_ (
    .A(d[0]),
    .B(_031_),
    .Y(_111_)
  );
  NAND _286_ (
    .A(_110_),
    .B(_111_),
    .Y(_001_[0])
  );
  NAND _287_ (
    .A(valid_11),
    .B(data_00[1]),
    .Y(_112_)
  );
  NAND _288_ (
    .A(d[1]),
    .B(_031_),
    .Y(_113_)
  );
  NAND _289_ (
    .A(_112_),
    .B(_113_),
    .Y(_001_[1])
  );
  NAND _290_ (
    .A(valid_11),
    .B(data_00[2]),
    .Y(_114_)
  );
  NAND _291_ (
    .A(d[2]),
    .B(_031_),
    .Y(_115_)
  );
  NAND _292_ (
    .A(_114_),
    .B(_115_),
    .Y(_001_[2])
  );
  NAND _293_ (
    .A(valid_11),
    .B(data_00[3]),
    .Y(_116_)
  );
  NAND _294_ (
    .A(d[3]),
    .B(_031_),
    .Y(_117_)
  );
  NAND _295_ (
    .A(_116_),
    .B(_117_),
    .Y(_001_[3])
  );
  NAND _296_ (
    .A(valid_11),
    .B(data_00[4]),
    .Y(_118_)
  );
  NAND _297_ (
    .A(d[4]),
    .B(_031_),
    .Y(_119_)
  );
  NAND _298_ (
    .A(_118_),
    .B(_119_),
    .Y(_001_[4])
  );
  NAND _299_ (
    .A(valid_11),
    .B(data_00[5]),
    .Y(_120_)
  );
  NAND _300_ (
    .A(d[5]),
    .B(_031_),
    .Y(_121_)
  );
  NAND _301_ (
    .A(_120_),
    .B(_121_),
    .Y(_001_[5])
  );
  NAND _302_ (
    .A(valid_11),
    .B(data_00[6]),
    .Y(_122_)
  );
  NAND _303_ (
    .A(d[6]),
    .B(_031_),
    .Y(_123_)
  );
  NAND _304_ (
    .A(_122_),
    .B(_123_),
    .Y(_001_[6])
  );
  NAND _305_ (
    .A(valid_11),
    .B(data_00[7]),
    .Y(_124_)
  );
  NAND _306_ (
    .A(d[7]),
    .B(_031_),
    .Y(_125_)
  );
  NAND _307_ (
    .A(_124_),
    .B(_125_),
    .Y(_001_[7])
  );
  NAND _308_ (
    .A(data_11[0]),
    .B(valid_11),
    .Y(_126_)
  );
  NAND _309_ (
    .A(e[0]),
    .B(_031_),
    .Y(_127_)
  );
  NAND _310_ (
    .A(_126_),
    .B(_127_),
    .Y(_006_[0])
  );
  NAND _311_ (
    .A(data_11[1]),
    .B(valid_11),
    .Y(_128_)
  );
  NAND _312_ (
    .A(e[1]),
    .B(_031_),
    .Y(_129_)
  );
  NAND _313_ (
    .A(_128_),
    .B(_129_),
    .Y(_006_[1])
  );
  NAND _314_ (
    .A(data_11[2]),
    .B(valid_11),
    .Y(_130_)
  );
  NAND _315_ (
    .A(e[2]),
    .B(_031_),
    .Y(_131_)
  );
  NAND _316_ (
    .A(_130_),
    .B(_131_),
    .Y(_006_[2])
  );
  NAND _317_ (
    .A(data_11[3]),
    .B(valid_11),
    .Y(_132_)
  );
  NAND _318_ (
    .A(e[3]),
    .B(_031_),
    .Y(_133_)
  );
  NAND _319_ (
    .A(_132_),
    .B(_133_),
    .Y(_006_[3])
  );
  NAND _320_ (
    .A(data_11[4]),
    .B(valid_11),
    .Y(_134_)
  );
  NAND _321_ (
    .A(e[4]),
    .B(_031_),
    .Y(_135_)
  );
  NAND _322_ (
    .A(_134_),
    .B(_135_),
    .Y(_006_[4])
  );
  NAND _323_ (
    .A(data_11[5]),
    .B(valid_11),
    .Y(_136_)
  );
  NAND _324_ (
    .A(e[5]),
    .B(_031_),
    .Y(_137_)
  );
  NAND _325_ (
    .A(_136_),
    .B(_137_),
    .Y(_006_[5])
  );
  NAND _326_ (
    .A(data_11[6]),
    .B(valid_11),
    .Y(_138_)
  );
  NAND _327_ (
    .A(e[6]),
    .B(_031_),
    .Y(_139_)
  );
  NAND _328_ (
    .A(_138_),
    .B(_139_),
    .Y(_006_[6])
  );
  NAND _329_ (
    .A(data_11[7]),
    .B(valid_11),
    .Y(_140_)
  );
  NAND _330_ (
    .A(e[7]),
    .B(_031_),
    .Y(_141_)
  );
  NAND _331_ (
    .A(_140_),
    .B(_141_),
    .Y(_006_[7])
  );
  NAND _332_ (
    .A(valid_00),
    .B(data_00[0]),
    .Y(_142_)
  );
  NAND _333_ (
    .A(c[0]),
    .B(_030_),
    .Y(_143_)
  );
  NAND _334_ (
    .A(_142_),
    .B(_143_),
    .Y(_000_[0])
  );
  NAND _335_ (
    .A(valid_00),
    .B(data_00[1]),
    .Y(_144_)
  );
  NAND _336_ (
    .A(c[1]),
    .B(_030_),
    .Y(_145_)
  );
  NAND _337_ (
    .A(_144_),
    .B(_145_),
    .Y(_000_[1])
  );
  NAND _338_ (
    .A(valid_00),
    .B(data_00[2]),
    .Y(_146_)
  );
  NAND _339_ (
    .A(c[2]),
    .B(_030_),
    .Y(_147_)
  );
  NAND _340_ (
    .A(_146_),
    .B(_147_),
    .Y(_000_[2])
  );
  NAND _341_ (
    .A(valid_00),
    .B(data_00[3]),
    .Y(_148_)
  );
  NAND _342_ (
    .A(c[3]),
    .B(_030_),
    .Y(_149_)
  );
  NAND _343_ (
    .A(_148_),
    .B(_149_),
    .Y(_000_[3])
  );
  NAND _344_ (
    .A(valid_00),
    .B(data_00[4]),
    .Y(_150_)
  );
  NAND _345_ (
    .A(c[4]),
    .B(_030_),
    .Y(_151_)
  );
  NAND _346_ (
    .A(_150_),
    .B(_151_),
    .Y(_000_[4])
  );
  NAND _347_ (
    .A(valid_00),
    .B(data_00[5]),
    .Y(_152_)
  );
  NAND _348_ (
    .A(c[5]),
    .B(_030_),
    .Y(_153_)
  );
  NAND _349_ (
    .A(_152_),
    .B(_153_),
    .Y(_000_[5])
  );
  NAND _350_ (
    .A(valid_00),
    .B(data_00[6]),
    .Y(_154_)
  );
  NAND _351_ (
    .A(c[6]),
    .B(_030_),
    .Y(_155_)
  );
  NAND _352_ (
    .A(_154_),
    .B(_155_),
    .Y(_000_[6])
  );
  NAND _353_ (
    .A(valid_00),
    .B(data_00[7]),
    .Y(_156_)
  );
  NAND _354_ (
    .A(c[7]),
    .B(_030_),
    .Y(_157_)
  );
  NAND _355_ (
    .A(_156_),
    .B(_157_),
    .Y(_000_[7])
  );
  NAND _356_ (
    .A(validt_1),
    .B(d[0]),
    .Y(_158_)
  );
  NAND _357_ (
    .A(_026_),
    .B(data_1[0]),
    .Y(_159_)
  );
  NAND _358_ (
    .A(_158_),
    .B(_159_),
    .Y(_003_[0])
  );
  NOT _359_ (
    .A(clk_2f),
    .Y(_009_)
  );
  NOT _360_ (
    .A(clk_2f),
    .Y(_010_)
  );
  NOT _361_ (
    .A(clk_2f),
    .Y(_011_)
  );
  NOT _362_ (
    .A(clk_2f),
    .Y(_012_)
  );
  NOT _363_ (
    .A(clk_2f),
    .Y(_013_)
  );
  NOT _364_ (
    .A(clk_2f),
    .Y(_014_)
  );
  NOT _365_ (
    .A(clk_2f),
    .Y(_015_)
  );
  NOT _366_ (
    .A(clk_2f),
    .Y(_016_)
  );
  NOT _367_ (
    .A(clk_2f),
    .Y(_017_)
  );
  NOT _368_ (
    .A(clk_2f),
    .Y(_018_)
  );
  NOT _369_ (
    .A(clk_2f),
    .Y(_019_)
  );
  NOT _370_ (
    .A(clk_2f),
    .Y(_020_)
  );
  NOT _371_ (
    .A(clk_2f),
    .Y(_021_)
  );
  NOT _372_ (
    .A(clk_2f),
    .Y(_022_)
  );
  NOT _373_ (
    .A(clk_2f),
    .Y(_023_)
  );
  NOT _374_ (
    .A(clk_2f),
    .Y(_024_)
  );
  NOT _375_ (
    .A(clk_2f),
    .Y(_025_)
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _376_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(data_0[0])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _377_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(data_0[1])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _378_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(data_0[2])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _379_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(data_0[3])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _380_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(data_0[4])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _381_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(data_0[5])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _382_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(data_0[6])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _383_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(data_0[7])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _384_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(data_1[0])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _385_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(data_1[1])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _386_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(data_1[2])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _387_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(data_1[3])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _388_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(data_1[4])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _389_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(data_1[5])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _390_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(data_1[6])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _391_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(data_1[7])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _392_ (
    .C(clk_f),
    .D(_004_[0]),
    .Q(data_2[0])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _393_ (
    .C(clk_f),
    .D(_004_[1]),
    .Q(data_2[1])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _394_ (
    .C(clk_f),
    .D(_004_[2]),
    .Q(data_2[2])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _395_ (
    .C(clk_f),
    .D(_004_[3]),
    .Q(data_2[3])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _396_ (
    .C(clk_f),
    .D(_004_[4]),
    .Q(data_2[4])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _397_ (
    .C(clk_f),
    .D(_004_[5]),
    .Q(data_2[5])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _398_ (
    .C(clk_f),
    .D(_004_[6]),
    .Q(data_2[6])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _399_ (
    .C(clk_f),
    .D(_004_[7]),
    .Q(data_2[7])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _400_ (
    .C(clk_f),
    .D(_005_[0]),
    .Q(data_3[0])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _401_ (
    .C(clk_f),
    .D(_005_[1]),
    .Q(data_3[1])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _402_ (
    .C(clk_f),
    .D(_005_[2]),
    .Q(data_3[2])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _403_ (
    .C(clk_f),
    .D(_005_[3]),
    .Q(data_3[3])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _404_ (
    .C(clk_f),
    .D(_005_[4]),
    .Q(data_3[4])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _405_ (
    .C(clk_f),
    .D(_005_[5]),
    .Q(data_3[5])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _406_ (
    .C(clk_f),
    .D(_005_[6]),
    .Q(data_3[6])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _407_ (
    .C(clk_f),
    .D(_005_[7]),
    .Q(data_3[7])
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _408_ (
    .C(clk_f),
    .D(validt_0),
    .Q(valid_0)
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _409_ (
    .C(clk_f),
    .D(validt_1),
    .Q(valid_1)
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _410_ (
    .C(clk_f),
    .D(validt_2),
    .Q(valid_2)
  );
  (* src = "DEMUX_L1.v:75" *)
  DFF _411_ (
    .C(clk_f),
    .D(validt_3),
    .Q(valid_3)
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _412_ (
    .C(_008_),
    .D(_001_[0]),
    .Q(d[0])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _413_ (
    .C(_009_),
    .D(_001_[1]),
    .Q(d[1])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _414_ (
    .C(_010_),
    .D(_001_[2]),
    .Q(d[2])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _415_ (
    .C(_011_),
    .D(_001_[3]),
    .Q(d[3])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _416_ (
    .C(_012_),
    .D(_001_[4]),
    .Q(d[4])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _417_ (
    .C(_013_),
    .D(_001_[5]),
    .Q(d[5])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _418_ (
    .C(_014_),
    .D(_001_[6]),
    .Q(d[6])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _419_ (
    .C(_015_),
    .D(_001_[7]),
    .Q(d[7])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _420_ (
    .C(_016_),
    .D(_007_[0]),
    .Q(f[0])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _421_ (
    .C(_017_),
    .D(_007_[1]),
    .Q(f[1])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _422_ (
    .C(_018_),
    .D(_007_[2]),
    .Q(f[2])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _423_ (
    .C(_019_),
    .D(_007_[3]),
    .Q(f[3])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _424_ (
    .C(_020_),
    .D(_007_[4]),
    .Q(f[4])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _425_ (
    .C(_021_),
    .D(_007_[5]),
    .Q(f[5])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _426_ (
    .C(_022_),
    .D(_007_[6]),
    .Q(f[6])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _427_ (
    .C(_023_),
    .D(_007_[7]),
    .Q(f[7])
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _428_ (
    .C(_024_),
    .D(valid_11),
    .Q(validt_1)
  );
  (* src = "DEMUX_L1.v:52" *)
  DFF _429_ (
    .C(_025_),
    .D(valid_00),
    .Q(validt_3)
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _430_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(c[0])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _431_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(c[1])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _432_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(c[2])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _433_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(c[3])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _434_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(c[4])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _435_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(c[5])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _436_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(c[6])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _437_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(c[7])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _438_ (
    .C(clk_2f),
    .D(_006_[0]),
    .Q(e[0])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _439_ (
    .C(clk_2f),
    .D(_006_[1]),
    .Q(e[1])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _440_ (
    .C(clk_2f),
    .D(_006_[2]),
    .Q(e[2])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _441_ (
    .C(clk_2f),
    .D(_006_[3]),
    .Q(e[3])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _442_ (
    .C(clk_2f),
    .D(_006_[4]),
    .Q(e[4])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _443_ (
    .C(clk_2f),
    .D(_006_[5]),
    .Q(e[5])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _444_ (
    .C(clk_2f),
    .D(_006_[6]),
    .Q(e[6])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _445_ (
    .C(clk_2f),
    .D(_006_[7]),
    .Q(e[7])
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _446_ (
    .C(clk_2f),
    .D(valid_00),
    .Q(validt_0)
  );
  (* src = "DEMUX_L1.v:29" *)
  DFF _447_ (
    .C(clk_2f),
    .D(valid_11),
    .Q(validt_2)
  );
endmodule

(* src = "DEMUX_L2.v:1" *)
module DEMUX_L2_synth(data_000, valid_000, clk_4f, clk_2f, data_00, data_11, valid_00, valid_11);
  (* src = "DEMUX_L2.v:20" *)
  wire [7:0] _000_;
  (* src = "DEMUX_L2.v:33" *)
  wire [7:0] _001_;
  (* src = "DEMUX_L2.v:45" *)
  wire [7:0] _002_;
  (* src = "DEMUX_L2.v:59" *)
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "DEMUX_L2.v:13" *)
  wire [7:0] a;
  (* src = "DEMUX_L2.v:14" *)
  wire [7:0] b;
  (* src = "DEMUX_L2.v:6" *)
  input clk_2f;
  (* src = "DEMUX_L2.v:5" *)
  input clk_4f;
  (* src = "DEMUX_L2.v:7" *)
  output [7:0] data_00;
  (* src = "DEMUX_L2.v:2" *)
  input [7:0] data_000;
  (* src = "DEMUX_L2.v:8" *)
  output [7:0] data_11;
  (* src = "DEMUX_L2.v:9" *)
  output valid_00;
  (* src = "DEMUX_L2.v:3" *)
  input valid_000;
  (* src = "DEMUX_L2.v:10" *)
  output valid_11;
  (* src = "DEMUX_L2.v:15" *)
  wire validt_00;
  (* src = "DEMUX_L2.v:16" *)
  wire validt_11;
  NOT _072_ (
    .A(validt_11),
    .Y(_062_)
  );
  NOT _073_ (
    .A(validt_00),
    .Y(_063_)
  );
  NOT _074_ (
    .A(valid_000),
    .Y(_064_)
  );
  NOT _075_ (
    .A(clk_4f),
    .Y(_004_)
  );
  NAND _076_ (
    .A(b[1]),
    .B(validt_11),
    .Y(_065_)
  );
  NAND _077_ (
    .A(data_11[1]),
    .B(_062_),
    .Y(_066_)
  );
  NAND _078_ (
    .A(_065_),
    .B(_066_),
    .Y(_003_[1])
  );
  NAND _079_ (
    .A(validt_11),
    .B(b[2]),
    .Y(_067_)
  );
  NAND _080_ (
    .A(_062_),
    .B(data_11[2]),
    .Y(_068_)
  );
  NAND _081_ (
    .A(_067_),
    .B(_068_),
    .Y(_003_[2])
  );
  NAND _082_ (
    .A(validt_11),
    .B(b[3]),
    .Y(_069_)
  );
  NAND _083_ (
    .A(_062_),
    .B(data_11[3]),
    .Y(_070_)
  );
  NAND _084_ (
    .A(_069_),
    .B(_070_),
    .Y(_003_[3])
  );
  NAND _085_ (
    .A(validt_11),
    .B(b[4]),
    .Y(_071_)
  );
  NAND _086_ (
    .A(_062_),
    .B(data_11[4]),
    .Y(_013_)
  );
  NAND _087_ (
    .A(_071_),
    .B(_013_),
    .Y(_003_[4])
  );
  NAND _088_ (
    .A(validt_11),
    .B(b[5]),
    .Y(_014_)
  );
  NAND _089_ (
    .A(_062_),
    .B(data_11[5]),
    .Y(_015_)
  );
  NAND _090_ (
    .A(_014_),
    .B(_015_),
    .Y(_003_[5])
  );
  NAND _091_ (
    .A(validt_11),
    .B(b[6]),
    .Y(_016_)
  );
  NAND _092_ (
    .A(_062_),
    .B(data_11[6]),
    .Y(_017_)
  );
  NAND _093_ (
    .A(_016_),
    .B(_017_),
    .Y(_003_[6])
  );
  NAND _094_ (
    .A(validt_11),
    .B(b[7]),
    .Y(_018_)
  );
  NAND _095_ (
    .A(_062_),
    .B(data_11[7]),
    .Y(_019_)
  );
  NAND _096_ (
    .A(_018_),
    .B(_019_),
    .Y(_003_[7])
  );
  NAND _097_ (
    .A(a[0]),
    .B(validt_00),
    .Y(_020_)
  );
  NAND _098_ (
    .A(data_00[0]),
    .B(_063_),
    .Y(_021_)
  );
  NAND _099_ (
    .A(_020_),
    .B(_021_),
    .Y(_002_[0])
  );
  NAND _100_ (
    .A(validt_00),
    .B(a[1]),
    .Y(_022_)
  );
  NAND _101_ (
    .A(_063_),
    .B(data_00[1]),
    .Y(_023_)
  );
  NAND _102_ (
    .A(_022_),
    .B(_023_),
    .Y(_002_[1])
  );
  NAND _103_ (
    .A(validt_00),
    .B(a[2]),
    .Y(_024_)
  );
  NAND _104_ (
    .A(_063_),
    .B(data_00[2]),
    .Y(_025_)
  );
  NAND _105_ (
    .A(_024_),
    .B(_025_),
    .Y(_002_[2])
  );
  NAND _106_ (
    .A(validt_00),
    .B(a[3]),
    .Y(_026_)
  );
  NAND _107_ (
    .A(_063_),
    .B(data_00[3]),
    .Y(_027_)
  );
  NAND _108_ (
    .A(_026_),
    .B(_027_),
    .Y(_002_[3])
  );
  NAND _109_ (
    .A(validt_00),
    .B(a[4]),
    .Y(_028_)
  );
  NAND _110_ (
    .A(_063_),
    .B(data_00[4]),
    .Y(_029_)
  );
  NAND _111_ (
    .A(_028_),
    .B(_029_),
    .Y(_002_[4])
  );
  NAND _112_ (
    .A(validt_00),
    .B(a[5]),
    .Y(_030_)
  );
  NAND _113_ (
    .A(_063_),
    .B(data_00[5]),
    .Y(_031_)
  );
  NAND _114_ (
    .A(_030_),
    .B(_031_),
    .Y(_002_[5])
  );
  NAND _115_ (
    .A(validt_00),
    .B(a[6]),
    .Y(_032_)
  );
  NAND _116_ (
    .A(_063_),
    .B(data_00[6]),
    .Y(_033_)
  );
  NAND _117_ (
    .A(_032_),
    .B(_033_),
    .Y(_002_[6])
  );
  NAND _118_ (
    .A(validt_00),
    .B(a[7]),
    .Y(_034_)
  );
  NAND _119_ (
    .A(_063_),
    .B(data_00[7]),
    .Y(_035_)
  );
  NAND _120_ (
    .A(_034_),
    .B(_035_),
    .Y(_002_[7])
  );
  NAND _121_ (
    .A(b[0]),
    .B(_064_),
    .Y(_036_)
  );
  NAND _122_ (
    .A(data_000[0]),
    .B(valid_000),
    .Y(_037_)
  );
  NAND _123_ (
    .A(_036_),
    .B(_037_),
    .Y(_001_[0])
  );
  NAND _124_ (
    .A(b[1]),
    .B(_064_),
    .Y(_038_)
  );
  NAND _125_ (
    .A(valid_000),
    .B(data_000[1]),
    .Y(_039_)
  );
  NAND _126_ (
    .A(_038_),
    .B(_039_),
    .Y(_001_[1])
  );
  NAND _127_ (
    .A(b[2]),
    .B(_064_),
    .Y(_040_)
  );
  NAND _128_ (
    .A(valid_000),
    .B(data_000[2]),
    .Y(_041_)
  );
  NAND _129_ (
    .A(_040_),
    .B(_041_),
    .Y(_001_[2])
  );
  NAND _130_ (
    .A(b[3]),
    .B(_064_),
    .Y(_042_)
  );
  NAND _131_ (
    .A(valid_000),
    .B(data_000[3]),
    .Y(_043_)
  );
  NAND _132_ (
    .A(_042_),
    .B(_043_),
    .Y(_001_[3])
  );
  NAND _133_ (
    .A(b[4]),
    .B(_064_),
    .Y(_044_)
  );
  NAND _134_ (
    .A(valid_000),
    .B(data_000[4]),
    .Y(_045_)
  );
  NAND _135_ (
    .A(_044_),
    .B(_045_),
    .Y(_001_[4])
  );
  NAND _136_ (
    .A(b[5]),
    .B(_064_),
    .Y(_046_)
  );
  NAND _137_ (
    .A(valid_000),
    .B(data_000[5]),
    .Y(_047_)
  );
  NAND _138_ (
    .A(_046_),
    .B(_047_),
    .Y(_001_[5])
  );
  NAND _139_ (
    .A(b[6]),
    .B(_064_),
    .Y(_048_)
  );
  NAND _140_ (
    .A(valid_000),
    .B(data_000[6]),
    .Y(_049_)
  );
  NAND _141_ (
    .A(_048_),
    .B(_049_),
    .Y(_001_[6])
  );
  NAND _142_ (
    .A(b[7]),
    .B(_064_),
    .Y(_050_)
  );
  NAND _143_ (
    .A(valid_000),
    .B(data_000[7]),
    .Y(_051_)
  );
  NAND _144_ (
    .A(_050_),
    .B(_051_),
    .Y(_001_[7])
  );
  NAND _145_ (
    .A(a[0]),
    .B(_064_),
    .Y(_052_)
  );
  NAND _146_ (
    .A(_037_),
    .B(_052_),
    .Y(_000_[0])
  );
  NAND _147_ (
    .A(a[1]),
    .B(_064_),
    .Y(_053_)
  );
  NAND _148_ (
    .A(_039_),
    .B(_053_),
    .Y(_000_[1])
  );
  NAND _149_ (
    .A(a[2]),
    .B(_064_),
    .Y(_054_)
  );
  NAND _150_ (
    .A(_041_),
    .B(_054_),
    .Y(_000_[2])
  );
  NAND _151_ (
    .A(a[3]),
    .B(_064_),
    .Y(_055_)
  );
  NAND _152_ (
    .A(_043_),
    .B(_055_),
    .Y(_000_[3])
  );
  NAND _153_ (
    .A(a[4]),
    .B(_064_),
    .Y(_056_)
  );
  NAND _154_ (
    .A(_045_),
    .B(_056_),
    .Y(_000_[4])
  );
  NAND _155_ (
    .A(a[5]),
    .B(_064_),
    .Y(_057_)
  );
  NAND _156_ (
    .A(_047_),
    .B(_057_),
    .Y(_000_[5])
  );
  NAND _157_ (
    .A(a[6]),
    .B(_064_),
    .Y(_058_)
  );
  NAND _158_ (
    .A(_049_),
    .B(_058_),
    .Y(_000_[6])
  );
  NAND _159_ (
    .A(a[7]),
    .B(_064_),
    .Y(_059_)
  );
  NAND _160_ (
    .A(_051_),
    .B(_059_),
    .Y(_000_[7])
  );
  NAND _161_ (
    .A(validt_11),
    .B(b[0]),
    .Y(_060_)
  );
  NAND _162_ (
    .A(_062_),
    .B(data_11[0]),
    .Y(_061_)
  );
  NAND _163_ (
    .A(_060_),
    .B(_061_),
    .Y(_003_[0])
  );
  NOT _164_ (
    .A(clk_4f),
    .Y(_005_)
  );
  NOT _165_ (
    .A(clk_4f),
    .Y(_006_)
  );
  NOT _166_ (
    .A(clk_4f),
    .Y(_007_)
  );
  NOT _167_ (
    .A(clk_4f),
    .Y(_008_)
  );
  NOT _168_ (
    .A(clk_4f),
    .Y(_009_)
  );
  NOT _169_ (
    .A(clk_4f),
    .Y(_010_)
  );
  NOT _170_ (
    .A(clk_4f),
    .Y(_011_)
  );
  NOT _171_ (
    .A(clk_4f),
    .Y(_012_)
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _172_ (
    .C(clk_2f),
    .D(_003_[0]),
    .Q(data_11[0])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _173_ (
    .C(clk_2f),
    .D(_003_[1]),
    .Q(data_11[1])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _174_ (
    .C(clk_2f),
    .D(_003_[2]),
    .Q(data_11[2])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _175_ (
    .C(clk_2f),
    .D(_003_[3]),
    .Q(data_11[3])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _176_ (
    .C(clk_2f),
    .D(_003_[4]),
    .Q(data_11[4])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _177_ (
    .C(clk_2f),
    .D(_003_[5]),
    .Q(data_11[5])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _178_ (
    .C(clk_2f),
    .D(_003_[6]),
    .Q(data_11[6])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _179_ (
    .C(clk_2f),
    .D(_003_[7]),
    .Q(data_11[7])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _180_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(a[0])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _181_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(a[1])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _182_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(a[2])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _183_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(a[3])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _184_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(a[4])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _185_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(a[5])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _186_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(a[6])
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _187_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(a[7])
  );
  (* src = "DEMUX_L2.v:59" *)
  DFF _188_ (
    .C(clk_2f),
    .D(validt_11),
    .Q(valid_11)
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _189_ (
    .C(clk_2f),
    .D(_002_[0]),
    .Q(data_00[0])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _190_ (
    .C(clk_2f),
    .D(_002_[1]),
    .Q(data_00[1])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _191_ (
    .C(clk_2f),
    .D(_002_[2]),
    .Q(data_00[2])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _192_ (
    .C(clk_2f),
    .D(_002_[3]),
    .Q(data_00[3])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _193_ (
    .C(clk_2f),
    .D(_002_[4]),
    .Q(data_00[4])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _194_ (
    .C(clk_2f),
    .D(_002_[5]),
    .Q(data_00[5])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _195_ (
    .C(clk_2f),
    .D(_002_[6]),
    .Q(data_00[6])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _196_ (
    .C(clk_2f),
    .D(_002_[7]),
    .Q(data_00[7])
  );
  (* src = "DEMUX_L2.v:45" *)
  DFF _197_ (
    .C(clk_2f),
    .D(validt_00),
    .Q(valid_00)
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _198_ (
    .C(_004_),
    .D(_001_[0]),
    .Q(b[0])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _199_ (
    .C(_005_),
    .D(_001_[1]),
    .Q(b[1])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _200_ (
    .C(_006_),
    .D(_001_[2]),
    .Q(b[2])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _201_ (
    .C(_007_),
    .D(_001_[3]),
    .Q(b[3])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _202_ (
    .C(_008_),
    .D(_001_[4]),
    .Q(b[4])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _203_ (
    .C(_009_),
    .D(_001_[5]),
    .Q(b[5])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _204_ (
    .C(_010_),
    .D(_001_[6]),
    .Q(b[6])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _205_ (
    .C(_011_),
    .D(_001_[7]),
    .Q(b[7])
  );
  (* src = "DEMUX_L2.v:33" *)
  DFF _206_ (
    .C(_012_),
    .D(valid_000),
    .Q(validt_11)
  );
  (* src = "DEMUX_L2.v:20" *)
  DFF _207_ (
    .C(clk_4f),
    .D(valid_000),
    .Q(validt_00)
  );
endmodule
