/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "MUX1_L1.v:1" *)
module MUX1_L1_synth(data_00, valid_00, reset_L, clk_f, clk_2f, data_0, data_1, valid_0, valid_1);
  (* src = "MUX1_L1.v:44" *)
  wire [7:0] _00_;
  (* src = "MUX1_L1.v:44" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  (* src = "MUX1_L1.v:6" *)
  input clk_2f;
  (* src = "MUX1_L1.v:5" *)
  input clk_f;
  (* src = "MUX1_L1.v:7" *)
  input [7:0] data_0;
  (* src = "MUX1_L1.v:2" *)
  output [7:0] data_00;
  (* src = "MUX1_L1.v:8" *)
  input [7:0] data_1;
  (* src = "MUX1_L1.v:4" *)
  input reset_L;
  (* src = "MUX1_L1.v:9" *)
  input valid_0;
  (* src = "MUX1_L1.v:3" *)
  output valid_00;
  (* src = "MUX1_L1.v:10" *)
  input valid_1;
  NOT _38_ (
    .A(data_0[0]),
    .Y(_02_)
  );
  NOT _39_ (
    .A(data_0[1]),
    .Y(_03_)
  );
  NOT _40_ (
    .A(data_0[2]),
    .Y(_04_)
  );
  NOT _41_ (
    .A(data_0[3]),
    .Y(_05_)
  );
  NOT _42_ (
    .A(data_0[4]),
    .Y(_06_)
  );
  NOT _43_ (
    .A(data_0[5]),
    .Y(_07_)
  );
  NOT _44_ (
    .A(data_0[6]),
    .Y(_08_)
  );
  NOT _45_ (
    .A(data_0[7]),
    .Y(_09_)
  );
  NOT _46_ (
    .A(valid_0),
    .Y(_10_)
  );
  NOR _47_ (
    .A(clk_f),
    .B(valid_1),
    .Y(_11_)
  );
  NAND _48_ (
    .A(clk_f),
    .B(_10_),
    .Y(_12_)
  );
  NAND _49_ (
    .A(reset_L),
    .B(_12_),
    .Y(_13_)
  );
  NOR _50_ (
    .A(_11_),
    .B(_13_),
    .Y(_01_)
  );
  NOR _51_ (
    .A(data_1[0]),
    .B(clk_f),
    .Y(_14_)
  );
  NAND _52_ (
    .A(_02_),
    .B(clk_f),
    .Y(_15_)
  );
  NAND _53_ (
    .A(reset_L),
    .B(_15_),
    .Y(_16_)
  );
  NOR _54_ (
    .A(_14_),
    .B(_16_),
    .Y(_00_[0])
  );
  NOR _55_ (
    .A(clk_f),
    .B(data_1[1]),
    .Y(_17_)
  );
  NAND _56_ (
    .A(clk_f),
    .B(_03_),
    .Y(_18_)
  );
  NAND _57_ (
    .A(reset_L),
    .B(_18_),
    .Y(_19_)
  );
  NOR _58_ (
    .A(_17_),
    .B(_19_),
    .Y(_00_[1])
  );
  NOR _59_ (
    .A(clk_f),
    .B(data_1[2]),
    .Y(_20_)
  );
  NAND _60_ (
    .A(clk_f),
    .B(_04_),
    .Y(_21_)
  );
  NAND _61_ (
    .A(reset_L),
    .B(_21_),
    .Y(_22_)
  );
  NOR _62_ (
    .A(_20_),
    .B(_22_),
    .Y(_00_[2])
  );
  NOR _63_ (
    .A(clk_f),
    .B(data_1[3]),
    .Y(_23_)
  );
  NAND _64_ (
    .A(clk_f),
    .B(_05_),
    .Y(_24_)
  );
  NAND _65_ (
    .A(reset_L),
    .B(_24_),
    .Y(_25_)
  );
  NOR _66_ (
    .A(_23_),
    .B(_25_),
    .Y(_00_[3])
  );
  NOR _67_ (
    .A(clk_f),
    .B(data_1[4]),
    .Y(_26_)
  );
  NAND _68_ (
    .A(clk_f),
    .B(_06_),
    .Y(_27_)
  );
  NAND _69_ (
    .A(reset_L),
    .B(_27_),
    .Y(_28_)
  );
  NOR _70_ (
    .A(_26_),
    .B(_28_),
    .Y(_00_[4])
  );
  NOR _71_ (
    .A(clk_f),
    .B(data_1[5]),
    .Y(_29_)
  );
  NAND _72_ (
    .A(clk_f),
    .B(_07_),
    .Y(_30_)
  );
  NAND _73_ (
    .A(reset_L),
    .B(_30_),
    .Y(_31_)
  );
  NOR _74_ (
    .A(_29_),
    .B(_31_),
    .Y(_00_[5])
  );
  NOR _75_ (
    .A(clk_f),
    .B(data_1[6]),
    .Y(_32_)
  );
  NAND _76_ (
    .A(clk_f),
    .B(_08_),
    .Y(_33_)
  );
  NAND _77_ (
    .A(reset_L),
    .B(_33_),
    .Y(_34_)
  );
  NOR _78_ (
    .A(_32_),
    .B(_34_),
    .Y(_00_[6])
  );
  NOR _79_ (
    .A(clk_f),
    .B(data_1[7]),
    .Y(_35_)
  );
  NAND _80_ (
    .A(clk_f),
    .B(_09_),
    .Y(_36_)
  );
  NAND _81_ (
    .A(reset_L),
    .B(_36_),
    .Y(_37_)
  );
  NOR _82_ (
    .A(_35_),
    .B(_37_),
    .Y(_00_[7])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _83_ (
    .C(clk_2f),
    .D(_00_[0]),
    .Q(data_00[0])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _84_ (
    .C(clk_2f),
    .D(_00_[1]),
    .Q(data_00[1])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _85_ (
    .C(clk_2f),
    .D(_00_[2]),
    .Q(data_00[2])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _86_ (
    .C(clk_2f),
    .D(_00_[3]),
    .Q(data_00[3])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _87_ (
    .C(clk_2f),
    .D(_00_[4]),
    .Q(data_00[4])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _88_ (
    .C(clk_2f),
    .D(_00_[5]),
    .Q(data_00[5])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _89_ (
    .C(clk_2f),
    .D(_00_[6]),
    .Q(data_00[6])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _90_ (
    .C(clk_2f),
    .D(_00_[7]),
    .Q(data_00[7])
  );
  (* src = "MUX1_L1.v:44" *)
  DFF _91_ (
    .C(clk_2f),
    .D(_01_),
    .Q(valid_00)
  );
endmodule

(* top =  1  *)
(* src = "MUXES.v:4" *)
module MUXES_synth(data_000, valid_000, reset_L, clk_f, clk_2f, clk_4f, data_0, data_1, data_2, data_3, valid_0, valid_1, valid_2, valid_3);
  (* src = "MUXES.v:9" *)
  input clk_2f;
  (* src = "MUXES.v:10" *)
  input clk_4f;
  (* src = "MUXES.v:8" *)
  input clk_f;
  (* src = "MUXES.v:11" *)
  input [7:0] data_0;
  (* src = "MUXES.v:5" *)
  output [7:0] data_000;
  (* src = "MUXES.v:12" *)
  input [7:0] data_1;
  (* src = "MUXES.v:13" *)
  input [7:0] data_2;
  (* src = "MUXES.v:14" *)
  input [7:0] data_3;
  (* src = "MUXES.v:20" *)
  wire [7:0] data__00;
  (* src = "MUXES.v:20" *)
  wire [7:0] data__11;
  (* src = "MUXES.v:7" *)
  input reset_L;
  (* src = "MUXES.v:15" *)
  input valid_0;
  (* src = "MUXES.v:6" *)
  output valid_000;
  (* src = "MUXES.v:16" *)
  input valid_1;
  (* src = "MUXES.v:17" *)
  input valid_2;
  (* src = "MUXES.v:18" *)
  input valid_3;
  (* src = "MUXES.v:21" *)
  wire valid__00;
  (* src = "MUXES.v:21" *)
  wire valid__11;
  (* module_not_derived = 32'd1 *)
  (* src = "MUXES.v:24" *)
  MUX1_L1_synth MUX1 (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_0(data_0),
    .data_00(data__00),
    .data_1(data_1),
    .reset_L(reset_L),
    .valid_0(valid_0),
    .valid_00(valid__00),
    .valid_1(valid_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "MUXES.v:34" *)
  MUX1_L1_synth MUX2 (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_0(data_2),
    .data_00(data__11),
    .data_1(data_3),
    .reset_L(reset_L),
    .valid_0(valid_2),
    .valid_00(valid__11),
    .valid_1(valid_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "MUXES.v:44" *)
  MUX_L2_synth MUX3 (
    .clk_2f(clk_2f),
    .clk_4f(clk_4f),
    .data_00(data__00),
    .data_000(data_000),
    .data_11(data__11),
    .reset_L(reset_L),
    .valid_00(valid__00),
    .valid_000(valid_000),
    .valid_11(valid__11)
  );
endmodule

(* src = "MUX_L2.v:1" *)
module MUX_L2_synth(data_000, valid_000, reset_L, clk_2f, clk_4f, data_00, data_11, valid_00, valid_11);
  (* src = "MUX_L2.v:41" *)
  wire [7:0] _00_;
  (* src = "MUX_L2.v:41" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  (* src = "MUX_L2.v:5" *)
  input clk_2f;
  (* src = "MUX_L2.v:6" *)
  input clk_4f;
  (* src = "MUX_L2.v:7" *)
  input [7:0] data_00;
  (* src = "MUX_L2.v:2" *)
  output [7:0] data_000;
  (* src = "MUX_L2.v:8" *)
  input [7:0] data_11;
  (* src = "MUX_L2.v:4" *)
  input reset_L;
  (* src = "MUX_L2.v:9" *)
  input valid_00;
  (* src = "MUX_L2.v:3" *)
  output valid_000;
  (* src = "MUX_L2.v:10" *)
  input valid_11;
  NOT _38_ (
    .A(valid_00),
    .Y(_02_)
  );
  NOT _39_ (
    .A(data_00[0]),
    .Y(_03_)
  );
  NOT _40_ (
    .A(data_00[1]),
    .Y(_04_)
  );
  NOT _41_ (
    .A(data_00[2]),
    .Y(_05_)
  );
  NOT _42_ (
    .A(data_00[3]),
    .Y(_06_)
  );
  NOT _43_ (
    .A(data_00[4]),
    .Y(_07_)
  );
  NOT _44_ (
    .A(data_00[5]),
    .Y(_08_)
  );
  NOT _45_ (
    .A(data_00[6]),
    .Y(_09_)
  );
  NOT _46_ (
    .A(data_00[7]),
    .Y(_10_)
  );
  NOR _47_ (
    .A(clk_2f),
    .B(data_11[1]),
    .Y(_11_)
  );
  NAND _48_ (
    .A(clk_2f),
    .B(_04_),
    .Y(_12_)
  );
  NAND _49_ (
    .A(reset_L),
    .B(_12_),
    .Y(_13_)
  );
  NOR _50_ (
    .A(_11_),
    .B(_13_),
    .Y(_00_[1])
  );
  NOR _51_ (
    .A(clk_2f),
    .B(data_11[2]),
    .Y(_14_)
  );
  NAND _52_ (
    .A(clk_2f),
    .B(_05_),
    .Y(_15_)
  );
  NAND _53_ (
    .A(reset_L),
    .B(_15_),
    .Y(_16_)
  );
  NOR _54_ (
    .A(_14_),
    .B(_16_),
    .Y(_00_[2])
  );
  NOR _55_ (
    .A(clk_2f),
    .B(data_11[3]),
    .Y(_17_)
  );
  NAND _56_ (
    .A(clk_2f),
    .B(_06_),
    .Y(_18_)
  );
  NAND _57_ (
    .A(reset_L),
    .B(_18_),
    .Y(_19_)
  );
  NOR _58_ (
    .A(_17_),
    .B(_19_),
    .Y(_00_[3])
  );
  NOR _59_ (
    .A(clk_2f),
    .B(data_11[4]),
    .Y(_20_)
  );
  NAND _60_ (
    .A(clk_2f),
    .B(_07_),
    .Y(_21_)
  );
  NAND _61_ (
    .A(reset_L),
    .B(_21_),
    .Y(_22_)
  );
  NOR _62_ (
    .A(_20_),
    .B(_22_),
    .Y(_00_[4])
  );
  NOR _63_ (
    .A(clk_2f),
    .B(data_11[5]),
    .Y(_23_)
  );
  NAND _64_ (
    .A(clk_2f),
    .B(_08_),
    .Y(_24_)
  );
  NAND _65_ (
    .A(reset_L),
    .B(_24_),
    .Y(_25_)
  );
  NOR _66_ (
    .A(_23_),
    .B(_25_),
    .Y(_00_[5])
  );
  NOR _67_ (
    .A(clk_2f),
    .B(data_11[6]),
    .Y(_26_)
  );
  NAND _68_ (
    .A(clk_2f),
    .B(_09_),
    .Y(_27_)
  );
  NAND _69_ (
    .A(reset_L),
    .B(_27_),
    .Y(_28_)
  );
  NOR _70_ (
    .A(_26_),
    .B(_28_),
    .Y(_00_[6])
  );
  NOR _71_ (
    .A(clk_2f),
    .B(data_11[7]),
    .Y(_29_)
  );
  NAND _72_ (
    .A(clk_2f),
    .B(_10_),
    .Y(_30_)
  );
  NAND _73_ (
    .A(reset_L),
    .B(_30_),
    .Y(_31_)
  );
  NOR _74_ (
    .A(_29_),
    .B(_31_),
    .Y(_00_[7])
  );
  NOR _75_ (
    .A(valid_11),
    .B(clk_2f),
    .Y(_32_)
  );
  NAND _76_ (
    .A(_02_),
    .B(clk_2f),
    .Y(_33_)
  );
  NAND _77_ (
    .A(reset_L),
    .B(_33_),
    .Y(_34_)
  );
  NOR _78_ (
    .A(_32_),
    .B(_34_),
    .Y(_01_)
  );
  NOR _79_ (
    .A(clk_2f),
    .B(data_11[0]),
    .Y(_35_)
  );
  NAND _80_ (
    .A(clk_2f),
    .B(_03_),
    .Y(_36_)
  );
  NAND _81_ (
    .A(reset_L),
    .B(_36_),
    .Y(_37_)
  );
  NOR _82_ (
    .A(_35_),
    .B(_37_),
    .Y(_00_[0])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _83_ (
    .C(clk_4f),
    .D(_00_[0]),
    .Q(data_000[0])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _84_ (
    .C(clk_4f),
    .D(_00_[1]),
    .Q(data_000[1])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _85_ (
    .C(clk_4f),
    .D(_00_[2]),
    .Q(data_000[2])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _86_ (
    .C(clk_4f),
    .D(_00_[3]),
    .Q(data_000[3])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _87_ (
    .C(clk_4f),
    .D(_00_[4]),
    .Q(data_000[4])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _88_ (
    .C(clk_4f),
    .D(_00_[5]),
    .Q(data_000[5])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _89_ (
    .C(clk_4f),
    .D(_00_[6]),
    .Q(data_000[6])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _90_ (
    .C(clk_4f),
    .D(_00_[7]),
    .Q(data_000[7])
  );
  (* src = "MUX_L2.v:41" *)
  DFF _91_ (
    .C(clk_4f),
    .D(_01_),
    .Q(valid_000)
  );
endmodule
