/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Serial_paralelo_tx.v:1" *)
module serial_paralelo_synth(clk_4f, clk_32f, data_in, reset, idle);
  (* src = "Serial_paralelo_tx.v:16" *)
  wire [2:0] _000_;
  (* src = "Serial_paralelo_tx.v:35" *)
  wire [2:0] _001_;
  (* src = "Serial_paralelo_tx.v:35" *)
  wire [7:0] _002_;
  (* src = "Serial_paralelo_tx.v:16" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  (* src = "Serial_paralelo_tx.v:10" *)
  wire [2:0] BC_counter;
  (* src = "Serial_paralelo_tx.v:4" *)
  input clk_32f;
  (* src = "Serial_paralelo_tx.v:3" *)
  input clk_4f;
  (* src = "Serial_paralelo_tx.v:10" *)
  wire [2:0] cont;
  (* src = "Serial_paralelo_tx.v:12" *)
  wire [7:0] data2out;
  (* src = "Serial_paralelo_tx.v:5" *)
  input data_in;
  (* src = "Serial_paralelo_tx.v:7" *)
  output idle;
  (* src = "Serial_paralelo_tx.v:6" *)
  input reset;
  NOT _082_ (
    .A(data2out[6]),
    .Y(_023_)
  );
  NOT _083_ (
    .A(data2out[7]),
    .Y(_024_)
  );
  NOT _084_ (
    .A(BC_counter[0]),
    .Y(_025_)
  );
  NOT _085_ (
    .A(BC_counter[1]),
    .Y(_026_)
  );
  NOT _086_ (
    .A(data_in),
    .Y(_027_)
  );
  NOT _087_ (
    .A(reset),
    .Y(_028_)
  );
  NOT _088_ (
    .A(data2out[3]),
    .Y(_029_)
  );
  NOT _089_ (
    .A(cont[0]),
    .Y(_030_)
  );
  NOT _090_ (
    .A(cont[1]),
    .Y(_031_)
  );
  NOT _091_ (
    .A(cont[2]),
    .Y(_032_)
  );
  NOR _092_ (
    .A(data2out[0]),
    .B(data2out[1]),
    .Y(_033_)
  );
  NAND _093_ (
    .A(data2out[3]),
    .B(data2out[2]),
    .Y(_034_)
  );
  NOT _094_ (
    .A(_034_),
    .Y(_035_)
  );
  NAND _095_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  NOT _096_ (
    .A(_036_),
    .Y(_037_)
  );
  NOR _097_ (
    .A(BC_counter[0]),
    .B(BC_counter[1]),
    .Y(_038_)
  );
  NAND _098_ (
    .A(BC_counter[2]),
    .B(_038_),
    .Y(_039_)
  );
  NAND _099_ (
    .A(data2out[5]),
    .B(data2out[4]),
    .Y(_040_)
  );
  NOT _100_ (
    .A(_040_),
    .Y(_041_)
  );
  NOR _101_ (
    .A(data2out[7]),
    .B(_040_),
    .Y(_042_)
  );
  NAND _102_ (
    .A(data2out[6]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _103_ (
    .A(_039_),
    .B(_043_),
    .Y(_044_)
  );
  NOT _104_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _105_ (
    .A(_036_),
    .B(_045_),
    .Y(_003_)
  );
  NOR _106_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_046_)
  );
  NAND _107_ (
    .A(_032_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _108_ (
    .A(_024_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _109_ (
    .A(data_in),
    .B(_047_),
    .Y(_049_)
  );
  NAND _110_ (
    .A(reset),
    .B(_048_),
    .Y(_050_)
  );
  NOR _111_ (
    .A(_049_),
    .B(_050_),
    .Y(_002_[7])
  );
  NAND _112_ (
    .A(cont[0]),
    .B(_031_),
    .Y(_051_)
  );
  NOR _113_ (
    .A(cont[2]),
    .B(_051_),
    .Y(_052_)
  );
  NOR _114_ (
    .A(data2out[6]),
    .B(_052_),
    .Y(_053_)
  );
  NAND _115_ (
    .A(_027_),
    .B(_052_),
    .Y(_054_)
  );
  NAND _116_ (
    .A(reset),
    .B(_054_),
    .Y(_055_)
  );
  NOR _117_ (
    .A(_053_),
    .B(_055_),
    .Y(_002_[6])
  );
  NAND _118_ (
    .A(_030_),
    .B(cont[1]),
    .Y(_056_)
  );
  NOR _119_ (
    .A(cont[2]),
    .B(_056_),
    .Y(_057_)
  );
  NOR _120_ (
    .A(data2out[5]),
    .B(_057_),
    .Y(_058_)
  );
  NAND _121_ (
    .A(_027_),
    .B(_057_),
    .Y(_059_)
  );
  NAND _122_ (
    .A(reset),
    .B(_059_),
    .Y(_060_)
  );
  NOR _123_ (
    .A(_058_),
    .B(_060_),
    .Y(_002_[5])
  );
  NAND _124_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_061_)
  );
  NOR _125_ (
    .A(cont[2]),
    .B(_061_),
    .Y(_062_)
  );
  NOR _126_ (
    .A(data2out[4]),
    .B(_062_),
    .Y(_063_)
  );
  NAND _127_ (
    .A(_027_),
    .B(_062_),
    .Y(_064_)
  );
  NAND _128_ (
    .A(reset),
    .B(_064_),
    .Y(_065_)
  );
  NOR _129_ (
    .A(_063_),
    .B(_065_),
    .Y(_002_[4])
  );
  NAND _130_ (
    .A(cont[2]),
    .B(_046_),
    .Y(_066_)
  );
  NAND _131_ (
    .A(_029_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _132_ (
    .A(data_in),
    .B(_066_),
    .Y(_068_)
  );
  NAND _133_ (
    .A(reset),
    .B(_067_),
    .Y(_069_)
  );
  NOR _134_ (
    .A(_068_),
    .B(_069_),
    .Y(_002_[3])
  );
  NOR _135_ (
    .A(_032_),
    .B(_051_),
    .Y(_070_)
  );
  NOR _136_ (
    .A(data2out[2]),
    .B(_070_),
    .Y(_071_)
  );
  NAND _137_ (
    .A(_027_),
    .B(_070_),
    .Y(_072_)
  );
  NAND _138_ (
    .A(reset),
    .B(_072_),
    .Y(_073_)
  );
  NOR _139_ (
    .A(_071_),
    .B(_073_),
    .Y(_002_[2])
  );
  NOR _140_ (
    .A(_032_),
    .B(_056_),
    .Y(_074_)
  );
  NOR _141_ (
    .A(data2out[1]),
    .B(_074_),
    .Y(_075_)
  );
  NAND _142_ (
    .A(_027_),
    .B(_074_),
    .Y(_076_)
  );
  NAND _143_ (
    .A(reset),
    .B(_076_),
    .Y(_077_)
  );
  NOR _144_ (
    .A(_075_),
    .B(_077_),
    .Y(_002_[1])
  );
  NOR _145_ (
    .A(_032_),
    .B(_061_),
    .Y(_078_)
  );
  NOR _146_ (
    .A(data2out[0]),
    .B(_078_),
    .Y(_079_)
  );
  NAND _147_ (
    .A(_027_),
    .B(_078_),
    .Y(_080_)
  );
  NAND _148_ (
    .A(reset),
    .B(_080_),
    .Y(_081_)
  );
  NOR _149_ (
    .A(_079_),
    .B(_081_),
    .Y(_002_[0])
  );
  NOR _150_ (
    .A(_028_),
    .B(cont[0]),
    .Y(_001_[0])
  );
  NAND _151_ (
    .A(reset),
    .B(_061_),
    .Y(_004_)
  );
  NOR _152_ (
    .A(_046_),
    .B(_004_),
    .Y(_001_[1])
  );
  NAND _153_ (
    .A(_032_),
    .B(_061_),
    .Y(_005_)
  );
  NAND _154_ (
    .A(reset),
    .B(_005_),
    .Y(_006_)
  );
  NOR _155_ (
    .A(_078_),
    .B(_006_),
    .Y(_001_[2])
  );
  NOR _156_ (
    .A(data2out[6]),
    .B(_024_),
    .Y(_007_)
  );
  NAND _157_ (
    .A(_023_),
    .B(data2out[7]),
    .Y(_008_)
  );
  NOR _158_ (
    .A(_040_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _159_ (
    .A(_041_),
    .B(_007_),
    .Y(_010_)
  );
  NOR _160_ (
    .A(_036_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _161_ (
    .A(_037_),
    .B(_009_),
    .Y(_012_)
  );
  NOR _162_ (
    .A(BC_counter[0]),
    .B(_028_),
    .Y(_013_)
  );
  NAND _163_ (
    .A(_039_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _164_ (
    .A(_012_),
    .B(_014_),
    .Y(_000_[0])
  );
  NOR _165_ (
    .A(_025_),
    .B(_026_),
    .Y(_015_)
  );
  NOR _166_ (
    .A(_038_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _167_ (
    .A(reset),
    .B(_016_),
    .Y(_017_)
  );
  NOR _168_ (
    .A(_012_),
    .B(_017_),
    .Y(_000_[1])
  );
  NOR _169_ (
    .A(_038_),
    .B(_011_),
    .Y(_018_)
  );
  NAND _170_ (
    .A(BC_counter[2]),
    .B(_015_),
    .Y(_019_)
  );
  NOR _171_ (
    .A(BC_counter[2]),
    .B(_015_),
    .Y(_020_)
  );
  NOR _172_ (
    .A(_028_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _173_ (
    .A(_019_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _174_ (
    .A(_018_),
    .B(_022_),
    .Y(_000_[2])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _175_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(data2out[0])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _176_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(data2out[1])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _177_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(data2out[2])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _178_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(data2out[3])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _179_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(data2out[4])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _180_ (
    .C(clk_32f),
    .D(_002_[5]),
    .Q(data2out[5])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _181_ (
    .C(clk_32f),
    .D(_002_[6]),
    .Q(data2out[6])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _182_ (
    .C(clk_32f),
    .D(_002_[7]),
    .Q(data2out[7])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _183_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(cont[0])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _184_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(cont[1])
  );
  (* src = "Serial_paralelo_tx.v:35" *)
  DFF _185_ (
    .C(clk_32f),
    .D(_001_[2]),
    .Q(cont[2])
  );
  (* src = "Serial_paralelo_tx.v:16" *)
  DFF _186_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "Serial_paralelo_tx.v:16" *)
  DFF _187_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "Serial_paralelo_tx.v:16" *)
  DFF _188_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "Serial_paralelo_tx.v:16" *)
  DFF _189_ (
    .C(clk_4f),
    .D(_003_),
    .Q(idle)
  );
endmodule
