/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "paralelo_serial_rx.v:1" *)
module paralelo_serial_rx_synth(active, idle_out);
  (* src = "paralelo_serial_rx.v:1" *)
  input active;
  (* src = "paralelo_serial_rx.v:1" *)
  output [7:0] idle_out;
  NOT _0_ (
    .A(active),
    .Y(idle_out[7])
  );
  BUF _1_ (
    .A(active),
    .Y(idle_out[6])
  );
  assign idle_out[5:0] = 6'h3c;
endmodule
